<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ANSALDI Lucile, BARREAU Julie, BONGIBAULT Baptiste, GUINEBRETIERE Aldric, MOREAU Cyrielle">

<title>The Companion book a M1 MODE student should have! - Multivariate analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">The Companion book a M1 MODE student should have!</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MarieEtienne/MODE_reproduciblescience" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./prior_course.html" rel="" target="">
 <span class="menu-text">Before the class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./instructions.html" rel="" target="">
 <span class="menu-text">Instructions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses-materials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Courses Materials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-courses-materials">    
        <li>
    <a class="dropdown-item" href="https://marieetienne.github.io/reproductibilite/_presentation/english_version.html" rel="" target="">
 <span class="dropdown-text">Git Intro</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-m1-mode-survival-book-by-the-m2-students" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">M1 MODE Survival book by the M2 students</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-m1-mode-survival-book-by-the-m2-students">    
        <li>
    <a class="dropdown-item" href="./AMV_chapter.html" rel="" target="">
 <span class="dropdown-text">Multivariate Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./linear_modelling.html" rel="" target="">
 <span class="dropdown-text">Linear modelling in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Mixed_models.html" rel="" target="">
 <span class="dropdown-text">Mixed models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chapter_dependance.html" rel="" target="">
 <span class="dropdown-text">Dependent data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Matrix.html" rel="" target="">
 <span class="dropdown-text">Matrix models and applications in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Chap_ODE.html" rel="" target="">
 <span class="dropdown-text">Ordinary Differential Equations in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./r_chapter_boostrapping_resampling.html" rel="" target="">
 <span class="dropdown-text">Resampling methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bayesian_modeles.html" rel="" target="">
 <span class="dropdown-text">Bayesian models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./simple_chapter.html" rel="" target="">
 <span class="dropdown-text">A simple chapter with no code</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-multivariates-analysis" id="toc-introduction-to-multivariates-analysis" class="nav-link active" data-scroll-target="#introduction-to-multivariates-analysis">Introduction to Multivariates Analysis</a></li>
  <li><a href="#part-1-pca" id="toc-part-1-pca" class="nav-link" data-scroll-target="#part-1-pca">PART 1: PCA</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#mathematics" id="toc-mathematics" class="nav-link" data-scroll-target="#mathematics">Mathematics</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#a-importing-the-dataset" id="toc-a-importing-the-dataset" class="nav-link" data-scroll-target="#a-importing-the-dataset">a) Importing the dataset :</a></li>
  <li><a href="#b-study-of-correlations" id="toc-b-study-of-correlations" class="nav-link" data-scroll-target="#b-study-of-correlations">b) Study of correlations :</a></li>
  <li><a href="#c-performing-pca" id="toc-c-performing-pca" class="nav-link" data-scroll-target="#c-performing-pca">c) Performing PCA :</a></li>
  <li><a href="#d-interpretation-of-outputs" id="toc-d-interpretation-of-outputs" class="nav-link" data-scroll-target="#d-interpretation-of-outputs">d) Interpretation of outputs :</a></li>
  <li><a href="#e-biological-conclusion" id="toc-e-biological-conclusion" class="nav-link" data-scroll-target="#e-biological-conclusion">e) Biological conclusion :</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-2-ca" id="toc-part-2-ca" class="nav-link" data-scroll-target="#part-2-ca">PART 2: CA</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#mathematics-1" id="toc-mathematics-1" class="nav-link" data-scroll-target="#mathematics-1">Mathematics</a>
  <ul class="collapse">
  <li><a href="#profiles" id="toc-profiles" class="nav-link" data-scroll-target="#profiles">- Profiles</a></li>
  <li><a href="#distances-between-profiles" id="toc-distances-between-profiles" class="nav-link" data-scroll-target="#distances-between-profiles">- Distances between profiles</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence">- Independence</a></li>
  <li><a href="#binary-correspondence-analysis" id="toc-binary-correspondence-analysis" class="nav-link" data-scroll-target="#binary-correspondence-analysis">- Binary Correspondence Analysis</a></li>
  <li><a href="#projection-of-both-analyses-onto-the-same-plane" id="toc-projection-of-both-analyses-onto-the-same-plane" class="nav-link" data-scroll-target="#projection-of-both-analyses-onto-the-same-plane">- Projection of both analyses onto the same plane</a></li>
  </ul></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a>
  <ul class="collapse">
  <li><a href="#a-performing-ca" id="toc-a-performing-ca" class="nav-link" data-scroll-target="#a-performing-ca">a) Performing CA :</a></li>
  <li><a href="#b-interpretation-of-outputs" id="toc-b-interpretation-of-outputs" class="nav-link" data-scroll-target="#b-interpretation-of-outputs">b) Interpretation of outputs :</a></li>
  <li><a href="#c-biological-conclusion" id="toc-c-biological-conclusion" class="nav-link" data-scroll-target="#c-biological-conclusion">c) Biological conclusion :</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-3-mca" id="toc-part-3-mca" class="nav-link" data-scroll-target="#part-3-mca">PART 3: MCA</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2">Introduction</a></li>
  <li><a href="#mathematics-2" id="toc-mathematics-2" class="nav-link" data-scroll-target="#mathematics-2">Mathematics</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  </ul></li>
  <li><a href="#part-4-cca" id="toc-part-4-cca" class="nav-link" data-scroll-target="#part-4-cca">PART 4: CCA</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3">Introduction</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">Interpretation</a></li>
  </ul></li>
  <li><a href="#part-5-rlq" id="toc-part-5-rlq" class="nav-link" data-scroll-target="#part-5-rlq">PART 5: RLQ</a>
  <ul class="collapse">
  <li><a href="#introduction-4" id="toc-introduction-4" class="nav-link" data-scroll-target="#introduction-4">Introduction</a></li>
  <li><a href="#interpretation-4" id="toc-interpretation-4" class="nav-link" data-scroll-target="#interpretation-4">Interpretation</a></li>
  </ul></li>
  <li><a href="#to-go-further-with-multivariate-analysis" id="toc-to-go-further-with-multivariate-analysis" class="nav-link" data-scroll-target="#to-go-further-with-multivariate-analysis">To go further with Multivariate Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multivariate analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ANSALDI Lucile, BARREAU Julie, BONGIBAULT Baptiste, GUINEBRETIERE Aldric, MOREAU Cyrielle </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction-to-multivariates-analysis" class="level1">
<h1>Introduction to Multivariates Analysis</h1>
<p>Biologists’ data, whether on individuals, populations or communities, are usually presented in the form of rectangular tables, with observations (n) in the rows and variables (p) in the columns.</p>
<p>The graphical representation of these n observations and p variables is easily achieved when there are only 2 or 3 variables (dimension). However, when the number of variables increases, the graphical representation becomes complicated, and Multivariate Analyses come into their own!</p>
<p>The aim of these analyses is to reduce the number of dimensions and examine the structure of the data by answering the following questions:</p>
<ul>
<li><p>Which observations are similar?</p></li>
<li><p>Are there observations that stand out? Subgroups?</p></li>
<li><p>Which variables are correlated?</p></li>
<li><p>Are there particular links between certain observations and/or variables?</p></li>
</ul>
<p>Multivariate analysis methods are therefore used to describe the data and generate hypotheses that can then be tested.</p>
</section>
<section id="part-1-pca" class="level1">
<h1>PART 1: PCA</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>PCA can be used to process a measurement table with :</p>
<ul>
<li><p>In row: the <strong>n observations</strong>.</p></li>
<li><p>In column: the <strong>p quantitative variables</strong>.</p></li>
</ul>
<p>The 2 sets (observations and variables) are <strong>totally distinct and non-interchangeable</strong>. In other words, if you interchange the rows and columns (with the variables in the rows and the observations in the columns), the table no longer has the same meaning.</p>
<p>In PCA tables, the mean of a column has a meaning, while the mean of a row does not.</p>
<p>The aim of PCA is to achieve the best geometric representation of individuals and variables. To achieve this, we seek to reduce the dimension by finding the best projection plane (subspace) for “best” visualization of the point cloud in reduced space.</p>
<p>However, this reduction must :</p>
<ul>
<li><p>Two individuals who resemble each other must be close in the representation space.</p></li>
<li><p>Preserve correlations between variables:</p>
<ul>
<li><p>Two variables that are correlated must be represented by vectors forming an acute angle.</p></li>
<li><p>Two independent variables are represented by orthogonal vectors.</p></li>
</ul></li>
</ul>
</section>
<section id="mathematics" class="level2">
<h2 class="anchored" data-anchor-id="mathematics">Mathematics</h2>
<p>Principal Component Analysis (PCA) is a powerful method for simplifying the complexity of highly correlated data. This approach aims to reduce dimensionality in a linear manner, thereby providing a clearer perspective on the underlying structure of the data.</p>
<p>In essence, PCA performs a linear transformation of the original variables to new variables called principal components. These components are carefully selected to capture the majority of the variance present in the dataset, thereby maximizing the separation between different observations.</p>
<p>The space of principal components can be expressed as :</p>
<p><span class="math display">\[
Z_p=\Sigma^p_{j=1}ø_j\times X_j
\]</span>Where :</p>
<ul>
<li><p><span class="math inline">\(Z_p\)</span> is the principal component <span class="math inline">\(p\)</span></p></li>
<li><p><span class="math inline">\(Ø_j\)</span> is the weight vector comprising the <span class="math inline">\(j\)</span> weights for principal component <span class="math inline">\(p\)</span>, i.e., the coefficients of the linear combination of the original variables from which the principal components are constructed.</p></li>
<li><p><span class="math inline">\(X_j\)</span> is the standardized predictor, meaning it has a mean equal to 0 and a standard deviation of 1.</p></li>
</ul>
<p>The process begins with a matrix <span class="math inline">\(Y\)</span>, where each row represents an observation and each column represents a continuous variable.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="table-inds-vars.png" class="img-fluid figure-img" width="230"></p>
</figure>
</div>
<p>First, we normalize the observations as follows :</p>
<p><span class="math display">\[
Y_{std} = \frac{y_i-\overline{y}}{\sigma_y}
\]</span> <em>; which is equivalent to centering as in:</em></p>
<p><span class="math display">\[
y_c= [y_i-\overline{y}]
\]</span> <em>; then scaling as in:</em></p>
<p><span class="math display">\[
y_s = \frac{y_i}{\sigma_y}
\]</span></p>
<p>We can then calculate the variance-covariance matrix:</p>
<p><span class="math display">\[
R = cov(Y_{std})
\]</span>The decomposition of this matrix provides the matrix <span class="math inline">\(U\)</span> of eigenvectors, which contains the principal components.</p>
<p>The eigenvectors, defined as the principal components, have associated eigenvalues. The graphical representation of the distances of observations to these eigenvectors illustrates how each principal component captures the variation in the data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Capture d’écran 2023-11-15 à 16.45.12.png" class="img-fluid figure-img" width="190"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Capture d’écran 2023-11-15 à 16.45.20.png" class="img-fluid figure-img" width="191"></p>
</figure>
</div>
<p>The orthogonal aspect of the principal components becomes evident when observing the second principal component, which, in turn, maximizes the variance in the data. These principal components, each aligned along an orthogonal axis, form a new coordinate system in which the information is more clearly structured.</p>
<p>In addition to representing the variance of the principal components, the eigenvectors also provide a relative understanding of their influence. This influence is calculated by dividing the eigenvalues by the total sum of these values, thus providing context on the contribution of each principal component <span class="math inline">\(v_k\)</span> to the overall information.</p>
<p><span class="math display">\[
Explained\ variance\ of\ v_k = \frac{\lambda_{v_k}}{\Sigma_{i=1}^p\lambda_v}
\]</span>The conclusion of the PCA involves obtaining the coordinate matrix <span class="math inline">\(F\)</span>. This matrix results from the multiplication of matrix <span class="math inline">\(U\)</span> by the standardized matrix <span class="math inline">\(Y_{std}\)</span>, enabling a rotation of the new data space. This process aligns the data along the principal components, providing a simplified yet informative view of the underlying structure of the initial data.</p>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Here’s an example of how PCA can be applied. <em>dataset presentation</em> <em>package needed</em></p>
<section id="a-importing-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="a-importing-the-dataset">a) Importing the dataset :</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading the "iris" dataset available on R :</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"decathlon2"</span>) </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span>decathlon2[decathlon2<span class="sc">$</span>Competition<span class="sc">==</span><span class="st">"OlympicG"</span>,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">12</span>)]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     X100m         Long.jump        Shot.put       High.jump    
 Min.   :10.44   Min.   :6.990   Min.   :13.07   Min.   :1.880  
 1st Qu.:10.72   1st Qu.:7.303   1st Qu.:14.52   1st Qu.:1.940  
 Median :10.88   Median :7.475   Median :14.86   Median :2.045  
 Mean   :10.82   Mean   :7.474   Mean   :14.90   Mean   :2.017  
 3rd Qu.:10.94   3rd Qu.:7.688   3rd Qu.:15.29   3rd Qu.:2.112  
 Max.   :11.14   Max.   :7.960   Max.   :16.36   Max.   :2.150  
     X400m        X110m.hurdle       Discus        Pole.vault   
 Min.   :46.81   Min.   :13.97   Min.   :40.11   Min.   :4.400  
 1st Qu.:48.56   1st Qu.:14.07   1st Qu.:43.90   1st Qu.:4.625  
 Median :49.05   Median :14.23   Median :44.73   Median :4.900  
 Mean   :49.01   Mean   :14.29   Mean   :45.43   Mean   :4.843  
 3rd Qu.:49.41   3rd Qu.:14.36   3rd Qu.:47.66   3rd Qu.:5.000  
 Max.   :50.79   Max.   :14.95   Max.   :51.65   Max.   :5.400  
    Javeline         X1500m          Points    
 Min.   :51.53   Min.   :264.4   Min.   :7926  
 1st Qu.:55.43   1st Qu.:270.5   1st Qu.:8088  
 Median :58.11   Median :276.3   Median :8236  
 Mean   :59.58   Mean   :275.1   Mean   :8317  
 3rd Qu.:62.92   3rd Qu.:278.6   3rd Qu.:8396  
 Max.   :70.52   Max.   :287.6   Max.   :8893  </code></pre>
</div>
</div>
<p>In this data set, we have 14 individuals (athletes) on whom 10 quantitative variables (performances in different sports disciplines) have been recorded:</p>
<ul>
<li><p>X100m</p></li>
<li><p>Long.jump</p></li>
<li><p>Shot.put</p></li>
<li><p>X400m</p></li>
<li><p>X110m.hurdle</p></li>
<li><p>Discus</p></li>
<li><p>Pole.vault</p></li>
<li><p>Javelin</p></li>
<li><p>X1500m</p></li>
</ul>
<p>If NAs are present in the data. In order to carry out the PCA without any problems with NAs, they can be omitted from the analysis with the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data=na.omit(object = data)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We want to find out whether particular links between certain observations and/or variables can be observed in this data set.</p>
</section>
<section id="b-study-of-correlations" class="level3">
<h3 class="anchored" data-anchor-id="b-study-of-correlations">b) Study of correlations :</h3>
<p>Obtain the correlation matrix between variables using the <strong>cor()</strong> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   X100m  Long.jump    Shot.put   High.jump       X400m
X100m         1.00000000 -0.8350966 -0.21746312 -0.26333512  0.54802600
Long.jump    -0.83509656  1.0000000  0.31407521  0.24623935 -0.51919384
Shot.put     -0.21746312  0.3140752  1.00000000  0.77045776 -0.18546890
High.jump    -0.26333512  0.2462394  0.77045776  1.00000000 -0.17357206
X400m         0.54802600 -0.5191938 -0.18546890 -0.17357206  1.00000000
X110m.hurdle  0.38366645 -0.4914562  0.03157435  0.01126452  0.35162059
Discus       -0.51341585  0.5136697  0.88239852  0.71362867 -0.36823138
Pole.vault    0.07021566  0.1578300 -0.41715958 -0.65024394  0.19459315
Javeline     -0.06085398  0.2256900  0.53582882  0.20440490  0.04744169
X1500m       -0.47201188  0.5394643  0.10753385 -0.03189887  0.15026787
Points       -0.64440656  0.7809521  0.76009926  0.60096524 -0.52293108
             X110m.hurdle     Discus  Pole.vault    Javeline      X1500m
X100m          0.38366645 -0.5134159  0.07021566 -0.06085398 -0.47201188
Long.jump     -0.49145618  0.5136697  0.15783003  0.22568995  0.53946433
Shot.put       0.03157435  0.8823985 -0.41715958  0.53582882  0.10753385
High.jump      0.01126452  0.7136287 -0.65024394  0.20440490 -0.03189887
X400m          0.35162059 -0.3682314  0.19459315  0.04744169  0.15026787
X110m.hurdle   1.00000000 -0.1755752  0.05716187  0.23674145 -0.41440555
Discus        -0.17557519  1.0000000 -0.46586569  0.47246648  0.12824707
Pole.vault     0.05716187 -0.4658657  1.00000000  0.08916975  0.42631317
Javeline       0.23674145  0.4724665  0.08916975  1.00000000  0.01073007
X1500m        -0.41440555  0.1282471  0.42631317  0.01073007  1.00000000
Points        -0.23729481  0.8596594 -0.13740583  0.60192747  0.24700780
                 Points
X100m        -0.6444066
Long.jump     0.7809521
Shot.put      0.7600993
High.jump     0.6009652
X400m        -0.5229311
X110m.hurdle -0.2372948
Discus        0.8596594
Pole.vault   -0.1374058
Javeline      0.6019275
X1500m        0.2470078
Points        1.0000000</code></pre>
</div>
</div>
<p>Variables are correlated if their value is greater than 0.9 (as a general rule). Here, we can see that no variables are correlated.</p>
<p>Here’s another way of visualizing correlations between variables: (useful when you have a lot of variables, as here):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(<span class="fu">cor</span>(data))<span class="sc">&gt;</span><span class="fl">0.9</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             X100m Long.jump Shot.put High.jump X400m X110m.hurdle Discus
X100m         TRUE     FALSE    FALSE     FALSE FALSE        FALSE  FALSE
Long.jump    FALSE      TRUE    FALSE     FALSE FALSE        FALSE  FALSE
Shot.put     FALSE     FALSE     TRUE     FALSE FALSE        FALSE  FALSE
High.jump    FALSE     FALSE    FALSE      TRUE FALSE        FALSE  FALSE
X400m        FALSE     FALSE    FALSE     FALSE  TRUE        FALSE  FALSE
X110m.hurdle FALSE     FALSE    FALSE     FALSE FALSE         TRUE  FALSE
Discus       FALSE     FALSE    FALSE     FALSE FALSE        FALSE   TRUE
Pole.vault   FALSE     FALSE    FALSE     FALSE FALSE        FALSE  FALSE
Javeline     FALSE     FALSE    FALSE     FALSE FALSE        FALSE  FALSE
X1500m       FALSE     FALSE    FALSE     FALSE FALSE        FALSE  FALSE
Points       FALSE     FALSE    FALSE     FALSE FALSE        FALSE  FALSE
             Pole.vault Javeline X1500m Points
X100m             FALSE    FALSE  FALSE  FALSE
Long.jump         FALSE    FALSE  FALSE  FALSE
Shot.put          FALSE    FALSE  FALSE  FALSE
High.jump         FALSE    FALSE  FALSE  FALSE
X400m             FALSE    FALSE  FALSE  FALSE
X110m.hurdle      FALSE    FALSE  FALSE  FALSE
Discus            FALSE    FALSE  FALSE  FALSE
Pole.vault         TRUE    FALSE  FALSE  FALSE
Javeline          FALSE     TRUE  FALSE  FALSE
X1500m            FALSE    FALSE   TRUE  FALSE
Points            FALSE    FALSE  FALSE   TRUE</code></pre>
</div>
</div>
<p>If TRUE (outside the diagonal), then both variables are correlated If two variables are correlated, one must be removed. The choice of deleting one of the two correct variables is arbitrary and depends on the question being asked.</p>
<p>To remove a variable from the data set, use the following function: <strong>data=data[,-(column_of_the_variable_to_remove)}]</strong></p>
</section>
<section id="c-performing-pca" class="level3">
<h3 class="anchored" data-anchor-id="c-performing-pca">c) Performing PCA :</h3>
<p>To run the PCA, you need to load the following two packages: <strong>factoextra</strong> and <strong>FactoMineR</strong></p>
<p>Then, to perform the PCA on R, you can use the function : <strong>PCA()</strong>. Remember to store the result of this PCA in a new variable, so that you can easily retrieve the PCA information you need for subsequent interpretation.</p>
</section>
<section id="d-interpretation-of-outputs" class="level3">
<h3 class="anchored" data-anchor-id="d-interpretation-of-outputs">d) Interpretation of outputs :</h3>
<section id="inertia-and-choice-of-axes" class="level4">
<h4 class="anchored" data-anchor-id="inertia-and-choice-of-axes">1) Inertia and choice of axes :</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recover the eigenvalues of each axis and the inertia carried by the principal components</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>PCA<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          eigenvalue percentage of variance cumulative percentage of variance
comp 1  4.753038e+00           4.320944e+01                          43.20944
comp 2  2.418289e+00           2.198444e+01                          65.19388
comp 3  1.551340e+00           1.410310e+01                          79.29698
comp 4  9.863587e-01           8.966897e+00                          88.26388
comp 5  5.554931e-01           5.049937e+00                          93.31381
comp 6  3.216961e-01           2.924510e+00                          96.23832
comp 7  2.203570e-01           2.003246e+00                          98.24157
comp 8  1.149733e-01           1.045212e+00                          99.28678
comp 9  6.178365e-02           5.616696e-01                          99.84845
comp 10 1.666416e-02           1.514924e-01                          99.99994
comp 11 6.323601e-06           5.748728e-05                         100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphical display of the inertia of each axis : </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(PCA, <span class="at">addlabels =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To determine the number of axes used in the PCA analysis, we need to identify the jump in variance explained by the different axes. Here we can see that the first axis represents 43.2% of the variance, the second axis 22%, the third axis 14.1%, …</p>
<p>We can therefore see that the jump in variance explained by the different axes is between the first and second axes. The difference between the variance explained by the axes other than the first is negligible compared to the difference between the first axis and the others.</p>
<p>For the PCA interpretation, we therefore retain the first two axes, which together explain 65.19% of the variance.</p>
</section>
<section id="interpretation-of-the-biological-meaning-of-the-axes" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-the-biological-meaning-of-the-axes">2) Interpretation of the biological meaning of the axes :</h4>
<p>In PCA, the axes are interpreted according to the columns (i.e.&nbsp;variables) via the correlation circle and the absolute contributions of the variables.</p>
<p>To obtain this information in R, use the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the absolute contributions of variables :</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>PCA<span class="sc">$</span>var<span class="sc">$</span>contrib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Dim.1       Dim.2       Dim.3      Dim.4       Dim.5
X100m        10.824776 10.03651625  1.63515357  0.3755928 23.39362182
Long.jump    12.418510 13.24601095  0.18397545  1.0039891  1.29845908
Shot.put     13.118558  8.89903353  2.86005522  2.7322519  1.12053773
High.jump    10.101229 10.94386007  1.34856164  9.6446306  5.75676065
X400m         6.050422  1.75575069 17.68011201 32.4590377  0.09123132
X110m.hurdle  2.265809 13.96580459 10.80010469  7.4256988 54.75065458
Discus       17.620323  2.99067030  0.06343601  0.5423102  0.71456580
Pole.vault    2.249144 16.38731995 23.04479888  4.8414968  0.03149013
Javeline      4.133763  3.25169636 31.78461582  9.3858284 10.87089875
X1500m        1.779257 18.51325372  8.53578854 28.5491707  1.51933507
Points       19.438208  0.01008361  2.06339817  3.0399930  0.45244507</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the circle of correlations :</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(PCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphical representation of absolute variable contribution values for an axis: </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Axis 1 case : </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_contrib</span>(PCA, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Axis 2 case: </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_contrib</span>(PCA, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The absolute contribution shows how the initial variable contributes to the formation of the axis. To find out from these results which variables contribute to the formation of the synthetic axis, we use the threshold of <span class="math inline">\(\frac{1}{nb\_variables}\times100\)</span> (in general). For a variable to contribute, its contribution value must be greater than this threshold. This threshold value corresponds to the red dotted line on the graphs showing the absolute contributions of the variables along the axes.</p>
<p>From these results, we can see that axis 1 is mainly represented by the following variables:</p>
<ul>
<li>Points, Discus, Shotput, Long.jump, X100m, High.jump</li>
</ul>
<p>Axis 2 is represented by the variables:</p>
<ul>
<li>X1500m, Pole.vault, X110m.hurdle, X100m</li>
</ul>
<p>The correlation circle also shows that some variables are related and others independent. Two related variables are represented by vectors forming an acute angle. Two independent variables are represented by orthogonal vectors. Two negatively related variables are represented by two opposite vectors.</p>
</section>
<section id="projection-of-individuals-to-create-a-typology-based-on-the-axes" class="level4">
<h4 class="anchored" data-anchor-id="projection-of-individuals-to-create-a-typology-based-on-the-axes">3) Projection of individuals to create a typology based on the axes:</h4>
<p>For this, we use the relative contributions of the individuals. These relative contributions can be used to create a typology of individuals based on the axes. The relative contribution of an individual corresponds to the share of information on the axis explained by the point and supported on the axis (in percentage).</p>
<p>To obtain the relative contributions of individuals on R, use the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative contributions of individuals :</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>PCA<span class="sc">$</span>ind<span class="sc">$</span>cos2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Dim.1        Dim.2        Dim.3        Dim.4        Dim.5
Sebrle     0.68963196 6.540767e-12 0.1505401735 3.421119e-03 0.0919816558
Clay       0.68982961 7.883438e-02 0.1191186204 1.593953e-04 0.0009981983
Karpov     0.74957187 2.476108e-02 0.1608118952 2.542731e-03 0.0008147725
Macey      0.12167773 7.112491e-01 0.0847580597 1.109719e-04 0.0239527703
Warners    0.03513216 7.035171e-01 0.2043199790 2.553907e-02 0.0041832424
Zsivoczky  0.01766196 7.411226e-01 0.0583141713 1.304529e-02 0.1454252042
Hernu      0.23531031 2.767503e-01 0.1923125481 1.038527e-01 0.0748120286
Bernard    0.03767052 2.359745e-02 0.4446099398 2.664423e-01 0.0658970688
Schwarzl   0.74103094 1.190975e-01 0.0087379756 1.268006e-06 0.0098608763
Pogorelov  0.12049107 2.472670e-02 0.0687218609 7.285021e-01 0.0045896049
Schoenbeck 0.47746580 2.724861e-02 0.2569700383 5.580082e-02 0.0190441531
Barras     0.32981991 4.127756e-01 0.0005470956 1.535366e-02 0.1765554931
Nool       0.23451399 1.310712e-01 0.2420363184 2.449685e-01 0.1242846825
Drews      0.53811419 2.784934e-01 0.1528997775 1.306683e-02 0.0056915740</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtaining the projection of individuals : </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(PCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The individuals who most explain Axis 1 are :</p>
<ul>
<li>Sebrle, Clay, Karpov, Schwarzl, Drews, Schoenbeck</li>
</ul>
<p>Those who most explain axis 2 are :</p>
<ul>
<li>Macey, Warners, Zsivoczky, Barras</li>
</ul>
</section>
</section>
<section id="e-biological-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="e-biological-conclusion">e) Biological conclusion :</h3>
<p>Thus, thanks to the results of the absolute contributions of the variables and the relative contributions of the individuals, we can represent the projection of the individuals and variables as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(PCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Knowing the biological interpretation of the axes :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="PCA_interpretation.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><strong>PCA interpretation</strong></figcaption>
</figure>
</div>
<p>We can therefore see that the individuals with the highest scores at this tournament are those who had the best results in the discus, shot put, long jump and high jump events. In addition, having good results in the 100m race doesn’t give you a good ranking.</p>
<p>Thanks to PCA, we can see that the final score is more linked to the score of certain disciplines than others. And therefore, that links between certain variables and individuals can be observed.</p>
</section>
</section>
</section>
<section id="part-2-ca" class="level1">
<h1>PART 2: CA</h1>
<section id="introduction-1" class="level2">
<h2 class="anchored" data-anchor-id="introduction-1">Introduction</h2>
<p>CA deals with <strong>tables that cross two categorical variables with several modalities</strong>, such as contingency tables, frequency tables, …</p>
<p>In these tables, rows and columns are <strong>interchangeable</strong> and the <strong>variables are all in the same units</strong>.</p>
<p>The aim of CA is to <strong>reveal structures and associations between these qualitative variables</strong> by representing them in a multidimensional space. It <strong>allows us to visualize relationships between categories of different variables, and to highlight trends, groupings or disparities</strong>. It is particularly useful for analyzing categorical data, when you want to understand the underlying structure of the data and identify associations between categories.</p>
<p>Unlike PCA, for a CA, we’re not interested in the distances between points, but in the distances between profiles of different modalities. A CA is therefore simply a PCA on the profiles, by equipping the space with a suitable distance: <strong>the</strong> <span class="math inline">\(\chi^2\)</span> <strong>distance</strong>. With this distance, the weight of rows (or columns) is relativized, but not cancelled out, and the symmetry between rows and columns is preserved.</p>
</section>
<section id="mathematics-1" class="level2">
<h2 class="anchored" data-anchor-id="mathematics-1">Mathematics</h2>
<p>Correspondence Analysis (CA) represents a statistical method aimed at exploring the relationship between two sets of categories. In contrast to PCA, which applies to continuous variables, CA is designed for categorical variables, allowing the analysis of the structure of a contingency table.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Table_de_contingence.png" class="img-fluid figure-img" width="261"></p>
</figure>
</div>
<p>In essence, Correspondence Analysis (CA) seeks to graphically represent associations between rows and columns in a contingency table. It helps reveal trends, groupings, or oppositions within categories, providing insight into the structure of dependence between variables.</p>
<p>The process begins with a contingency table showing the observed frequencies of co-occurrence between different categories. These data are then transformed to obtain a probability table where the frequency of each co-occurrence is calculated as follows:</p>
<p><span class="math display">\[
f_{ij} = \frac{X_{ij}}{n}
\]</span>With <span class="math inline">\(f_{ij}\)</span> representing the probability that events <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> occur jointly, <span class="math inline">\(X_{ij}\)</span> the number of times this co-occurrence has been observed, and <span class="math inline">\(n\)</span> the total number of observations.The marginal probabilities of the columns <span class="math inline">\((f_{.j})\)</span> and rows <span class="math inline">\((f_{i.})\)</span> are calculated as follows:</p>
<p><span class="math display">\[
f_{.j} = \sum_{i=1}^{I}f_{ij}\\\\\\  
f_{i.}=\sum_{j=1}^{J}f_{ij}
\]</span></p>
<section id="profiles" class="level3">
<h3 class="anchored" data-anchor-id="profiles">- Profiles</h3>
<ul>
<li><p>Row profiles</p>
<p>The row profile is <span class="math inline">\(L_i = (\frac{f_{i1}}{f_{i.}},...,\frac{f_{ij}}{f_{i.}})\)</span>. In matrix terms, we will set up <span class="math inline">\(D_n=diag(f_{i.})\)</span> such that <span class="math inline">\(L = D_n^{-1}F\)</span>. We can then define the average row profile, obtained by summing the columns of our frequency table :</p>
<p><span class="math display">\[
(\sum_{i=1}^nf_{i.}\frac{f_{i1}}{f_{i.}},...,\sum_{i=1}^nf_{i.}\frac{f_{ij}}{f_{i.}})=(f_{.1},...,f_{.j})
\]</span></p></li>
<li><p><strong>Column profiles</strong></p>
<p>The column profile is <span class="math inline">\(C_j=(\frac{f_{1j}}{f_{.j}},...,\frac{f_{ij}}{f_{.j}})\)</span>. As with row profiles, it can be expressed and calculated in matrix terms by setting: <span class="math inline">\(D_p=diag(f_{.j})\)</span>, such that <span class="math inline">\(C=D_p^{-1}F^T\)</span>. We can then define the average column profile by summing the rows of our frequency table:</p>
<p><span class="math display">\[
(\sum_{j=1}^pf_{.j}\frac{f_{1j}}{f_{.j}},...,\sum_{j=1}^pf_{.j}\frac{f_{ij}}{f_{i.}})=(f_{1.},...f_{i.})
\]</span></p></li>
</ul>
</section>
<section id="distances-between-profiles" class="level3">
<h3 class="anchored" data-anchor-id="distances-between-profiles">- Distances between profiles</h3>
<p>One can measure the distance between two row profiles by<span class="math display">\[d^2(i,i')=\sum_{j=1}^p(\frac{f_{i j}}{f_{i.}}-\frac{f_{i'j}}{f_{i'.}})^2\]</span></p>
<p>But this distance does not take into account the importance of each column. A more sensible choice is to use the <span class="math inline">\(\chi^2\)</span> distance, which does take the importance of each column into consideration.</p>
<p><span class="math inline">\(d^2(i,i')=\sum_{j=1}^p\frac{1}{f_{.j}}(\frac{f_{i j}}{f_{i.}}-\frac{f_{i'j}}{f_{i'}})^2\)</span></p>
<p>Let’s use the notation <span class="math inline">\(x\)</span> to refer to the vector of distances between two rows <span class="math inline">\(L_{11}-L_{21}\)</span> or between two columns <span class="math inline">\(C_{11}-C_{12}\)</span>. Adopting matrix notation, the square distance of the <span class="math inline">\(\chi^2\)</span> is of the form:</p>
<p><span class="math display">\[
x^TD_p^{-1}x = \sum_{j=1}^p\frac{x^2_j}{f_{.j}}
\]</span>for a row point <span class="math inline">\(x\ \epsilon\ \mathbb{R}^n\)</span> .</p>
</section>
<section id="independence" class="level3">
<h3 class="anchored" data-anchor-id="independence">- Independence</h3>
<p>In the theory of tests, the objective is to determine whether there is a link between the two qualitative variables. The null hypothesis <span class="math inline">\(H_0\)</span> is the independence between the two variables (no effect). The alternative hypothesis <span class="math inline">\(H_1\)</span> is the presence of a link between the two variables.</p>
<p>The association between the two categorical variables is assessed through the discrepancy between the observed data and the independence model.This independence model is calculated based on the following equation:</p>
<p><span class="math display">\[
P(A\ \cap\ B) = P(A) \times P(B)
\]</span>Therefore, the joint probability is the product of the marginal probabilities:</p>
<p><span class="math display">\[
f_{ij} = f_{i.} \times f_{.j}
\]</span>One can then calculate the discrepancy between the observed data <span class="math inline">\((f_{ij})\)</span> and the independence model:</p>
<ul>
<li><p>The significance of the association is measured with a <span class="math inline">\(\chi^2\)</span> test</p>
<p><span class="math display">\[
\chi_{obs}^2 = \sum_{i=1}^I\sum_{j=1}^J\frac{(obs.headcount - th.headcount)^2}{th.headcount}=\sum_{i=1}^I\sum_{j=1}^J\frac{(n\times f_{ij} - n\times f_{i.}\times f_{.j})^2}{n\times f_{i.}\times f_{.j}}
\]</span></p></li>
<li><p>The strength of the association <span class="math inline">\(Ø^2\)</span> is measured by the discrepancy between theoretical and observed probabilities.</p></li>
</ul>
<p><span class="math display">\[
Ø^2 = \sum_{i=1}^I\sum_{j=1}^J\frac{(obs.prob - th.prob)^2}{th.prob}
\]</span></p>
</section>
<section id="binary-correspondence-analysis" class="level3">
<h3 class="anchored" data-anchor-id="binary-correspondence-analysis">- Binary Correspondence Analysis</h3>
<p>By conducting a correspondence analysis, we aim to simultaneously represent the row profiles belonging to <span class="math inline">\(\mathbb{R}^p\)</span> and the column profiles belonging to <span class="math inline">\(\mathbb{R}^n\)</span> of a frequency table. As this representation is done in the Cartesian plane, it will be obtained through a double principal component analysis.</p>
<p>The two principal component analyses are not directly performed on the variables but rather on the row profiles (direct analysis) and the column profiles (dual analysis) presented earlier. Moreover, binary correspondence analysis incorporates the notion of column (or row) weights and the <span class="math inline">\(\chi^2\)</span> distance.</p>
<section id="direct-analysis-rows" class="level4">
<h4 class="anchored" data-anchor-id="direct-analysis-rows">- Direct Analysis (Rows)</h4>
<p>The direct analysis is performed on the row profiles. The rows of <span class="math inline">\(L = D_n^{-1}F\)</span> are elements of <span class="math inline">\(\mathbb{R}^p\)</span>. We aim to represent them in this space using the distance function <span class="math inline">\(x^TD_p^{-1}x\)</span>.</p>
<p>In the direct analysis, we seek the vector <span class="math inline">\(u\ \epsilon\ \mathbb{R}^p\)</span> such as :</p>
<p><span class="math display">\[
(u^TD_p^{-1}F^TD_n^{-1})D_n(D_n^{-1}FD_p^{-1}u)
\]</span></p>
<p><em>With</em> <span class="math inline">\(F\)</span> <em>: the observed frequency matrix</em></p>
<p>is maximal, given that <span class="math inline">\(u^TD_p^{-1}u=1\)</span>.</p>
<p>The solution is given by the principal eigenvector of</p>
<p><span class="math display">\[
D_pD_p^{-1}F^TD_n^{-1}FD_p^{-1}=F^TD_n^{-1}FD_p^{-1}\equiv S
\]</span></p>
</section>
<section id="dual-analysis-columns" class="level4">
<h4 class="anchored" data-anchor-id="dual-analysis-columns">- Dual Analysis (Columns)</h4>
<p>Dual analysis is performed on the column profiles. The rows of <span class="math inline">\(C = D_p^{-1}F^T\)</span> are elements of <span class="math inline">\(\mathbb{R}^n\)</span>. We aim to represent them in this space using the distance function <span class="math inline">\(x^TD-n^{-1}x\)</span>.</p>
<p>In dual analysis, we seek the vector <span class="math inline">\(v\ \epsilon\ \mathbb{R}^n\)</span> such as</p>
<p><span class="math display">\[
(v^TD_n^{-1}FD_p^{-1})D_p(D_p^{-1}F^TD-n^{-1}v)
\]</span>is maximal, given that <span class="math inline">\(v^TD_n^{-1}v=1\)</span>.</p>
<p>The solution is given by the principal eigenvector of</p>
<p><span class="math display">\[
D_n(D_n^{-1}FD_p^{-1}F^TD_n^{-1})=FD_p^{-1}F^TD_n^{-1}\equiv T
\]</span></p>
</section>
</section>
<section id="projection-of-both-analyses-onto-the-same-plane" class="level3">
<h3 class="anchored" data-anchor-id="projection-of-both-analyses-onto-the-same-plane">- Projection of both analyses onto the same plane</h3>
<p>The usual goal of correspondence analysis is to produce a 2-dimensional graph that summarizes the information contained in the frequency table and highlights different interesting associations. In other words, we want to somehow overlay the figures resulting from dual and direct analyses.</p>
<p>To present both analyses in the same plane, it is essential to ensure that both PCAs project the data into the same dimensions. The transition relationships and the concept of the center of gravity presented in the following sections allow us to ensure that we are indeed projecting the “individuals” from dual and direct analyses into the same dimensions.</p>
<section id="transition-relationships" class="level4">
<h4 class="anchored" data-anchor-id="transition-relationships">- Transition Relationships</h4>
<p>The following relationships</p>
<p><span class="math display">\[
D_n^{-1}F\varphi_j=\sqrt{\lambda_j}\Psi_j\equiv \hat{\Psi}_j
\]</span></p>
<p><span class="math display">\[
D_p^{-1}F^T\Psi_j=\sqrt{\lambda_j}\varphi_j\equiv \hat{\varphi}_j
\]</span></p>
<p><em>With</em> <span class="math inline">\(\varphi_j\)</span> : <em>the</em> eigenvector <em>associated with the eigenvalue</em> <span class="math inline">\(\lambda_j\)</span> <em>of the matrix F;</em> <span class="math inline">\(\Psi_j\)</span> : <em>the</em> modality <em>coordinates of the row variable in the row space defined by the eigenvalues;</em> <span class="math inline">\(\hat{\Psi}_j\)</span> <em>the</em> contrinution <em>of the component</em> <span class="math inline">\(j\)</span> <em>to the row variable in the row space and</em> <span class="math inline">\(\hat{\varphi}_j\)</span> <em>the</em> contrinution <em>of the component</em> <span class="math inline">\(j\)</span> <em>to the column variable in the column space</em></p>
<p>establish an almost barycentric link between the two types of analysis, meaning that the coordinates of points in one space are proportional to the components of the factor from the other space corresponding to the same eigenvalue.</p>
<p>Verification: The first relationship is confirmed as follows.</p>
<p><span class="math display">\[
D_n^{-1}F\varphi_j=D_n^{-1}(FD_p^{-1}u_j) = D_n^{-1}(\sqrt{\lambda_j}v_j)=\sqrt{\lambda_j}\Psi_j
\]</span>The second identity is demonstrated in a similar manner.</p>
<p>The consequences of the preceding transition relationships are that…</p>
<ol type="1">
<li><p><span class="math inline">\(1=\lambda_1 \geq \lambda_2 \geq … \geq \lambda_p \geq 0\)</span></p></li>
<li><p><span class="math inline">\((f_1,…,f_p)^T\)</span> is an eigenvector associated with the eigenvalue <span class="math inline">\(\lambda_1=1\)</span> of <span class="math inline">\(S=F^TD_n^{-1}FD_p^{-1}\)</span>.</p>
<p>Note that since the first eigenvalue is always equal to one, many software packages only mention the other <span class="math inline">\(p-1\)</span> eigenvalues.</p></li>
</ol>
</section>
<section id="center-of-gravity" class="level4">
<h4 class="anchored" data-anchor-id="center-of-gravity">- Center of Gravity</h4>
<p>To project the observations onto the same plane, we need to determine the origin of the graph.</p>
<p>The center of gravity of the rows is defined by <span class="math inline">\(G_L=(g_1,…,g_p)^T\)</span>, where</p>
<p><span class="math display">\[
g_j=\sum_{i=1}^nf_i\frac{f_{ij}}{f_i}=\sum_{i=1}^nf_{ij}=f_j, 1\leq j \leq p
\]</span>Similarly, the center of gravity of the columns is defined by</p>
<p><span class="math display">\[
G_C=(f_1,...,f_n)^T
\]</span>Centering of the rows is obtained by calculating</p>
<p><span class="math display">\[
\frac{f_{ij}}{f_i}-g_j=\frac{f_{ij}}{f_i}-f_j=\frac{f_{ij}-f_if_j}{f_i}
\]</span>so that <span class="math inline">\(\sum_{j=1}^p\frac{f_{ij}-f_if_j}{f_i}=0\)</span></p>
<p>for all <span class="math inline">\(i\ \epsilon\)</span> <span class="math inline">\({1,…,n}\)</span>.</p>
<p>The consequence of centering the rows is that the analysis is no longer conducted on <span class="math inline">\(S=F^TD_n^{-1}FD_p^{-1}\)</span> but rather on <span class="math inline">\(S*=(s^*_{jj'})\)</span>, where</p>
<p><span class="math display">\[
s^*_{jj'}=\sum_{i=1}^n\frac{(f_{ij}-f_if_j)(f_{ij'}-f_if_j)}{f_if_{j'}}
\]</span>To detect associations between rows and columns, one must establish a connection with the statistic of the <span class="math inline">\(\chi^2\)</span> test.</p>
<p>By definition, <span class="math inline">\(trace(S*)=\sum_{j=1}^p\sum_{i=1}^n\frac{(f_{ij}-f_if_j)^2}{f_if_j}\)</span></p>
</section>
</section>
</section>
<section id="interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-1">Interpretation</h2>
<p>Here’s an example of how CA can be applied.</p>
<p>You can import R package using the code</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the dataset :</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 1: Create eye and hair color vectors</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>colors_of_eyes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Blue"</span>, <span class="st">"Brown"</span>, <span class="st">"Green"</span>, <span class="st">"Gray"</span>, <span class="st">"Black"</span>, <span class="st">"Yellow"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>hair_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Black"</span>, <span class="st">"Brown"</span>, <span class="st">"Blond"</span>, <span class="st">"Redhead"</span>, <span class="st">"Chestnut"</span>, <span class="st">"Blues"</span>, <span class="st">"White"</span>, <span class="st">"Pink"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 2: Create a data array with fixed values</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>fixed_values <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">50</span>, <span class="dv">35</span>, <span class="dv">32</span>, <span class="dv">24</span>, <span class="dv">0</span>, <span class="dv">0</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="dv">15</span>, <span class="dv">84</span>, <span class="dv">34</span>, <span class="dv">18</span>, <span class="dv">16</span>, <span class="dv">0</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">0</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">0</span>, <span class="dv">21</span>, <span class="dv">34</span>, <span class="dv">6</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">13</span>, <span class="dv">24</span>,</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">12</span>, <span class="dv">0</span>, <span class="dv">10</span>,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>, <span class="dv">20</span>, <span class="dv">5</span>, <span class="dv">46</span>, <span class="dv">2</span>, <span class="dv">5</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>), <span class="at">nrow =</span> <span class="fu">length</span>(hair_colors), <span class="at">ncol =</span> <span class="fu">length</span>(colors_of_eyes))</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Store the matrix in an array variable : </span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(fixed_values)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Name rows and columns</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> colors_of_eyes</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(data) <span class="ot">&lt;-</span> hair_colors</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Blue Brown Green Gray Black Yellow
Black      50    34    10    5     2      0
Brown      35    18     0    3     5     10
Blond      32    16     0    1    13      1
Redhead    24     0    18    0    24     20
Chestnut    0     7     0    0     9      5
Blues       0     4    21    3    10     46
White      15     1    34    8     0      2
Pink       84    20     6    4    12      5</code></pre>
</div>
</div>
<p>This table shows the number of people with each eye color (in columns) and hair color (in rows), for a total of 617 people sampled.</p>
<p>By performing a CA on this dataset, we seek to show the correspondences/oppositions between the different modalities of a variable.</p>
<section id="a-performing-ca" class="level3">
<h3 class="anchored" data-anchor-id="a-performing-ca">a) Performing CA :</h3>
<p>To run the CA, such as the PCA, you need to load the following two packages: <strong>factoextra</strong> and <strong>FactoMineR</strong>.</p>
<p>Then, to perform the CA on R, you can use the function : <strong>CA()</strong>. Remember to store the result of this PCA in a new variable, so that you can easily retrieve the PCA information you need for subsequent interpretation.</p>
<div class="cell" data-hide="true">
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In a CA, rows are called <strong>rows</strong> and columns called <strong>col</strong>.</p>
</section>
<section id="b-interpretation-of-outputs" class="level3">
<h3 class="anchored" data-anchor-id="b-interpretation-of-outputs">b) Interpretation of outputs :</h3>
<section id="inertia-and-choice-of-axes-1" class="level4">
<h4 class="anchored" data-anchor-id="inertia-and-choice-of-axes-1">1) Inertia and choice of axes :</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recover the eigenvalues of each axis and the inertia carried by the principal components</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>CA<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       eigenvalue percentage of variance cumulative percentage of variance
dim 1 0.415178377             55.3969063                          55.39691
dim 2 0.215052153             28.6942303                          84.09114
dim 3 0.073125570              9.7570841                          93.84822
dim 4 0.043902740              5.8579062                          99.70613
dim 5 0.002202466              0.2938732                         100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphical display of the inertia of each axis : </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(CA, <span class="at">addlabels =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To determine the number of axes used in the CA analysis, we need to identify the jump in variance explained by the different axes. It’s the same as for PCA. Here we can see that the first axis represents 55.4% of the variance, the second axis 28.7%, the third axis 9.8%, …</p>
<p>We can therefore see that the jump in variance explained by the different axes is between the first and second axes. The difference between the variance explained by the axes other than the first is negligible compared to the difference between the first axis and the others.</p>
<p>For the CA interpretation, we therefore retain the first two axes, which together explain 65.19% of the variance.</p>
</section>
<section id="interpretation-of-the-biological-meaning-of-the-axes-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-the-biological-meaning-of-the-axes-1">2) Interpretation of the biological meaning of the axes :</h4>
<p>In CA, in contrast to PCA, axes are interpreted either column-wise or row-wise. The choice depends on the initial biological question.</p>
<p>Here we’ll interpret the axes according to the lines, i.e.&nbsp;according to the hair colors. To find out which variables contribute to the synthetic axis, we use the threshold of : <span class="math inline">\(\frac{1}{nb\_variables}\)</span></p>
<p>The threshold in our case is: <span class="math inline">\(\frac{1}{8}\)</span>.</p>
<p>To obtain this information in R, use the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtaining absolute line contribution values : </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>Row_contrib<span class="ot">=</span>CA<span class="sc">$</span>row<span class="sc">$</span>contrib</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Row_contrib<span class="sc">&gt;</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Dim 1 Dim 2 Dim 3 Dim 4 Dim 5
Black     TRUE FALSE  TRUE FALSE  TRUE
Brown    FALSE FALSE FALSE FALSE  TRUE
Blond    FALSE FALSE FALSE FALSE FALSE
Redhead  FALSE FALSE  TRUE FALSE  TRUE
Chestnut FALSE  TRUE FALSE  TRUE FALSE
Blues     TRUE FALSE  TRUE FALSE FALSE
White    FALSE  TRUE FALSE FALSE FALSE
Pink      TRUE FALSE FALSE  TRUE FALSE</code></pre>
</div>
</div>
<p>According to these results, the lines explaining the first axis are :</p>
<ul>
<li>Black, Blues, Pink</li>
</ul>
<p>The lines explaining the second axis are :</p>
<ul>
<li>Chestnut, White</li>
</ul>
</section>
<section id="interpretation-of-relatives-contributions" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-relatives-contributions">3) Interpretation of relatives contributions :</h4>
<p>Relative contributions represent the quality of representation of the column/row by the axis.</p>
<p>Either the rows or the columns are interpreted, depending on the choice made in the next step. In our case, we chose the columns, since we interpreted the axes with the absolute contributions of the rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain relative column contribution values :</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>CA<span class="sc">$</span>col<span class="sc">$</span>cos2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Dim 1      Dim 2      Dim 3       Dim 4        Dim 5
Blue   0.85575259 0.01448471 0.00950636 0.120205825 5.051631e-05
Brown  0.57556811 0.05455375 0.17954769 0.189337969 9.924835e-04
Green  0.45208660 0.52672933 0.01096464 0.008743165 1.476265e-03
Gray   0.01081361 0.82960368 0.08394864 0.020223487 5.541059e-02
Black  0.06314083 0.46740988 0.41166914 0.056819078 9.610773e-04
Yellow 0.74157647 0.18279275 0.05802235 0.017605743 2.692628e-06</code></pre>
</div>
</div>
<p>Blue and yellow eye colors are well represented by axis 1. Grey eye color is represented by axis 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative line contribution values : </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>CA<span class="sc">$</span>row<span class="sc">$</span>cos2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Dim 1       Dim 2      Dim 3       Dim 4        Dim 5
Black    0.69781032 0.070862823 0.15315848 0.066726581 1.144180e-02
Brown    0.52754846 0.167378322 0.26792495 0.020035304 1.711296e-02
Blond    0.69002130 0.182751826 0.08463182 0.041935390 6.596638e-04
Redhead  0.49239795 0.083209727 0.41251121 0.007108659 4.772456e-03
Chestnut 0.03638017 0.564361623 0.02919618 0.365627649 4.434383e-03
Blues    0.87482351 0.049760467 0.07057401 0.004824928 1.708337e-05
White    0.15364853 0.827793121 0.00721218 0.010354558 9.916087e-04
Pink     0.78192585 0.000285946 0.02156349 0.195417315 8.073975e-04</code></pre>
</div>
</div>
<p>This verifies that the modalities that contribute most to the formation of the first two axes all have a good representation quality (not always the case).</p>
</section>
</section>
<section id="c-biological-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="c-biological-conclusion">c) Biological conclusion :</h3>
<p>For the question of links between modalities in rows or columns, you need to know that :</p>
<ul>
<li><p>If we have a positive sclaire product, i.e.&nbsp;less than 90 degree difference between the arrows of two different modalities. Then we have a conjunction representing an affinity between these two modalities.</p></li>
<li><p>If we have a negative scalar product, i.e.&nbsp;more than 90? difference between the arrows of two different modalities. Then we have an opposition of these two modalities. They reject each other.</p></li>
<li><p>If we have a zero scalar product, i.e.&nbsp;the arrows between two different modalities are perpendicular. Then there is no link between these two modalities.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_ca_biplot</span>(CA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>On this graph, the rows are shown in blue and the columns in red. In other words, hair color in blue and eye color in red.</p>
<p>From this analysis, we can see :</p>
<ul>
<li><p>A conjunction between black, pink, brown or blond hair and blue or brown eyes.</p></li>
<li><p>A conjunction between yellow eyes and blue hair</p></li>
<li><p>An opposition between these two groups on axis 1.</p></li>
</ul>
<p>In an analysis where the data are not created randomly, but come from different individuals from different populations. This could reveal a particular typology of one population in relation to another.</p>
</section>
</section>
</section>
<section id="part-3-mca" class="level1">
<h1>PART 3: MCA</h1>
<section id="introduction-2" class="level2">
<h2 class="anchored" data-anchor-id="introduction-2">Introduction</h2>
<p>MCA is a statistical method adapted to table of type “individuals x quatitative variable”. Eingen Values correspond to means of squared correlation ratios. It could be used a pre-processing before a classification or a coinertia analysis on tables with quantitative.</p>
</section>
<section id="mathematics-2" class="level2">
<h2 class="anchored" data-anchor-id="mathematics-2">Mathematics</h2>
<p>The MCA stands out from other multivariate analyzes with a single table (PCA, CA or mix between MCA and PCA, etc.) because it <strong><em>only takes qualitative variables</em></strong> as input. Its goal is to find the relationships between modalities by visualizing the possible associations and producing a quantitative indicator of their relationships.</p>
<p>The data taken by an MCA is a table comprising <span class="math inline">\(J\)</span> qualitative variables to describe <span class="math inline">\(I\)</span> statistical individuals. All individuals have the same weight <span class="math inline">\(\frac{1}{I}\)</span>. The value <span class="math inline">\(V_{i,j}\)</span> in the table corresponds to the modality taken by individual <span class="math inline">\(i\)</span> for variable <span class="math inline">\(j\)</span>.</p>
<p>To obtain a <strong><em>complete disjunctive table (CDT)</em></strong> and carry out the statistical analysis, it is necessary to subdivide each variable <span class="math inline">\(j\)</span> into <span class="math inline">\(n_{j}\)</span> modalities corresponding to all of the responses <span class="math inline">\(V_{.,j}\)</span> of the <span class="math inline">\(I\)</span> individuals for this variable. The table will always have <span class="math inline">\(I\)</span> rows but <span class="math inline">\(\sum_{j=1}^J {n_j}\)</span> columns (we will denote K columns), in which each of the <span class="math inline">\(V_{i,k}\)</span> values is either 1 or 0 depending on the presence or absence of the modality.</p>
<p>The value <span class="math inline">\(V_{i,k}\)</span> is transformed again : the old value of <span class="math inline">\(V_{i,k}\)</span> (1 or 0) is divided by the probability <span class="math inline">\(p_{k}\)</span> of having this modality (i.e.&nbsp;<span class="math inline">\(p_k=\frac{\sum_{i=0}^I V_{i,k}}{I}\)</span>, result from which we subtract 1 to center the result.</p>
<p><span class="math display">\[V'_{i,k}=\frac{\sum_{i=1}^I V_{i,k}}{I}-1\]</span></p>
<p>We define the <strong><em>distance D</em></strong> between 2 individuals <span class="math inline">\(i\)</span> and <span class="math inline">\(i’\)</span> as : <span class="math display">\[D=\frac{1}{J}\sum_{k=1}^K \frac{1}{p_{k}}(V'_{i,k}-V'_{i',k})^2\]</span></p>
<p>So 2 individuals taking the all same modalities are at a distance D = 0, the more similar the responses are over a large number of modalities, the lower the distance D will be and conversely. If two individuals share a rare modality, the distance will be reduced to take into account the common specificity.</p>
<p>The inertia of the point cloud : <span class="math inline">\(N = \frac{K}{J} – 1\)</span>. <span class="math inline">\(η^2(x,y)\)</span> is the correlation ratio between 2 variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> and <span class="math inline">\(η^2(F_s,k)\)</span> is the <strong><em>correlation ratio</em></strong> between the modality <span class="math inline">\(k\)</span> and l’axe <span class="math inline">\(F_s\)</span>. The axis <span class="math inline">\(F_1\)</span> is the one which maximize its correlation ratio with all the modalities <span class="math inline">\(k\)</span> : <span class="math display">\[F_1=\max(\sum_{k=1}^K η^2(F_s,V_{.,k}))\]</span></p>
</section>
<section id="interpretation-2" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-2">Interpretation</h2>
<p>This part is a simple example of MCA using R. You can import R package using the code. Let’s have to look to fictive the data set we will be working on :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>hippo <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> <span class="st">"https://raw.githubusercontent.com/AnsaldiL/MODE_reproduciblescience/master/hp.csv"</span>, <span class="at">sep=</span><span class="st">';'</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>hippo<span class="ot">=</span>hippo[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(hippo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   143 obs. of  4 variables:
 $ Age      : int  20 21 23 24 23 35 26 22 22 20 ...
 $ Sex      : chr  "F" "M" "F" "F" ...
 $ Frequency: chr  "regularly" "rarely" "regularly" "regularly" ...
 $ Lake     : chr  "G1" "G3" "G1" "G3" ...</code></pre>
</div>
</div>
<p>Water consumption behaviour of Hippopotamus was observed in Penjari National Park, Benin. Drinking frequency was evaluated by a technician and rated “rarely” or “regularly”. Sex is indicated with F for female and M for male. As there are 3 lakes in the park which are noted “G1”, “G2” and “G3”.</p>
<p>We are performing MCA with the package FactoMineR.</p>
<p>Let’s have a look to Eigen Values :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>res.mca<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      eigenvalue percentage of variance cumulative percentage of variance
dim 1  0.4348479               32.61359                          32.61359
dim 2  0.3391468               25.43601                          58.04960
dim 3  0.3304681               24.78511                          82.83470
dim 4  0.2288706               17.16530                         100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(res.mca, <span class="at">addlabels =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The total variance of the data set is divided between four dimensions. The first dimension concentrate 32.6% of the total variance. The first plan gather 58% of the variance. You can better visualize the repartition of variance with the plot.</p>
<p>Here, you can see the results for the individuals, their coordinates (<span class="math inline">\(coord\)</span>), absolute contributions (<span class="math inline">\(contrib\)</span>), and the quality of their projection (<span class="math inline">\(cos2\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res.mca<span class="sc">$</span>ind<span class="sc">$</span>coord)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Dim 1      Dim 2        Dim 3      Dim 4
1 -0.2750115 -0.3282379  0.953675653  0.2177425
2  1.1910863 -0.2970654 -0.817927621  0.0463482
3 -0.2750115 -0.3282379  0.953675653  0.2177425
4 -0.5234147 -0.6299231 -0.447176405  0.1119000
5 -0.2750115 -0.3282379  0.953675653  0.2177425
6 -0.6770613  0.6031855  0.005825436 -0.2073689</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res.mca<span class="sc">$</span>ind<span class="sc">$</span>cos2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Dim 1      Dim 2        Dim 3        Dim 4
1 0.06632695 0.09448565 7.976083e-01 0.0415790594
2 0.65134489 0.04051620 3.071527e-01 0.0009862576
3 0.06632695 0.09448565 7.976083e-01 0.0415790594
4 0.31017449 0.44925117 2.263977e-01 0.0141766670
5 0.06632695 0.09448565 7.976083e-01 0.0415790594
6 0.52978429 0.42047948 3.921931e-05 0.0496970050</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res.mca<span class="sc">$</span>ind<span class="sc">$</span>contrib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Dim 1     Dim 2        Dim 3       Dim 4
1 0.1216265 0.2221539 1.924579e+00 0.144863948
2 2.2814613 0.1819619 1.415677e+00 0.006563565
3 0.1216265 0.2221539 1.924579e+00 0.144863948
4 0.4405736 0.8181846 4.231479e-01 0.038259024
5 0.1216265 0.2221539 1.924579e+00 0.144863948
6 0.7371954 0.7502017 7.181106e-05 0.131389632</code></pre>
</div>
</div>
<p>Coordonates of the individuals are their position on the first plan. <span class="math inline">\(cos2\)</span> represents the quality of the representation of the individuals on the first plan. Contribution is how the point contribute to the creation of different axis.</p>
<p>You can access the same information for the variable (instead of the individuals):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>res.mca<span class="sc">$</span>var<span class="sc">$</span>coord</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Dim 1       Dim 2       Dim 3      Dim 4
F         -0.47746388 -0.21701783  0.15112124 -0.3434173
M          1.14818694  0.52187620 -0.36341060  0.8258369
rarely     1.23505546 -0.11004338 -0.08731625 -0.8834510
regularly -0.53107385  0.04731865  0.03754599  0.3798839
G1         0.46448522 -0.40376182  1.45603286  0.2760402
G2        -0.33088584  1.22351803 -0.17862073 -0.3340851
G3        -0.02692834 -0.93083264 -0.95986346  0.1241336</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>res.mca<span class="sc">$</span>var<span class="sc">$</span>contrib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Dim 1      Dim 2       Dim 3      Dim 4
F         12.34263168  3.2693937  1.62699252 12.1316114
M         29.68109047  7.8621135  3.91252964 29.1736370
rarely    35.15982729  0.3578914  0.23124469 34.1811065
regularly 15.11872574  0.1538933  0.09943522 14.6978758
G1         4.62603750  4.4819347 59.81574581  3.1042541
G2         3.05186316 53.5031214  1.17025431  5.9111247
G3         0.01982416 30.3716520 33.14379781  0.8003904</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>res.mca<span class="sc">$</span>var<span class="sc">$</span>cos2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Dim 1       Dim 2       Dim 3       Dim 4
F         0.5482177869 0.113256440 0.054919059 0.283606714
M         0.5482177869 0.113256440 0.054919059 0.283606714
rarely    0.6559056566 0.005207104 0.003278375 0.335608865
regularly 0.6559056566 0.005207104 0.003278375 0.335608865
G1        0.0837850567 0.063310139 0.823313280 0.029591524
G2        0.0625631068 0.855426501 0.018231638 0.063778755
G3        0.0004019773 0.480314347 0.510741640 0.008542035</code></pre>
</div>
</div>
<p>Let’s have a look to the plot of this MCA analysis :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res.mca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As this is a factice data set, some individuals are overlapping. We will not focus on this artefact of the data set.</p>
<p><strong>How to interprete these graphs?</strong></p>
<p><strong><em>General description</em></strong> : The individuals are in black. The variables are in red. The percentage of variance of the first two axis is written on them. Individuals in the center of the cloud are individuals taking a mean value for all of their caracteristics, unlikely individuals far from the middle which are specific individuals, very different from others. Close individuals present close characteristics.</p>
<p><strong><em>Interpretation</em></strong>: Here, we can see that the first axis separates individuals drinking regularly from individuals drinking rarely. The second axis separates individuals drinking at G2 from individuals drinking at G3. Male and female seamed to be separated by the first axis. As we can gather individuals sharing close properties, females seams to drink regularly and male more rarely. It is a bit less clear but male are drinking preferably in pound 1.</p>
<p>Note that supplementary quantitaive data could be added to the analysis to help interpretation. As they are quantitatives, they would not participate to the creation of axis but they may be ploted on the final graph.</p>
</section>
</section>
<section id="part-4-cca" class="level1">
<h1>PART 4: CCA</h1>
<section id="introduction-3" class="level2">
<h2 class="anchored" data-anchor-id="introduction-3">Introduction</h2>
<p>Two table analysis is used when the scientist possesses two data set with expecting the second to explain the first. The first one is called Y, the response variable and the second one is called X, the explanatory variable. For example :</p>
<p>Table Y | Table X<br>
a data set with temperature data | a data set with cities caracteristics such as heigth of buildings, concreted area, number of cars… |<br>
a data set with the quantity of chemicals in soil | a data set with % of pesticide applied |<br>
a data set with functional traits of an animal | a data set with the quantities of different food given to the animal |</p>
<p>RDA is used when expecting a linear response from <span class="math inline">\(X\)</span> to <span class="math inline">\(Y\)</span>. Only the variables of <span class="math inline">\(X\)</span> explaining <span class="math inline">\(Y\)</span> would be kept. The canonical axis are a linear combinaison of the explicative variable (<span class="math inline">\(Y\)</span>). The <span class="math inline">\(Y\)</span> table will be ordered with a PCA. Then, a multiple regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> is done and stored in a new table, <span class="math inline">\(Y'\)</span>. The residual matrix correspond to <span class="math inline">\(Y-Y'\)</span>, what was not explained by <span class="math inline">\(X\)</span>.</p>
</section>
<section id="interpretation-3" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-3">Interpretation</h2>
<p>Here are the library you will need to perfor the RDA, make sure your import them at the begining of your working document.</p>
<p>Let’s import the data, they are from <span class="citation" data-cites="thilenius1963synecology">@thilenius1963synecology</span>. However, the data of abundance have been changed to facilitated the interpretation. For access to real data and metadata, please see the JDBakker Git page: <a href="https://github.com/jon-bakker/appliedmultivariatestatistics/blob/main/Oak_data_47x216.csv">appliedmultivariatestatistics/Oak_data_47x216.csv at main · jon-bakker/appliedmultivariatestatistics (github.com)</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>Oak <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/AnsaldiL/MODE_reproduciblescience/master/Oak_data.csv"</span>, <span class="at">sep=</span><span class="st">';'</span>, <span class="at">header =</span> <span class="cn">TRUE</span>) </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>Topo <span class="ot">&lt;-</span> Oak <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(LatAppx, LongAppx, Elev.m, Slope.deg) <span class="sc">%&gt;%</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">decostand</span>(<span class="st">"range"</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>Oak_sp<span class="ot">=</span>Oak[,<span class="dv">28</span><span class="sc">:</span><span class="dv">83</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can explore the tables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Oak_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Abgr.s Abgr.t Acar Acgld.t Acma.s Acma.t Acmi Adbi Agha Agre Agse Agte Aica
1      0      0    0       0      0      0    0    0    0    0    0    1    1
2      5      0    0       0      1      0    0    0    0    0    0    0    0
3      4      0    2       0      1      0    0    0    0    0    0    0    0
4      0      0    0       0      0      0    0    0    0    0    0    0    1
5      0      0    0       0      0      0    0    0    0    0    0    0    0
6      0      0    0       1      0      0    0    0    0    0    0    0    0
  ALL Alpr Amal.s Amal.t Apan Aqfo Arel Arme.s Arme.t Avfa Beaq.s Brco Brla
1   0    2      0      0    0    0    0      0      0    0      0    0    1
2   0    0      1      0    0    0    0      0      0    0      0    0    0
3   0    0      0      0    0    0    0      0      0    0      0    0    0
4   0    0      0      0    0    2    0      0      0    0      0    0    0
5   0    0      0      0    0    0    1      0      0    0      0    0    0
6   0    0      0      0    0    1    0      0      0    0      0    0    0
  Brpu Brri Brse Brst Brvu Caqu CAR Cato Cear Ceum Ceve.s Cipa Civu Coco.s
1    1    0    0    0    0    1   0    0    0    0      0    0    0      0
2    0    0    0    0    0    1   0    0    0    0      0    0    0      0
3    0    0    0    0    0    0   0    0    0    0      0    0    0      0
4    1    0    0    0    0    3   0    0    0    1      1    0    0      0
5    0    0    0    0    0    1   0    0    0    0      1    0    0      0
6    0    0    0    0    0    0   0    0    0    0      1    0    0      0
  Coco.t Cogr Conu.s Conu.t CORY.t Cost Crca Crdo.s Crdo.t Crox.s Cyec Cyfo
1      0    0      0      0      0    0    0      0      0      0    0    0
2      0    0      0      0      0    0    0      0      0      0    0    0
3      0    0      0      0      0    0    0      0      0      0    0    0
4      0    0      0      0      0    0    0      0      0      0    0    0
5      0    0      0      0      0    0    0      0      0      0    0    0
6      0    0      0      0      0    0    0      0      0      0    0    0
  Cygr Daca Dacar Dagl
1    0    0     0    0
2    0    0     0    0
3    0    0     0    0
4    0    0     0    0
5    0    0     0    0
6    0    0     0    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Topo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    LatAppx  LongAppx     Elev.m  Slope.deg
1 0.3882609 1.0000000 0.06578947 0.03448276
2 0.5073864 0.6239120 0.13157895 0.24137931
3 0.5750381 0.7687530 0.33333333 0.20689655
4 0.7392188 0.6721803 0.06578947 0.17241379
5 0.8261238 0.9377551 0.33333333 0.34482759
6 0.3309702 0.9046193 0.06578947 0.17241379</code></pre>
</div>
</div>
<p>So here, the first table (“Oak_sp”) represents a table of plant abundance for 47 sites (47 rows). We have 56 differents species. The second table (“Topo”) corresponds to 4 topographics variables (Latitute, Longitute of sites, the elevation and the slope). As it is not the same unit for each variable we have centred-reduced these four variables.</p>
<p>As explained above, the CCA objective is to link the abundance of plant by the topographics variables. Here, we have <em>a priori</em> hypothesis on the effect of these environmental variables on the plants.</p>
<p>We have seen in introduction of the part 3 that CCA was used when the respond have a non-linear distribution but rather a gaussian relationship.</p>
<p>So we begin by performing a CA on the species table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>caoak <span class="ot">&lt;-</span> <span class="fu">dudi.coa</span>(Oak_sp,<span class="at">scannf=</span>F,<span class="at">nf=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we can perform the PCA on the CA that corresponds to the CCA with the <strong>ADE4</strong> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ccaoak <span class="ot">&lt;-</span> <span class="fu">pcaiv</span>(caoak,Topo,<span class="at">scannf=</span>F,<span class="at">nf=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can also realize the CCA with one code row only with the <strong>vegan</strong> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ccavegan<span class="ot">=</span><span class="fu">cca</span>(Oak_sp,Topo,<span class="at">scan=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It is important to use the two methods because each allows us to have different information during the analyse of the result</p>
<p>An we already have completed our analyse, it was no difficult! But now, we need analyse the result and test the significant.</p>
<p>To test the significant, we use a bootstrapping test thank you the <strong>ADE4</strong> package.It is important to test if the result of the RLQ is not only due to random combination of values but that we have a real correlation between are different tables. To produce this, we perform a permutation test with the function <em>randtest</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">randtest</span>(ccaoak)<span class="co">#with ADE4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte-Carlo test
Call: randtest.pcaiv(xtest = ccaoak)

Observation: 0.1270957 

Based on 99 replicates
Simulated p-value: 0.01 
Alternative hypothesis: greater 

     Std.Obs  Expectation     Variance 
3.3273097300 0.0852729286 0.0001579932 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">randtest</span>(ccaoak))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The outputs above corresponds to the permutation test. We see that the number of permutation of columns and rows was to 999 (default value).</p>
<p>The results of this test shows that our result is significatively different to the permutation result with a threshold of 5% (p-value = 0.02)</p>
<p>Finally, the results of the CCA are plot in the distribution law calculated by the permutation. So we can conclude that our environmental variables explain a part of the plant distribution.</p>
<p>We have now to look the collinearity between the environmental variable. It corresponds to the correlation between them. For that, we use the Variance Inflation Factor (VIF).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>test<span class="ot">=</span><span class="fu">vif.cca</span>(ccavegan) </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  LatAppx  LongAppx    Elev.m Slope.deg 
 1.072988  1.115539  1.169013  1.111402 </code></pre>
</div>
</div>
<p>If all the variables have a number lower than 10, you can conclude that you do not not have collinearity. If you have, you need to select some variables to remove with, for example, an <em>ordistep</em> function.</p>
<p>Now that we have tested all the conditions, we can look at the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>ccaoak</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Canonical correspondence analysis
call: pcaiv(dudi = caoak, df = Topo, scannf = F, nf = 2)
class: caiv pcaiv dudi 

$rank (rank)     : 4
$nf (axis saved) : 2

eigen values: 0.3446 0.179 0.1231 0.05905

 vector length mode    content                
 $eig   4      numeric eigen values           
 $lw    47     numeric row weigths (from dudi)
 $cw    56     numeric col weigths (from dudi)

 data.frame nrow ncol content                             
 $Y         47   56   Dependant variables                 
 $X         47   4    Explanatory variables               
 $tab       47   56   modified array (projected variables)

 data.frame nrow ncol content                               
 $c1        56   2    PPA Pseudo Principal Axes             
 $as        2    2    Principal axis of dudi$tab on PAP     
 $ls        47   2    projection of lines of dudi$tab on PPA
 $li        47   2    $ls predicted by X                    

 data.frame nrow ncol content                                  
 $fa        5    2    Loadings (CPC as linear combinations of X
 $l1        47   2    CPC Constraint Principal Components      
 $co        56   2    inner product CPC - Y                    
 $cor       4    2    correlation CPC - X                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The pourcentage of variance explained by topographic variables is: "</span>,<span class="fu">sum</span>(ccaoak<span class="sc">$</span>eig)<span class="sc">/</span><span class="fu">sum</span>(caoak<span class="sc">$</span>eig),<span class="st">"%"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The pourcentage of variance explained by topographic variables is:  0.127095660396168 %"</code></pre>
</div>
</div>
<p>The first output (by <strong>ADE4</strong>) allows us to see each part of the analyse that could be use to describe the result. We will use especially the last part afterward. You also have, at the beginning, the number of rank that corresponds to the number of eigenvalue with their score below. We can calculate the percentage of variance explained by topographic variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ccavegan</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: cca(X = Oak_sp, Y = Topo, scan = F)

              Inertia Proportion Rank
Total          5.5529     1.0000     
Constrained    0.7057     0.1271    4
Unconstrained  4.8471     0.8729   38
Inertia is scaled Chi-square 
17 species (variables) deleted due to missingness

Eigenvalues for constrained axes:
  CCA1   CCA2   CCA3   CCA4 
0.3446 0.1790 0.1231 0.0590 

Eigenvalues for unconstrained axes:
   CA1    CA2    CA3    CA4    CA5    CA6    CA7    CA8 
0.7256 0.5739 0.4521 0.4240 0.3563 0.2448 0.2239 0.1857 
(Showing 8 of 38 unconstrained eigenvalues)</code></pre>
</div>
</div>
<p>Here, it is the output with the <strong>vegan</strong> package. We can see the total inertia in the CCA analyse (5.55) and the inertia explained by the topographic variables (0.71) and by the residuals (4.85). We can therefore conclude that our topographic variables explain only 13% of the plant variances (same result that before). Below that, we have the eigenvalues for the constrained axes (variance part explained by topographic variables) and for the unconstrained axes (variance part explained by the residuals)</p>
<p>We can now, observe the complet plot of the CCA result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ccaoak)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we can have a complete plot with the <strong>ADE4</strong> package.</p>
<ul>
<li><p>The “Loadings” part represents the canonical coefficients. For each axis, the arrows explain the relative weight of the topographic variables in the multiple regression calculation.</p></li>
<li><p>The “Correlation” part shows the correlation between topographic variables themselves and with CCA axes</p></li>
<li><p>The “Scores and Predictions” part allows us to understand, for each site, the real plant abundance (base of arrows) and the abundance predicted by multiple regressions with the topographic variables.</p></li>
<li><p>The “Species” part corresponds to the coordinates of each plant species in the CCA analyse</p></li>
</ul>
<p>But this can also be decomposed in different plots and output.We can detail each part and observe the biological results.</p>
<p>We can begin by the absolute contribution of species:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>contrib<span class="ot">=</span><span class="fu">inertia.dudi</span>(ccaoak, <span class="at">col =</span> <span class="cn">TRUE</span>, <span class="at">row =</span> <span class="cn">FALSE</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>contrib<span class="sc">$</span>col.abs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Axis1        Axis2
Abgr.s  6.021847e+00  1.212813788
Abgr.t  3.177359e+01 10.422451480
Acar    2.635049e+00  0.134855688
Acgld.t 7.493068e+00  1.910539707
Acma.s  2.515315e-02  1.689674506
Acma.t  8.936196e-01  1.898419377
Acmi    3.919403e-02  0.004891136
Adbi    9.970574e+00  5.143409094
Agha    8.209713e-01 17.598302739
Agre    8.571153e-01  1.890912149
Agse    1.299772e-01  8.924213094
Agte    4.233778e+00  1.403202784
Aica    3.007289e+00  0.000614369
ALL     1.076835e-01  6.374919825
Alpr    1.413603e-01  0.237212759
Amal.s  5.831519e-02  0.289243172
Amal.t  2.843090e-02  2.844815278
Apan    6.791621e+00  1.385883395
Aqfo    6.407529e+00 11.512960665
Arel    3.725579e+00  2.142662004
Arme.s  0.000000e+00  0.000000000
Arme.t  1.002592e-05  2.416236998
Avfa    1.389095e-01  1.919937151
Beaq.s  1.385684e+00  4.664898207
Brco    0.000000e+00  0.000000000
Brla    1.570857e+00  0.757779956
Brpu    4.750564e-01  0.266026605
Brri    8.163005e-01  1.287295464
Brse    1.292897e-01  0.143416542
Brst    0.000000e+00  0.000000000
Brvu    4.429482e+00  0.016067778
Caqu    1.841713e-02  1.290440906
CAR     6.964536e-01  0.036573989
Cato    1.206790e+00  0.522162462
Cear    9.936004e-01  0.303130230
Ceum    8.493802e-01  0.392276059
Ceve.s  1.019629e+00  2.122835911
Cipa    1.182233e-04  1.942686629
Civu    0.000000e+00  0.000000000
Coco.s  0.000000e+00  0.000000000
Coco.t  9.551865e-01  0.003571735
Cogr    5.754591e-02  1.919957503
Conu.s  0.000000e+00  0.000000000
Conu.t  0.000000e+00  0.000000000
CORY.t  0.000000e+00  0.000000000
Cost    0.000000e+00  0.000000000
Crca    0.000000e+00  0.000000000
Crdo.s  0.000000e+00  0.000000000
Crdo.t  5.203645e-02  0.143607303
Crox.s  0.000000e+00  0.000000000
Cyec    0.000000e+00  0.000000000
Cyfo    0.000000e+00  0.000000000
Cygr    4.350974e-02  2.829101566
Daca    0.000000e+00  0.000000000
Dacar   0.000000e+00  0.000000000
Dagl    0.000000e+00  0.000000000</code></pre>
</div>
</div>
<p>The output, here, is the absolute contribution of each species for the axis 1 and the axis 2. This allows us to observe what species contributes the most of the axes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>ccaoak<span class="sc">$</span>fa</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      RS1           RS2
(Intercept) -1.448845e-16  1.304775e-16
LatAppx      5.546487e-01 -1.321836e-01
LongAppx     8.933635e-02  1.113464e-01
Elev.m      -2.378758e-02 -2.828042e-01
Slope.deg    2.306181e-02  3.754766e-01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.corcircle</span>(ccaoak<span class="sc">$</span>fa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This line gives you the canonical coefficients on each axis. The circle is explain in the “Loadings” part of the main plot of the RDA. On axis 1, the variable with the main contribution of the predictive power is <span class="math inline">\(LatAppx\)</span>. On axis 2, <span class="math inline">\(Slope.deg\)</span> and <span class="math inline">\(Elev.m\)</span> contributes the most of the predictive power.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>ccaoak<span class="sc">$</span>co</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Comp1        Comp2
Abgr.s  -0.344559610 -0.111446061
Abgr.t  -1.499805193  0.619091450
Acar    -0.405170072 -0.066061105
Acgld.t -0.657447384 -0.239263999
Acma.s   0.098964466 -0.584591822
Acma.t  -0.527599532  0.554232875
Acmi     0.093384329 -0.023775904
Adbi    -1.970348894 -1.019944979
Agha    -0.376925736  1.257752946
Agre    -0.408495885 -0.437292359
Agse     0.318149791  1.899989382
Agte     0.560360412  0.232504722
Aica     0.510110670  0.005254841
ALL      0.204765928  1.135503753
Alpr     0.135452232  0.126461872
Amal.s  -0.213102669  0.342056435
Amal.t  -0.210430331 -1.517079157
Apan     0.566164741  0.184326417
Aqfo     0.455971525 -0.440508302
Arel     0.525654360  0.287308446
Arme.s   0.000000000  0.000000000
Arme.t   0.002281469 -0.807217082
Avfa     0.328900132  0.881271477
Beaq.s   0.555259619  0.734265751
Brco     0.000000000  0.000000000
Brla     0.451534247  0.226027947
Brpu     0.384680895  0.207471640
Brri     0.797302436  0.721614627
Brse     0.259080296 -0.196661887
Brst     0.000000000  0.000000000
Brvu     0.656643322  0.028503562
Caqu    -0.043729888 -0.263818130
CAR     -0.520749860  0.086007708
Cato     0.969424379  0.459588372
Cear     0.470186239 -0.187174556
Ceum     0.575087756 -0.281674227
Ceve.s  -0.476305048 -0.495325172
Cipa    -0.009595104 -0.886477227
Civu     0.000000000  0.000000000
Coco.s   0.000000000  0.000000000
Coco.t   0.862466323 -0.038010697
Cogr     0.172846131 -0.719558962
Conu.s   0.000000000  0.000000000
Conu.t   0.000000000  0.000000000
CORY.t   0.000000000  0.000000000
Cost     0.000000000  0.000000000
Crca     0.000000000  0.000000000
Crdo.s   0.000000000  0.000000000
Crdo.t   0.201303763 -0.241020771
Crox.s   0.000000000  0.000000000
Cyec     0.000000000  0.000000000
Cyfo     0.000000000  0.000000000
Cygr     0.184073508 -1.069770155
Daca     0.000000000  0.000000000
Dacar    0.000000000  0.000000000
Dagl     0.000000000  0.000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.label</span>(ccaoak<span class="sc">$</span>co,<span class="at">boxes=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(co\)</span> gives you access to the coordinates of each species on the first plan. The table explicits the coordinates and the plot help you to find close species. On the first axis, two species have high negative value : Adbi (-1.97) &amp; Abgr.t (-1.50). They are opposed at species as Coco.t (0.86) &amp; Cato (0.96). You can realize the same for the second axis.</p>
<p>Here, we can highlight that there is a group formed by Agse (coord = 0.31 ; 1.90 respectively for the axis 1 and 2), Agha (coord = -0.38 ; 1.25) Avfa (coord = 0.33 ; 0.88) and ALL (coord = 0.20 ; 1.14). An other on with two outliers, Abgr.t and Adbi. These groups will be correlated with the environment data further in the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>ccaoak<span class="sc">$</span>cor </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 RS1         RS2
LatAppx    0.9867311 -0.09977934
LongAppx   0.3726389  0.33053940
Elev.m    -0.1505108 -0.45170572
Slope.deg  0.1235033  0.65338800</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.corcircle</span>(ccaoak<span class="sc">$</span>cor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we have the correlation between axes and the topographic variables. We can conclude that the elevation (corr = -0.15[axis1] ; -0.45[axis2]) and the slope (corr = 0.12[axis1] ; 0.65[axis2]) are strongly negatively correlated. The Longitude seems to be positively correlated with the slope and negatively correlated with the elevation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.match</span>(ccaoak<span class="sc">$</span>ls, ccaoak<span class="sc">$</span>li)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ccavegan,<span class="at">scaling=</span><span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ccavegan,<span class="at">scaling=</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-38-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The first plot with the arrows represents the real abundances for each site (base of the arrow) and the predictions of abundance calculated by a multiple regression thanks to the topographic variables. We see here that there are some large differences between reality and prediction. Most of the sites are in a center group but some sites differ. It is the case with the sites n°7,40,41,42. We have another group with the sites n°43,44,45,46.</p>
<p>The second plot, with <em>scaling = 1</em> preserves euclidian distances between stations.<br>
The third plot, with <em>scaling = 2</em> preserves correlations between species.</p>
<p>To conclude on the CCA analyse, we have seen that the topographic variables explain 13% of the plant variances. The first axis represents 34% of the constrained inertia and is explained by the Latitude (corr = 0.99). We can see that two species have a high coordinate in this axis (Adbi &amp; Abgr.t).<br>
The second axis (18% of the constrained inertia) is explained by the Elevation (corr = -0.45), the Slope (corr = 0.65) and the Longitude (corr = 0.33).</p>
<p>Finally, the sites n°43,44,45,46 are sites with a small latitude value and with a high abundance of species as Abgr.t.</p>
</section>
</section>
<section id="part-5-rlq" class="level1">
<h1>PART 5: RLQ</h1>
<section id="introduction-4" class="level2">
<h2 class="anchored" data-anchor-id="introduction-4">Introduction</h2>
<p>The RLQ analysis is a generalized co-inertia with 3 tables : environmental variables for each sites (R), species abundances for each sites (L) and trait variables for each species (Q). We will have to perform a CA on the table L and weighted analysis (MCA or PCA) on tablesR and Q. Then a function named <em>rlq()</em> perform 3 co-inertia analysis between R and L and L and Q and then between the results of each co-inertia.</p>
</section>
<section id="interpretation-4" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-4">Interpretation</h2>
<p>The use of RLQ analysis is important in ecology to integrate the traits of species with the environmental variables. So here, we don’t have 2 tables (environment &amp; specie) as RDA part but 3 tables:</p>
<ul>
<li><p>environmental variables by sites (R)</p></li>
<li><p>abundance of species by sites (L)</p></li>
<li><p>trait values by species (Q)</p></li>
</ul>
<p>To perform the RLQ, we need to decompose the analyse by three type of analyses already done in this chapter:</p>
<ul>
<li><p>we will use a CA analyse on the abundance of species</p></li>
<li><p>we will use a MCA on the environmental table by taking the sites weight on the CA</p></li>
<li><p>we will use a MCA on the trait table by taking the species weight on the CA</p></li>
</ul>
<p>Here, we use MCA for R and Q because our variables are factors but you can perform a PCA if your variables are quantitatives. Warning, for R and Q you have the obligation to weight by the L table (see below).</p>
<p>You can import R package using the code</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ade4)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RVAideMemoire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>*** Package RVAideMemoire v 0.9-83-7 ***</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PerformanceAnalytics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: xts</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
######################### Warning from 'xts' package ##########################
#                                                                             #
# The dplyr lag() function breaks how base R's lag() function is supposed to  #
# work, which breaks lag(my_xts). Calls to lag(my_xts) that you type or       #
# source() into this session won't work correctly.                            #
#                                                                             #
# Use stats::lag() to make sure you're not using dplyr::lag(), or you can add #
# conflictRules('dplyr', exclude = 'lag') to your .Rprofile to stop           #
# dplyr from breaking base R's lag() function.                                #
#                                                                             #
# Code in packages is not affected. It's protected by R's namespace mechanism #
# Set `options(xts.warn_dplyr_breaks_lag = FALSE)` to suppress this warning.  #
#                                                                             #
###############################################################################</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'xts'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'PerformanceAnalytics'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    legend</code></pre>
</div>
</div>
<p>Here, we work with a dataset of <strong>ADE4</strong> package. The data comes from <span class="citation" data-cites="dray2008testing">@dray2008testing</span>, <span class="citation" data-cites="legendre1997relating">@legendre1997relating</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import the dataset</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(aviurba)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create the three tables</span></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aviurba<span class="sc">$</span>mil)    <span class="co">#(R)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> farms    small.bui high.bui industry fields   grassland scrubby  deciduous
 yes:22   yes:13    yes: 8   yes:12   yes:22   yes:12    yes:30   yes:36   
 no :29   no :38    no :43   no :39   no :29   no :39    no :21   no :15   
                                                                           
                                                                           
                                                                           
                                                                           
                                                                           
 conifer  noisy      veg.cover
 yes: 8   yes:10   R37    :9  
 no :43   no :41   R5     :8  
                   R98    :7  
                   R93    :7  
                   R22    :6  
                   R87    :5  
                   (Other):9  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>R<span class="ot">&lt;-</span>aviurba<span class="sc">$</span>mil</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aviurba<span class="sc">$</span>fau)    <span class="co">#(L)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Sp1               Sp2              Sp3               Sp4        
 Min.   :0.00000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :0.00000   Median :0.0000   Median :0.00000   Median :0.0000  
 Mean   :0.05882   Mean   :0.1373   Mean   :0.07843   Mean   :0.7647  
 3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:1.0000  
 Max.   :1.00000   Max.   :2.0000   Max.   :1.00000   Max.   :4.0000  
      Sp5              Sp6              Sp7              Sp8       
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000  
 Median :0.0000   Median :0.0000   Median :0.0000   Median :3.000  
 Mean   :0.1176   Mean   :0.2353   Mean   :0.1569   Mean   :2.078  
 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:3.000  
 Max.   :2.0000   Max.   :1.0000   Max.   :1.0000   Max.   :4.000  
      Sp9              Sp10             Sp11             Sp12        
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :0.0000   Median :0.0000   Median :0.0000   Median :0.00000  
 Mean   :0.5882   Mean   :0.6275   Mean   :0.3922   Mean   :0.03922  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :3.0000   Max.   :4.0000   Max.   :4.0000   Max.   :1.00000  
      Sp13              Sp14              Sp15             Sp16       
 Min.   :0.00000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.00000   Median :0.00000   Median :0.0000   Median :0.0000  
 Mean   :0.05882   Mean   :0.03922   Mean   :0.1961   Mean   :0.3725  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:1.0000  
 Max.   :1.00000   Max.   :1.00000   Max.   :2.0000   Max.   :1.0000  
      Sp17              Sp18             Sp19             Sp20       
 Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.00000   Median :0.0000   Median :1.0000   Median :0.0000  
 Mean   :0.07843   Mean   :0.4118   Mean   :0.7059   Mean   :0.2157  
 3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000  
 Max.   :1.00000   Max.   :2.0000   Max.   :2.0000   Max.   :2.0000  
      Sp21              Sp22             Sp23              Sp24        
 Min.   :0.00000   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000  
 Median :0.00000   Median :0.0000   Median :0.00000   Median :0.00000  
 Mean   :0.03922   Mean   :0.3725   Mean   :0.07843   Mean   :0.09804  
 3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :2.0000   Max.   :1.00000   Max.   :1.00000  
      Sp25              Sp26             Sp27             Sp28        
 Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :0.00000   Median :0.0000   Median :0.0000   Median :0.00000  
 Mean   :0.03922   Mean   :0.1961   Mean   :0.2353   Mean   :0.03922  
 3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :1.0000   Max.   :2.0000   Max.   :1.00000  
      Sp29           Sp30             Sp31             Sp32       
 Min.   :0.00   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:2.00   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :3.00   Median :0.0000   Median :0.0000   Median :1.0000  
 Mean   :2.49   Mean   :0.6667   Mean   :0.2353   Mean   :0.8627  
 3rd Qu.:3.00   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:1.0000  
 Max.   :4.00   Max.   :4.0000   Max.   :2.0000   Max.   :3.0000  
      Sp33             Sp34              Sp35             Sp36      
 Min.   :0.0000   Min.   :0.00000   Min.   :0.0000   Min.   :0.000  
 1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.000  
 Median :0.0000   Median :0.00000   Median :1.0000   Median :0.000  
 Mean   :0.2941   Mean   :0.07843   Mean   :0.5686   Mean   :0.451  
 3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:1.000  
 Max.   :1.0000   Max.   :2.00000   Max.   :3.0000   Max.   :3.000  
      Sp37              Sp38             Sp39              Sp40       
 Min.   :0.00000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :0.00000   Median :0.0000   Median :0.00000   Median :0.0000  
 Mean   :0.05882   Mean   :0.1765   Mean   :0.03922   Mean   :0.4118  
 3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:1.0000  
 Max.   :1.00000   Max.   :2.0000   Max.   :1.00000   Max.   :3.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>L<span class="ot">&lt;-</span>aviurba<span class="sc">$</span>fau</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aviurba<span class="sc">$</span>traits) <span class="co">#(Q)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   feed.hab    feed.strat     breeding     migratory 
 insect:19   ground :27   ground  : 6   resident:23  
 grani :12   aerial : 3   building:14   migrant :17  
 omni  : 9   foliage:10   scrub   :12                
                          foliage : 8                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>Q<span class="ot">&lt;-</span>aviurba<span class="sc">$</span>traits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and explore the tables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(R)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   farms small.bui high.bui industry fields grassland scrubby deciduous conifer
R1   yes        no       no       no    yes        no      no       yes      no
R2   yes        no       no       no     no       yes     yes        no      no
R3    no        no       no       no    yes        no     yes       yes      no
R4    no        no       no       no    yes        no     yes        no      no
R5    no        no       no      yes     no        no     yes        no      no
R6    no        no       no      yes     no       yes     yes        no      no
   noisy veg.cover
R1    no       R98
R2    no       R87
R3    no      R100
R4    no      R100
R5    no        R5
R6   yes        R5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Sp1 Sp2 Sp3 Sp4 Sp5 Sp6 Sp7 Sp8 Sp9 Sp10 Sp11 Sp12 Sp13 Sp14 Sp15 Sp16 Sp17
R1   0   0   0   0   0   0   1   0   0    0    0    0    0    0    0    1    0
R2   0   0   0   0   0   0   1   0   0    0    0    0    1    0    0    0    0
R3   0   2   0   0   0   0   1   0   1    0    0    0    0    1    0    0    0
R4   0   0   0   0   0   0   1   0   1    0    0    0    0    0    1    0    0
R5   0   0   0   0   0   0   0   0   2    0    0    0    0    0    1    1    0
R6   0   0   0   0   0   0   0   0   0    0    0    0    0    0    0    1    0
   Sp18 Sp19 Sp20 Sp21 Sp22 Sp23 Sp24 Sp25 Sp26 Sp27 Sp28 Sp29 Sp30 Sp31 Sp32
R1    1    1    0    0    1    0    0    0    1    0    0    4    0    0    1
R2    2    1    0    0    1    0    1    0    1    0    0    4    4    1    1
R3    2    0    0    0    1    0    0    0    1    1    0    1    0    1    0
R4    2    0    0    0    1    0    1    0    0    2    0    1    0    1    1
R5    1    0    0    0    1    0    0    0    1    1    0    1    1    1    0
R6    0    0    0    0    0    0    0    0    0    0    0    4    1    0    1
   Sp33 Sp34 Sp35 Sp36 Sp37 Sp38 Sp39 Sp40
R1    1    0    1    0    0    0    0    1
R2    1    0    0    0    0    0    0    0
R3    1    0    0    0    0    0    0    1
R4    1    0    0    0    0    1    0    0
R5    0    0    0    0    0    0    0    0
R6    1    2    1    2    0    0    0    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    feed.hab feed.strat breeding migratory
Sp1     omni     ground  foliage   migrant
Sp2     omni     ground building   migrant
Sp3     omni     ground   ground   migrant
Sp4    grani     ground building  resident
Sp5    grani     ground    scrub  resident
Sp6    grani     ground  foliage  resident</code></pre>
</div>
</div>
<p>The first part is to perform our CA on specie table</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>afcL <span class="ot">&lt;-</span> <span class="fu">dudi.coa</span>(<span class="fu">log</span>(L<span class="sc">+</span><span class="dv">1</span>), <span class="at">scannf =</span> <span class="cn">FALSE</span>) </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>afcL  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Duality diagramm
class: coa dudi
$call: dudi.coa(df = log(L + 1), scannf = FALSE)

$nf: 2 axis-components saved
$rank: 39
eigen values: 0.3987 0.2736 0.1917 0.1624 0.1421 ...
  vector length mode    content       
1 $cw    40     numeric column weights
2 $lw    51     numeric row weights   
3 $eig   39     numeric eigen values  

  data.frame nrow ncol content             
1 $tab       51   40   modified array      
2 $li        51   2    row coordinates     
3 $l1        51   2    row normed scores   
4 $co        40   2    column coordinates  
5 $c1        40   2    column normed scores
other elements: N </code></pre>
</div>
</div>
<p>The first CA is done. We use log transformation because the abundance of species has a large range and we add “+1” to avoid the log(0) for some species. You must adapt the presence of transformation (or not) to your data.</p>
<p>Now, we can perform the two MCA analysis on the trait table and environmental table</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>acmR <span class="ot">&lt;-</span> <span class="fu">dudi.acm</span>(R, <span class="at">row.w =</span> afcL<span class="sc">$</span>lw, <span class="at">scannf =</span> <span class="cn">FALSE</span>,<span class="at">nf =</span> <span class="dv">4</span>)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter</span>(acmR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>acmQ <span class="ot">&lt;-</span> <span class="fu">dudi.acm</span>(Q, <span class="at">row.w =</span> afcL<span class="sc">$</span>cw, <span class="at">scannf =</span> <span class="cn">FALSE</span>,<span class="at">nf =</span> <span class="dv">4</span>)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter</span>(acmQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-43-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The scatterplot allows to see the ordination of each table and the repartition of factor on the simple axe of MCA.</p>
<p>But now, we will use the RLQ analyse that creates two co-inertia (R-L, L-Q), assembles and compares the co-inertia. We use the rlq function for that.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>rlq <span class="ot">&lt;-</span> <span class="fu">rlq</span>(acmR, afcL, acmQ, <span class="at">scannf =</span> <span class="cn">FALSE</span>)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>rlq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>RLQ analysis
call: rlq(dudiR = acmR, dudiL = afcL, dudiQ = acmQ, scannf = FALSE)
class: rlq dudi 

$rank (rank)     : 8
$nf (axis saved) : 2

eigen values: 0.01068 0.003128 0.001525 0.0004536 0.0001298 ...

  vector length mode    content                    
1 $eig   8      numeric Eigenvalues                
2 $lw    28     numeric Row weigths (for acmR cols)
3 $cw    12     numeric Col weigths (for acmQ cols)

   data.frame nrow ncol content                                      
1  $tab       28   12   Crossed Table (CT): cols(acmR) x cols(acmQ)  
2  $li        28   2    CT row scores (cols of acmR)                 
3  $l1        28   2    Principal components (loadings for acmR cols)
4  $co        12   2    CT col scores (cols of acmQ)                 
5  $c1        12   2    Principal axes (loadings for acmQ cols)      
6  $lR        51   2    Row scores (rows of acmR)                    
7  $mR        51   2    Normed row scores (rows of acmR)             
8  $lQ        40   2    Row scores (rows of acmQ)                    
9  $mQ        40   2    Normed row scores (rows of acmQ)             
10 $aR        4    2    Corr acmR axes / rlq axes                    
11 $aQ        4    2    Corr afcL axes / coinertia axes              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>axe<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The contribution of axe n°"</span>,axe, <span class="st">"are"</span>, rlq<span class="sc">$</span>eig<span class="sc">/</span>(<span class="fu">sum</span>(rlq<span class="sc">$</span>eig))<span class="sc">*</span><span class="dv">100</span>,<span class="st">"%"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The contribution of axe n° 1 are 66.6748744763001 %"  
[2] "The contribution of axe n° 2 are 19.5228230896623 %"  
[3] "The contribution of axe n° 3 are 9.51702542395437 %"  
[4] "The contribution of axe n° 4 are 2.83090411660832 %"  
[5] "The contribution of axe n° 5 are 0.810200444830495 %" 
[6] "The contribution of axe n° 6 are 0.421072849575587 %" 
[7] "The contribution of axe n° 7 are 0.124897113199049 %" 
[8] "The contribution of axe n° 8 are 0.0982024858697611 %"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co">#randtest(rlq)</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(rlq)</span></span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(rlq)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, the output of the RLQ is complex but only few information are, at this point important. We see that we have 8 eigenvalues and we have their values. All the different compounds of the output will be used after in representations or analysis.</p>
<p>Nevertheless, we can calculate the contribution of each axis of the RLQ by performing the formule below: <span class="math display">\[\frac{rlq$eig}{\sum{rlq$eig}}.100\]</span></p>
<p>After that, and before to plot and analyse the result, it is important to test if the result of the RLQ is not only due to random combination of values but that we have a real correlation between are different tables. To produce this, we perform a permutation test with the function <em>randtest</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">randtest</span>(rlq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: krandtest lightkrandtest 
Monte-Carlo tests
Call: randtest.rlq(xtest = rlq)

Number of tests:   2 

Adjustment method for multiple comparisons:   none 
Permutation number:   999 
     Test        Obs  Std.Obs   Alter Pvalue
1 Model 2 0.01602442 9.151203 greater  0.001
2 Model 4 0.01602442 2.293103 greater  0.032</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">randtest</span>(rlq))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The outputs above corresponds to the permutation test. We see that the number of permutation of columns and rows was to 999 (default value).</p>
<p>The results of this test shows that the permutation of sites (rows) is the first result (p_value=0.1%) and the permutation of species (columns) is the second result (p_value=1.9%) So each result is significant (5% threshold) and we can conclude that our RLQ result is not linked to random effect.</p>
<p>Finally, the results of the RLQ are plot in the distribution law calculated by the permutation.</p>
<p>We can know analyse the result by using different types of plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rlq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot above is the complet plot, difficult to understand and that will be resumed step by step afterward.</p>
<p>However, we have here, up the score (the position) of the sites and species in this analyse. Below in the centre, we have the correlation of the environmental variables between them (R Canonical weights) and the correlation of the traits between them (Q Canonical weight). The plots of the R axes and the Q axes represent the reprojection of axis in the RLQ analyse in order to the simple analyses (CA or MCA here).</p>
<p>Now, we can decompose the result and start with the environmental variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analyse the environmental variables:</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rlq<span class="sc">$</span>l1,<span class="at">dig=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 RS1   RS2
farms.yes      -0.11  0.73
farms.no        0.10 -0.65
small.bui.yes  -2.27 -0.53
small.bui.no    0.71  0.16
high.bui.yes   -2.17 -0.48
high.bui.no     0.35  0.08
industry.yes    0.43  2.63
industry.no    -0.11 -0.67
fields.yes      1.34  0.52
fields.no      -1.34 -0.52
grassland.yes  -1.07  0.26
grassland.no    0.30 -0.07
scrubby.yes    -0.10 -0.91
scrubby.no      0.14  1.37
deciduous.yes  -0.56 -0.64
deciduous.no    1.36  1.55
conifer.yes    -0.87  0.91
conifer.no      0.17 -0.18
noisy.yes      -2.61  0.67
noisy.no        0.43 -0.11
veg.cover.R100  4.35 -4.95
veg.cover.R98   1.74 -1.64
veg.cover.R93   0.13  3.16
veg.cover.R87  -0.94 -0.98
veg.cover.R62  -1.86 -0.35
veg.cover.R37  -2.01 -0.10
veg.cover.R22  -2.91  0.05
veg.cover.R5    1.04  3.24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.label</span>(rlq<span class="sc">$</span>l1, <span class="at">boxes=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calcul of the absolute contribution</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>iner<span class="ot">=</span><span class="fu">inertia.dudi</span>(rlq,<span class="at">col.inertia=</span>T,<span class="at">row.inertia=</span>T)</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>abscoiE<span class="ot">=</span>iner<span class="sc">$</span>row.abs</span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a>abscoiE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Axis1        Axis2
farms.yes       0.05223514  2.304444147
farms.no        0.04623764  2.039853800
small.bui.yes  11.21784230  0.599492102
small.bui.no    3.52200412  0.188219231
high.bui.yes    5.99404001  0.297237022
high.bui.no     0.97600864  0.048399060
industry.yes    0.33291147 12.714009779
industry.no     0.08422136  3.216444135
fields.yes      8.17323519  1.238389579
fields.no       8.20233957  1.242799407
grassland.yes   2.29313411  0.132425116
grassland.no    0.64653934  0.037336694
scrubby.yes     0.04972304  4.526463864
scrubby.no      0.07475839  6.805519570
deciduous.yes   2.01878003  2.632197876
deciduous.no    4.90713304  6.398193444
conifer.yes     1.13513324  1.240985532
conifer.no      0.22330026  0.244123224
noisy.yes       8.82492060  0.589761352
noisy.no        1.47048833  0.098271387
veg.cover.R100 16.95851693 21.972519979
veg.cover.R98   4.57563062  4.054631466
veg.cover.R93   0.02364930 14.452989048
veg.cover.R87   0.82853117  0.891676376
veg.cover.R62   3.46745570  0.119501611
veg.cover.R37   5.23067194  0.012183942
veg.cover.R22   7.43352189  0.002336584
veg.cover.R5    1.23703663 11.899594674</code></pre>
</div>
</div>
<p>The table corresponds to the position of each modality for each environmental variables on the two first axis. You can link this table to the plot. For example, “veg.cover.R100” seems to stand out from the other modalities. In the table, we can see that the position on the first axis is 4.35 and -4.95 on the second axis. Closer to the center of the cloud, we can talk about “veg.cover.R98” that have position of 1.74 on the first axis and -1.64 on the second axis. In addition, we can observe the contribution of this two variables. On the second table we have the absolute contribution of the modalities for each variable. The contribution of the “veg.cover.R100” of the first axis is 17% and 22% on the second axis. This is a high value if we take the threshold to 1/N with N the number of modalities (28 here so 3%). The contribution of “veg.cover.R98” is 4.6% for the first axis and 4.1% for the second axis.</p>
<p>We can therefore conclude that this two variables are correlated. This seems to be biologically coherent since these two variables are part of a plant cover gradient and are the two highest values.</p>
<p>We can also see that the variable negatively correlated with the first axis are modalities explaining the urbanization ()</p>
<p>Now we can realise the same analyse for the traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analyse the traits:</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rlq<span class="sc">$</span>c1,<span class="at">dig=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     CS1   CS2
feed.hab.insect     0.72  0.73
feed.hab.grani     -0.69 -0.24
feed.hab.omni      -0.13 -1.64
feed.strat.ground  -0.11  0.01
feed.strat.aerial  -1.26  1.24
feed.strat.foliage  2.60 -1.97
breeding.ground     3.60  4.16
breeding.building  -1.16  0.35
breeding.scrub      1.71 -2.22
breeding.foliage   -0.15 -0.62
migratory.resident -0.24 -0.23
migratory.migrant   0.54  0.50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.arrow</span>(rlq<span class="sc">$</span>c1, <span class="at">boxes=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co">#absolute contribution</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>abscoiV<span class="ot">=</span>iner<span class="sc">$</span>col.abs</span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>abscoiV</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Axis1        Axis2
feed.hab.insect     5.69187893  5.861738276
feed.hab.grani      5.10226145  0.632420595
feed.hab.omni       0.05897841  8.814467814
feed.strat.ground   0.22470905  0.003581384
feed.strat.aerial   7.09044249  6.818080636
feed.strat.foliage 19.80381068 11.362659415
breeding.ground    28.19988784 37.628640395
breeding.building  17.18536604  1.552603443
breeding.scrub     13.29440922 22.370738798
breeding.foliage    0.11612276  2.116775390
migratory.resident  1.00414733  0.881790779
migratory.migrant   2.22798580  1.956503077</code></pre>
</div>
</div>
<p>As seen before, the first table is the position of the modalities for the two first axes of the RLQ analyses. The plot is the representation of that and the second table is the absolute contributions.</p>
<p>Here, we have larger differences between the different variable and modalities. We’re going to focus on a few examples, but you can take the time to go into detail about each modality. “feed.strat.foliage” (coord= 2.60; -1.97 for first and second axis respectively) and “breeding.scrub” (coord= 1.71: -2.22) break away from the centre of the cloud. In addition their contributions are all greater than 10%. We can conclude that these modalities are correlated and highly contribute of axes.</p>
<p>The last point is to observe the species coordinates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analyse the species:</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rlq<span class="sc">$</span>lQ,<span class="at">dig=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     AxcQ1 AxcQ2
Sp1   0.04 -0.44
Sp2  -0.22 -0.19
Sp3   0.97  0.76
Sp4  -0.55 -0.03
Sp5   0.17 -0.67
Sp6  -0.30 -0.27
Sp7   0.71 -0.24
Sp8  -0.29  0.70
Sp9   0.99  1.17
Sp10 -0.29  0.70
Sp11 -0.29  0.70
Sp12  1.19  1.35
Sp13 -0.41 -0.38
Sp14  1.19  1.35
Sp15  1.19  1.35
Sp16 -0.20  0.22
Sp17  0.00  0.40
Sp18  0.71 -0.24
Sp19  0.31 -1.02
Sp20  1.39 -0.74
Sp21  1.39 -0.74
Sp22  1.20 -0.92
Sp23  1.39 -0.74
Sp24  1.39 -0.74
Sp25  0.48 -0.28
Sp26  0.48 -0.28
Sp27  0.64  0.93
Sp28  0.17 -0.67
Sp29 -0.55 -0.03
Sp30 -0.55 -0.03
Sp31 -0.30 -0.27
Sp32 -0.30 -0.27
Sp33  0.38 -0.76
Sp34  0.85 -1.16
Sp35 -0.30 -0.27
Sp36 -0.20  0.22
Sp37  1.18 -1.33
Sp38 -0.16 -0.62
Sp39 -0.41 -0.38
Sp40 -0.16 -0.62</code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.label</span>(rlq<span class="sc">$</span>lQ,<span class="at">boxes=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">s.label</span>(rlq<span class="sc">$</span>lQ, <span class="at">label=</span>aviurba<span class="sc">$</span>species.names.fr,<span class="at">boxes=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="AMV_chapter_files/figure-html/unnamed-chunk-49-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, is to see that we seems to have a gradient of response along the first axis (i.e.&nbsp;Loriot Jaune/Sp37 [coord=1.18; -1.33] and Alouette des champs/Sp9 [coord=0.99; 1.17]) and along the second axis (i.e.&nbsp;Loriot Jaune/Sp37 [coord=1.18; -1.33] and Fauvette des jardins/Sp21 [coord=0.99; 1.17]). We will see that we need to link this to the others variables (trait and environment) For species and sites, we do not have contribution because these variables do not contribute of the axis creation.</p>
<p>To conclude on this analysis, the two first axes explain 86.2% of the total variation with respectively 66.7%, and 19.5% of the total inertia.</p>
<p>The correlations between the environmental variables and the RLQ axes showed that the first axis is explained by Veg.cover.R100 (contribution of 16.95%), veg.cover.R22 (7.43%), noisy.yes (8.82%), small.bui.yes (11.22%), field.yes (8.17%), field.no (8.2%) and Veg.cover.R22 (7.43%). The traits variables that contribute to the first axis of the RLQ axes are breeding.ground (28.19%), feed.strat.foliage (19.8%), breeding.scrub (13.3%) and negatively with breeding.building (17.18%) and feed.strat.aerial (7.09%). In other words, breeding.ground, feed.strat.foliage, breeding.scrub, feed.strat.aerial and breeding.building were the higher explanatory attributes for this RLQ axis (explained by the length and the angle between the axes and the vectors).</p>
</section>
</section>
<section id="to-go-further-with-multivariate-analysis" class="level1">
<h1>To go further with Multivariate Analysis</h1>
<p>Two other methods of two tables analysis were not presented here :</p>
<ul>
<li><p><strong>Co-inertia</strong> is used when you have a table with you response variable <span class="math inline">\(Y\)</span> and a second one with <em>potentially</em> explaining variables, <span class="math inline">\(X\)</span>, <strong>but you do not have any <em>a priori</em></strong> about the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>.</p></li>
<li><p><strong>CCA</strong> is used with two table, where both <span class="math inline">\(Y\)</span> <strong>and</strong> <span class="math inline">\(X\)</span> <strong>are quantitative data</strong>. It works the same as RDA.</p></li>
<li><p>PCCA is CCA like but it includes a spacial dependency… Spacial and Temporal dependencies are a great deal in data analysis !</p></li>
</ul>
<p>Even if this presentation of multivariate analysis was not exhaustive, you can have a better view of what you can do when you are to analyse a data table. The method chosen will depend on the number of tables and the type of the variables (quantitative or qualitative). To help you decide what analysis to use regarding to the ones we presented here, you can have a look to this decision tree !</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="decision_tree.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><strong>Decision tree multivariate analysis (from A. Pannard)</strong></figcaption>
</figure>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>