---
title: "Ordinary Differential Equations and their application in Ecology"
bibliography: references.bib
author: "Amélie Cocchiara, Anastasia Paupe, Clément Monaury, Laura Martinez Anton, Theo Laguillez"
execute: 
  freeze: auto
output: 
  html_document:
   toc: true
   toc_float: true
editor: 
  markdown: 
    wrap: 72
---

```{r}
#Add packages
library(tidyverse)
```

Introduce objectifs of the chapter

I. Dynamics systems (definition)

II. Ordinary differential equation

<!-- -->

1)  Definition
2)  1-equation system

<!-- -->

III. 2-equations system

# **IV. 3-equation system**

## 1) SIR model and resolution by hand

The most used models in epidemiology are mathematical models of
infectious diseases such as the SIR model. These models are based on
compartmentalization that divide the population into various possible
disease states. The SIR model is composed of 3 compartments: initially
healthy or susceptible individuals (S), infected individuals (I) and
cured individuals or resistent (R).

$$SIR=\begin{cases}\frac{d_S}{d_t}=- \alpha SI-\gamma R &\text{Susceptible} \\ \frac{d_I}{d_t}=\alpha SI-\beta I&\text{Infected} \\ \frac{d_R}{d_t}=\beta I- \gamma R &\text{Resistent}\end{cases} 
\\
\\ \begin{align} With : & - \alpha \text{: disease transmission rate}
\\ & - \beta \text{: cure rate}
\\ & - \gamma \text{: coefficient of loss of immunity} \end{align}$$

We assume a closed population, so :
$$ S+I+R = 1 \Leftrightarrow R=1-S-I $$

Thus, we can express R from S and I, so we can remove the equation from
our system and we end up with a system with 2 equations.

### Balance points

We look for balance points such as:

$$ SIR=\begin{cases}\frac{d_S}{d_t}=0 &\text{Susceptible} \\ \frac{d_I}{d_t}=0&\text{Infected} \end{cases} $$

To do this, we solve :

$$ \begin{align} & \begin{cases} - \alpha SI-\gamma R = 0 &\text{Susceptible} \\ \alpha SI-\beta I =0 &\text{Infected} \end{cases}
\\ \Leftrightarrow & \begin{cases} \alpha SI-\gamma (1-S-I) = 0 \\ \alpha SI-\beta I =0 \end{cases} \end{align} $$

We first focus on solving:

$$\begin{align} & \alpha SI - \beta I=0
\\ \Leftrightarrow \ & I(\alpha S- \beta) =0 \\ \Leftrightarrow \ & I=0\ or\ S= \frac{\beta}{\alpha} \end{align}$$

If *I = 0*, we integrate I=0 into our "susceptible" equation to obtain
the solution for S:

$$\begin{align} & \ \ \ \ \ \begin{cases} \alpha S *0 + \gamma (1-S-0)=0 \\ I=0 \end{cases} \\ & \Leftrightarrow \begin{cases} \gamma (1-S)=0 \\ I=O \end{cases} \\ &\text{We thus obtain our first solution:} \\ &\Leftrightarrow \begin{cases} S=1 \\ I=0 \end{cases} \end{align} $$

It's the disease-free equilibrium (DFE).

If *S = b/a*, we integrate S into our "susceptible" equation to obtain
the solution for I:

$$
\begin{align} & \ \ \ \ \  \begin{cases} - \alpha \frac{\beta}{\alpha} I + \gamma (1- \frac{\beta}{\alpha} - I) =0
\\ S = \frac{\beta}{\alpha} \end{cases}
\\ & \Leftrightarrow \begin{cases} -\beta I + \gamma - \frac{\beta \gamma}{\alpha} -\gamma I = 0 \\ S = \frac{\beta}{\alpha} \end{cases}
\\ & \Leftrightarrow \begin{cases} \beta I + \gamma I = \gamma (1 - \frac{\beta}{\alpha}) \\ S= \frac{\beta}{\alpha} \end{cases}
\\ & \text{We thus obtain our first solution:}
\\ & \Leftrightarrow \begin{cases} I= \frac{\gamma (1- \frac{\beta}{\alpha})}{\beta + \gamma} \\ S=\frac{\beta}{\alpha} \end{cases} \end{align} 
$$

It's the endemic equilibrium (EE).

### Jacobian matrix

Now, let's perform linear stability analysis for each equilibrium point
by computing the Jacobian matrix :

$$ J=\begin{bmatrix} \frac{\delta S}{\delta S} & \frac{\delta S}{\delta I} \\ \frac{\delta I}{\delta S} & \frac{\delta I}{\delta I}  \end{bmatrix} \Leftrightarrow \begin{bmatrix} - \alpha I- \gamma & - \alpha S- \gamma \\ \alpha I & \alpha S- \beta \end{bmatrix} $$

Analyze the stability of each equilibrium point by examining the signs
of the real parts of the eigenvalues. If the real parts are all
negative, the equilibrium is stable; if any are positive, the
equilibrium is unstable. The stability will depend on the specific
values of the parameters **α** and **β**.

### For the disease-free equilibrium :

$$ J(1,0)= \begin{bmatrix} -\gamma & - \alpha -\gamma \\ 0 & \alpha - \beta \end{bmatrix} $$

The Jacobian matrix for the pair (1,0) is an upper triangular matrix, so
the eigenvalues are the diagonal elements :
$$ \lambda _1 = - \gamma \ \text{and} \ \lambda _2 = \alpha - \beta $$

γ is a coefficient representing loss of immunity, so γ\>0.

So : $$ \begin{align} & \lambda _1 <0 
\\ & \text{If:} \ - \alpha > \beta , \ \lambda _2 > 0 \ \text{Unstable equilibrium point}
\\& \ \ \ \  - \alpha < \beta , \ \lambda _2 < 0 \ \text{Asymptotically stable point}  \end{align} $$

In order to better understand the behavior of the unstable point, we
look for the sign of the determinant of the matrix:

$$ det(J(1,0))= - \gamma (\alpha - \beta ) \\
\Leftrightarrow \ \gamma (\beta - \alpha)
\\ \gamma > 0 \ and \ \alpha > \beta
\\ det(J(1,0)) < 0 \Rightarrow \text{Saddle point} $$

Saddle points exhibit a combination of stable and unstable behavior in
different directions in the state space.

### For the endemic equilibrium

$$ J(\frac{\beta}{\alpha},\frac{\gamma (1-\frac{\beta}{\alpha})}{\beta + \gamma})= \begin{bmatrix} \frac{\gamma (\beta- \alpha)}{\beta + \gamma} - \gamma & - \beta -\gamma \\ \frac{\gamma (\alpha - \beta)}{\beta + \gamma} & 0 \end{bmatrix} $$

Here, we do not have a characteristic matrix so to determine the
eigenvalues, it will be necessary to solve the characteristic
polynomial. We will first look at the sign of the determinant of the
matrix to study the behavior of the system.

So, we calculate the determinant :
$$\begin{align} & det(J(\frac{\beta}{\alpha},\frac{\gamma (1-\frac{\beta}{\alpha})}{\beta + \gamma})) = - (- \beta - \gamma) * \frac{\gamma (\alpha - \beta)}{\beta + \gamma} = \gamma (\alpha - \beta) \end{align}$$

If **α** \< **β**, det(J) \< 0 : a saddle point.

If **α** \> **β**, det(J) \> 0 : look the trace of the matrix.

$$Tr(J(S,I)) = \frac{\gamma (\beta - \alpha)}{\beta - \gamma} - \gamma
\\
\\ \gamma > 0 \ \text{and} \ \alpha > \beta
\\
\\ \text{So:} \ Tr(J(S,I)) <0 $$

In this case we have a stable point. The specific type of stability
depends on the signs and nature of the eigenvalues.

Now, we solve the characteristic polynomial to obtain the eigenvalues:

$$ det(J- \lambda Id) = 0
\\ \text{with Id : identity matrix}
\\
\\ \Leftrightarrow \begin{bmatrix} \frac{\gamma (\beta - \alpha)}{\beta + \gamma}-\gamma -\lambda 
& - \beta - \gamma
\\  \frac{\gamma (\alpha - \beta)}{\beta + \gamma} & - \lambda \end{bmatrix} = 0
\\ \Leftrightarrow - \lambda (
\frac{\gamma (\beta - \alpha)}{\beta + \gamma}-\gamma -\lambda) 
- (- \beta - \gamma )(
\frac{\gamma (\alpha - \beta)}{\beta + \gamma}
) = 0 
\\ \Leftrightarrow \lambda^2 + \lambda (\gamma +  \frac{\gamma (\alpha- \beta)}{\beta + \gamma})+ \gamma (\alpha - \beta) = 0 $$

The number of solutions is indicated by the value of the discriminant :
$$ \Delta = (\gamma +  \frac{\gamma (\alpha - \beta)}{\beta + \gamma})^2 - 4 (\gamma (\alpha - \beta))
\\ \text{With} \ \alpha > \beta
\\
\\
\begin {align} \text{If} \ & \Delta < 0:\ \text{you will have two complex conjugate roots.} \\ &\Delta = 0:\ \text{you will have one real repeated root.} \\ &\Delta>0: \ \text{you will have two distinct real roots.} \end{align} $$

From now,we will assign numerical values:
$$ \alpha = 4, \ \beta = 2 \ and \ \gamma = 1 
\\
\Delta = (1 + \frac{1(4-2)}{1+2})^2 - 4(1(4-2))= -5.22 
\\ So \ \Delta < 0 $$

$$ \text{Solutions are given by the following formula:}
\\ \lambda= \frac{-(\gamma + \frac{
\gamma (\alpha - \beta)}{\beta + \gamma}) \pm \sqrt \Delta}{2}i
\\ \frac{\sqrt \Delta}{2}i: \ \text{imaginary part.}
\\ \frac{-(\gamma + \frac{\gamma (\alpha - \beta)}{\beta +\gamma})}{2}: \ \text{real part.} 
\\
\\ \text{Real part}= -\frac{5}{3}$$

The stability of a linear system is often determined by the real parts
of the eigenvalues. In this case, the real part is negative which
indicates stability.

## 2) Lotka-Volterra : A three-species model

Biotic interactions are complex, requiring the interaction of numerous
parameters. If we take the **Lotka-Volterra** example, it only considers
the **interactions between two species**, prey and predator. It assumes
a constant mortality rate among predators, regardless of prey. However,
**predators are themselves the prey of other super-predators**. Their
mortality rate should therefore depend on the super-predators they
encounter. Thus, the **prey-predator-superpredator** extension of the
Lotka-Volterra model would be a good representation of natural trophic
interactions.

In this case, we considerer a superpredator, a predator an a prey.

A superpredator is an organism that reaches adulthood at the top of the
food chain. Thus, by definition, a superpredator is not the prey of any
other species. The predator is consider to be in the middle of the food
chain and the prey at the bottom.

The model can be written as the following system of differential
equations:

$$ PPS=\begin{cases} \frac{d_x}{d_t}=ax-bxy &\text{Prey} \\ \frac{d_y}{d_t}=-cy+dxy-eyz&\text{Predator} \\ \frac{d_z}{d_t}=-fz+gyz &\text{Superpredator} \end{cases} $$

The model parameters are :

-   *a* : *x* natural growth rate

-   *-f* and *-c* : natural death rate of *y* and *z*

-   The growth rate of *y* and *z* depends on the number of prey caught.
    It is modeled by *dxy* for *y* and by *gyz* for *z*.

-   The death rate of *x* and *y* depends on the number of top predators
    *y* for *x* and *z* for *y* . It is modeled by *-bxy* for *x* and by
    *-eyz* for *y*.

This model is only useful for chains of predators. It doesn't take into
account the presence of several predators with different dynamics on the
same prey.

Let's try to solve this system: To do this, the first step is to find
the balance of the model, that is to say the values (x,y,z) so that:

$$\frac{d_x}{d_t}=\frac{d_y}{d_t}=\frac{d_z}{d_t}=0$$

We take our previous systems that we factored:

$$ PPS=\begin{cases}\frac{d_x}{d_t}=x(a-by) &\text{Prey} \\ \frac{d_y}{d_t}=y(dxy-c-ez)&\text{Predator} \\ \frac{d_z}{d_t}=z(gy-f) &\text{Superpredator}\end{cases} $$

The obvious solution is (0,0,0) but is not the only one. Indeed, for the
derivatives to be equal to 0, then we must find the following solution:

$$(a-by)=(gy-f)=(dx-c-ez)=0$$

We first solve :
$$a-by=0\Leftrightarrow a=by \Leftrightarrow y=\frac{a}{b}$$
$$gy-f=0\Leftrightarrow f=by \Leftrightarrow y=\frac{f}{g}$$

So, a solution for a yeq is: $$y_{eq}=\frac{a}{b}=\frac{f}{g}$$
Therefore, there is an equilibrium when : $$ga=fb$$

In order to determine the other solutions, we must solve the following
matrix :
$$ M=\begin{bmatrix}a-by&-bx&0\\dy&-c+dx-ez&-ey\\0&gz&gy-f\end{bmatrix}$$

We invite you to look at the chapter on matrix calculation to determine
the solutions.

**But don't panic** ! In ecology we are lucky to have a great tool, R,
which allows us to resolve this type of system.

## 3) Resolution under R

## 4) Generalizations of the three-species model and other examples

### a) Generalizations of the three-species model

The three-species model presented previously is a simplified model that
models a perfectly linear trophic chain. However, nature is more complex
and a species can be preyed upon by multiple predators and predators can
predate multiple prey items.

We invite you to go see the course of Lalith Devireddy (2016) entitled
"Extending the Lotka-Volterra Equations" which develops this model and
its resolutions.

Many models with 3-ODE systems exist to model ecological dynamics. Here
we will present two additional ones to you but we will not develop their
resolution.

### b) NPZ model

The NPZ model makes it possible to model the lake production of a
pelagic ecosystem. This model studies variations in nutrients,
phytoplankton and zooplankton that are linked to each other.

Conclusion & motivation words
