<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The Companion book a M1 MODE student should have! - Linear modelling in ecology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">The Companion book a M1 MODE student should have!</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MarieEtienne/MODE_reproduciblescience" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./prior_course.html" rel="" target="">
 <span class="menu-text">Before the class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./instructions.html" rel="" target="">
 <span class="menu-text">Instructions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses-materials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Courses Materials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-courses-materials">    
        <li>
    <a class="dropdown-item" href="https://marieetienne.github.io/reproductibilite/_presentation/english_version.html" rel="" target="">
 <span class="dropdown-text">Git Intro</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-m1-mode-survival-book-by-the-m2-students" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">M1 MODE Survival book by the M2 students</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-m1-mode-survival-book-by-the-m2-students">    
        <li>
    <a class="dropdown-item" href="./AMV_chapter.html" rel="" target="">
 <span class="dropdown-text">Multivariate Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./linear_modelling.html" rel="" target="">
 <span class="dropdown-text">Linear modelling in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Mixed_models.html" rel="" target="">
 <span class="dropdown-text">Mixed models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chapter_dependance.html" rel="" target="">
 <span class="dropdown-text">Dependent data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Matrix.html" rel="" target="">
 <span class="dropdown-text">Matrix models and applications in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Chap_ODE.html" rel="" target="">
 <span class="dropdown-text">Ordinary Differential Equations in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./r_chapter_boostrapping_resampling.html" rel="" target="">
 <span class="dropdown-text">Resampling methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bayesian_modeles.html" rel="" target="">
 <span class="dropdown-text">Bayesian models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./simple_chapter.html" rel="" target="">
 <span class="dropdown-text">A simple chapter with no code</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">INTRODUCTION</a>
  <ul class="collapse">
  <li><a href="#the-statistical-test" id="toc-the-statistical-test" class="nav-link" data-scroll-target="#the-statistical-test">THE STATISTICAL TEST</a>
  <ul class="collapse">
  <li><a href="#the-null-and-alternative-hypotheses" id="toc-the-null-and-alternative-hypotheses" class="nav-link" data-scroll-target="#the-null-and-alternative-hypotheses">1. The null and alternative hypotheses</a></li>
  <li><a href="#calculation-of-the-observed-value-tobs" id="toc-calculation-of-the-observed-value-tobs" class="nav-link" data-scroll-target="#calculation-of-the-observed-value-tobs">2. Calculation of the observed value Tobs</a></li>
  <li><a href="#the-p-value" id="toc-the-p-value" class="nav-link" data-scroll-target="#the-p-value">3. The P-value</a></li>
  <li><a href="#rejection-or-validation-of-the-hypothesis" id="toc-rejection-or-validation-of-the-hypothesis" class="nav-link" data-scroll-target="#rejection-or-validation-of-the-hypothesis">4. Rejection or validation of the hypothesis</a></li>
  </ul></li>
  <li><a href="#statistical-modelling" id="toc-statistical-modelling" class="nav-link" data-scroll-target="#statistical-modelling">STATISTICAL MODELLING</a></li>
  </ul></li>
  <li><a href="#i.-general-linear-models" id="toc-i.-general-linear-models" class="nav-link" data-scroll-target="#i.-general-linear-models">I. GENERAL LINEAR MODELS</a>
  <ul class="collapse">
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">1) ANOVA</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">INTRODUCTION</a></li>
  <li><a href="#simple-factor-anova" id="toc-simple-factor-anova" class="nav-link" data-scroll-target="#simple-factor-anova">Simple factor ANOVA</a></li>
  <li><a href="#multiple-factor-anova" id="toc-multiple-factor-anova" class="nav-link" data-scroll-target="#multiple-factor-anova">Multiple factor ANOVA</a></li>
  <li><a href="#anova-example" id="toc-anova-example" class="nav-link" data-scroll-target="#anova-example">ANOVA EXAMPLE</a></li>
  <li><a href="#dataset-presentation-and-objectives-of-the-analysis" id="toc-dataset-presentation-and-objectives-of-the-analysis" class="nav-link" data-scroll-target="#dataset-presentation-and-objectives-of-the-analysis">Dataset presentation and objectives of the analysis</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">Data exploration</a></li>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link" data-scroll-target="#statistical-analysis">Statistical analysis</a></li>
  <li><a href="#model-validation-check-the-assumptions" id="toc-model-validation-check-the-assumptions" class="nav-link" data-scroll-target="#model-validation-check-the-assumptions">Model validation: Check the assumptions</a></li>
  </ul></li>
  <li><a href="#ancova" id="toc-ancova" class="nav-link" data-scroll-target="#ancova">2) ANCOVA</a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2">INTRODUCTION</a></li>
  <li><a href="#ancova-example" id="toc-ancova-example" class="nav-link" data-scroll-target="#ancova-example">ANCOVA EXAMPLE</a></li>
  <li><a href="#dataset-presentation-and-objectives-of-the-analysis-1" id="toc-dataset-presentation-and-objectives-of-the-analysis-1" class="nav-link" data-scroll-target="#dataset-presentation-and-objectives-of-the-analysis-1">Dataset presentation and objectives of the analysis</a></li>
  <li><a href="#data-exploration-1" id="toc-data-exploration-1" class="nav-link" data-scroll-target="#data-exploration-1">Data exploration</a></li>
  <li><a href="#statistical-analysis-1" id="toc-statistical-analysis-1" class="nav-link" data-scroll-target="#statistical-analysis-1">Statistical analysis</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression">3) REGRESSION</a>
  <ul class="collapse">
  <li><a href="#introduction-3" id="toc-introduction-3" class="nav-link" data-scroll-target="#introduction-3">INTRODUCTION</a></li>
  <li><a href="#model-writing" id="toc-model-writing" class="nav-link" data-scroll-target="#model-writing">MODEL WRITING</a></li>
  <li><a href="#regression-example" id="toc-regression-example" class="nav-link" data-scroll-target="#regression-example">REGRESSION EXAMPLE:</a></li>
  <li><a href="#dataset-presentation-and-objectives-of-the-analysis-2" id="toc-dataset-presentation-and-objectives-of-the-analysis-2" class="nav-link" data-scroll-target="#dataset-presentation-and-objectives-of-the-analysis-2">Dataset presentation and objectives of the analysis</a></li>
  <li><a href="#data-exploration-2" id="toc-data-exploration-2" class="nav-link" data-scroll-target="#data-exploration-2">Data exploration</a></li>
  <li><a href="#statistical-analysis-2" id="toc-statistical-analysis-2" class="nav-link" data-scroll-target="#statistical-analysis-2">Statistical analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#ii-generalized-linear-models" id="toc-ii-generalized-linear-models" class="nav-link" data-scroll-target="#ii-generalized-linear-models">II/ GENERALIZED LINEAR MODELS</a>
  <ul class="collapse">
  <li><a href="#binomial-law" id="toc-binomial-law" class="nav-link" data-scroll-target="#binomial-law">1) Binomial Law</a>
  <ul class="collapse">
  <li><a href="#introduction-4" id="toc-introduction-4" class="nav-link" data-scroll-target="#introduction-4">INTRODUCTION</a></li>
  <li><a href="#binomial-law-example" id="toc-binomial-law-example" class="nav-link" data-scroll-target="#binomial-law-example">BINOMIAL LAW EXAMPLE</a></li>
  <li><a href="#dataset-presentation-and-objectives-of-the-analysis-3" id="toc-dataset-presentation-and-objectives-of-the-analysis-3" class="nav-link" data-scroll-target="#dataset-presentation-and-objectives-of-the-analysis-3">Dataset presentation and objectives of the analysis</a></li>
  <li><a href="#data-exploration-3" id="toc-data-exploration-3" class="nav-link" data-scroll-target="#data-exploration-3">Data exploration</a></li>
  <li><a href="#statistical-analysis-3" id="toc-statistical-analysis-3" class="nav-link" data-scroll-target="#statistical-analysis-3">Statistical analysis</a></li>
  </ul></li>
  <li><a href="#poisson-law" id="toc-poisson-law" class="nav-link" data-scroll-target="#poisson-law">2) POISSON LAW</a>
  <ul class="collapse">
  <li><a href="#introduction-5" id="toc-introduction-5" class="nav-link" data-scroll-target="#introduction-5">INTRODUCTION</a></li>
  <li><a href="#poisson-law-example" id="toc-poisson-law-example" class="nav-link" data-scroll-target="#poisson-law-example">POISSON LAW EXAMPLE</a></li>
  <li><a href="#data-exploration-4" id="toc-data-exploration-4" class="nav-link" data-scroll-target="#data-exploration-4">Data exploration</a></li>
  <li><a href="#statistical-analysis-4" id="toc-statistical-analysis-4" class="nav-link" data-scroll-target="#statistical-analysis-4">Statistical analysis</a></li>
  </ul></li>
  <li><a href="#negative-binomial-law" id="toc-negative-binomial-law" class="nav-link" data-scroll-target="#negative-binomial-law">3) NEGATIVE BINOMIAL LAW</a>
  <ul class="collapse">
  <li><a href="#introduction-6" id="toc-introduction-6" class="nav-link" data-scroll-target="#introduction-6">INTRODUCTION</a></li>
  <li><a href="#negative-binomial-law-example" id="toc-negative-binomial-law-example" class="nav-link" data-scroll-target="#negative-binomial-law-example">NEGATIVE BINOMIAL LAW EXAMPLE</a></li>
  <li><a href="#dataset-presentation-and-objectives-of-the-analysis-4" id="toc-dataset-presentation-and-objectives-of-the-analysis-4" class="nav-link" data-scroll-target="#dataset-presentation-and-objectives-of-the-analysis-4">Dataset presentation and objectives of the analysis</a></li>
  <li><a href="#data-exploration-5" id="toc-data-exploration-5" class="nav-link" data-scroll-target="#data-exploration-5">Data exploration</a></li>
  <li><a href="#statistical-analysis-5" id="toc-statistical-analysis-5" class="nav-link" data-scroll-target="#statistical-analysis-5">Statistical analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#iii-model-validation" id="toc-iii-model-validation" class="nav-link" data-scroll-target="#iii-model-validation">III/ MODEL VALIDATION</a>
  <ul class="collapse">
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals">Normality of residuals</a></li>
  <li><a href="#homogeneity-of-variances" id="toc-homogeneity-of-variances" class="nav-link" data-scroll-target="#homogeneity-of-variances">Homogeneity of variances</a></li>
  <li><a href="#independence-of-residuals" id="toc-independence-of-residuals" class="nav-link" data-scroll-target="#independence-of-residuals">Independence of residuals</a></li>
  </ul></li>
  <li><a href="#general-conclusion" id="toc-general-conclusion" class="nav-link" data-scroll-target="#general-conclusion">GENERAL CONCLUSION</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear modelling in ecology</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>INTRODUCTION</h1>
<section id="the-statistical-test" class="level2">
<h2 class="anchored" data-anchor-id="the-statistical-test">THE STATISTICAL TEST</h2>
<p>The purpose of statistics is to test a hypothesis. You would need to follow these steps:</p>
<section id="the-null-and-alternative-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="the-null-and-alternative-hypotheses">1. The null and alternative hypotheses</h3>
<p>They define different proposed relationships between dependent and independent variable(s).</p>
<p><em>Null hypothesis H0</em> = no relationship between dependent and independent variables.</p>
<p><em>Alternative hypothesis H1</em> = some expected relationship between the variables.</p>
</section>
<section id="calculation-of-the-observed-value-tobs" class="level3">
<h3 class="anchored" data-anchor-id="calculation-of-the-observed-value-tobs">2. Calculation of the observed value Tobs</h3>
<p>The observed value Tobs of the test statistic T is calculated from data given that the T variable has a probability distribution known under H0.</p>
</section>
<section id="the-p-value" class="level3">
<h3 class="anchored" data-anchor-id="the-p-value">3. The P-value</h3>
<p>To get this value, you need to calculate the probability of observing Tobs value in this T distribution knowing the distribution of the test statistic T under H0.</p>
</section>
<section id="rejection-or-validation-of-the-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="rejection-or-validation-of-the-hypothesis">4. Rejection or validation of the hypothesis</h3>
<p>If the P-value is less than (or equal to) <span class="math inline">\(\alpha\)</span>, then the null hypothesis is rejected in favor of the alternative hypothesis and if the P-value is greater than <span class="math inline">\(\alpha\)</span> then the null hypothesis is not rejected. WARNING : never say that the null hypothesis is validated. You just know that you cannot reject it with the information you have. There could be relationships that have not been detected.</p>
</section>
</section>
<section id="statistical-modelling" class="level2">
<h2 class="anchored" data-anchor-id="statistical-modelling">STATISTICAL MODELLING</h2>
<p>Linear modelling is widely used in statistics to model observed data, by considering their random nature. It explains one dependent variable, noted Y (random variable, also called <strong>the response variable</strong>) in function to independent variables (also called <strong>predictors</strong> or <strong>explanatory variables</strong>), also observed/measured on statistical units of the sample. In this chapter, you will see different models corresponding to different statistical tests. It happens that several tests can be conducted for the same dataset and hypothesis ; in this case, you will select the most powerful test. It is the one with the lowest <span class="math inline">\(\beta\)</span>-error (given at the end).</p>
</section>
</section>
<section id="i.-general-linear-models" class="level1">
<h1>I. GENERAL LINEAR MODELS</h1>
<p>First let’s get to know the most basic and simple linear models. We also call them <em>‘Gaussian’</em> because of their allure. They are used and validated following three eligibility conditions that you will find in part ‘Model validation’.</p>
<section id="anova" class="level2">
<h2 class="anchored" data-anchor-id="anova">1) ANOVA</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">INTRODUCTION</h3>
<p>ANOVA (Analysis of variance) is one of the most widespread techniques in data analysis. We use it to test the effect of one or more independent quantitative variables (Xs) on a dependent qualitative variable (Y). The categorical qualitative variables are named ‘factors’, et each factor has different levels that are chosen and fixed.</p>
<p>We consider 2 types of ANOVA: in the presence of a single variable X in the analysis, we follow a <em>simple factor ANOVA</em>; in the presence of several variables X, we follow a <em>multiple factor ANOVA</em>.</p>
</section>
<section id="simple-factor-anova" class="level3">
<h3 class="anchored" data-anchor-id="simple-factor-anova">Simple factor ANOVA</h3>
<p>The model takes the following form: <span class="math display">\[ Y_{ij} = \mu + \alpha_{i} + \epsilon_{ij}  \]</span> where <span class="math inline">\(\mu\)</span> is the overall mean, <span class="math inline">\(\alpha_{i}\)</span> is the effect of the ith level of the single factor and <span class="math inline">\(\epsilon\)</span> is the error term (i.e.&nbsp;residuals).</p>
</section>
<section id="multiple-factor-anova" class="level3">
<h3 class="anchored" data-anchor-id="multiple-factor-anova">Multiple factor ANOVA</h3>
<p>The ANOVA model depends on the experimental design: factorial or nested.</p>
<p><strong>Full factorial design</strong> This design studies the influence of multiple factors and of their interactions on the variable of interest. We frequently want to test for differences in the response variable due to the multiple factors, called ‘main effects’. What we do is test the effects of each main effect separately, then whether or not these effects interact with each other (‘factor interactions’). Considering a factorial design with two factors, the model takes the form: <span class="math display">\[ Y_{ijk} = \mu + \alpha_{i} + \beta_{j} + \gamma_{ij} +\epsilon_{ijk}  \]</span> where <span class="math inline">\(\mu\)</span> is the overall mean, <span class="math inline">\(\alpha_{i}\)</span> is the effect of the ith group of the first factor, and <span class="math inline">\(\beta_{j}\)</span> is the effect of the jth group of the second factor, <span class="math inline">\(\gamma_{ij}\)</span> is the interaction between both factors and <span class="math inline">\(\epsilon\)</span> is the error term (i.e.&nbsp;residuals).</p>
<p><strong>Nested ANOVA</strong> In this design, the levels of a factor are hierarchically nested within the levels of another factor. Considering a nested design with two factors in which B factor is nested in A factor, the model takes the form: <span class="math display">\[ Y_{ijk} = \mu + \alpha_{i} + \beta_{j/i} +\epsilon_{ijk}  \]</span> where <span class="math inline">\(\mu\)</span> is the overall mean, <span class="math inline">\(\alpha_{i}\)</span> is the effect of the ith group of the first factor, and <span class="math inline">\(\beta_{j/i}\)</span> is the effect of the jth group of the second factor nested in the ith group of the first factor and <span class="math inline">\(\epsilon\)</span> is the error term (i.e.&nbsp;residuals).</p>
</section>
<section id="anova-example" class="level3">
<h3 class="anchored" data-anchor-id="anova-example">ANOVA EXAMPLE</h3>
<p>Let’s consider an experimental data originated to an ANOVA example developed by James Lavender &amp; Alistair Poore - 2016 (<a href="https://environmentalcomputing.net/statistics/linear-models/anova/anova-factorial/" class="uri">https://environmentalcomputing.net/statistics/linear-models/anova/anova-factorial/</a>).</p>
</section>
<section id="dataset-presentation-and-objectives-of-the-analysis" class="level3">
<h3 class="anchored" data-anchor-id="dataset-presentation-and-objectives-of-the-analysis">Dataset presentation and objectives of the analysis</h3>
<p>In this data analysis, we will focus on experimental data with two factors that are both applied to all statistical individuals. An ecologist wants to test the effects of metal contamination on the number of species found in sessile marine invertebrates (i.e.&nbsp;sponges). This ecologist would precisely like to know whether copper enrichment reduces species richness, but also know that the richness of invertebrates can depend on whether the substrate is vertical or horizontal. In order to do this, they made an experiment where species richness was recorded in replicate samples in each of the six combinations of copper enrichment (<span class="math inline">\(“None”\)</span>,<span class="math inline">\(“Low”\)</span>,<span class="math inline">\(“High”\)</span>) and orientation (<span class="math inline">\(“Vertical”\)</span>,<span class="math inline">\(“Horizontal”\)</span>). The experimental design is <strong>factorial</strong> because all levels of one treatment are represented in all levels of the other treatment (i.e.&nbsp;crossed factors).</p>
<p>In consequence, the factorial ANOVA will test whether there are:</p>
<ul>
<li><p>any differences in species richness among the three levels of copper enrichment</p></li>
<li><p>any differences in species richness among the two levels of substrate orientation</p></li>
<li><p>any interactions between copper and orientation (i.e.&nbsp;the effect of the copper enrichment depends on the substrate orientation and reciprocally).</p></li>
</ul>
<p>We have three null hypotheses:</p>
<ul>
<li><p>there is no difference between the means for each level of copper enrichment, H0: <span class="math inline">\(\mu_{None}\)</span>=<span class="math inline">\(\mu_{Low}\)</span>=<span class="math inline">\(\mu_{High}\)</span></p></li>
<li><p>there is no difference between the means for each level of orientation, H0: <span class="math inline">\(\mu_{Vertical}\)</span>=<span class="math inline">\(\mu_{Horizontal}\)</span></p></li>
<li><p>there is no interaction between both factors (i.e.&nbsp;if factor effects exist, the factors do not interact)</p></li>
</ul>
<p>Let’s perform a two-factor ANOVA, something far better than running two separate single factor ANOVAs that contrast copper effects for each level of the substrate orientation, for 3 reasons:</p>
<ul>
<li><ol type="1">
<li>we have more statistical power (higher degrees of freedom)</li>
</ol></li>
<li><ol start="2" type="1">
<li>we can test whether the main effects interact or not</li>
</ol></li>
<li><ol start="3" type="1">
<li>we reduce the risk of statistical error (i.e.&nbsp;we can’t forget that each time we perform a separate statistical analysis, we get <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> risks)</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset import</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>datasessile <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"sessile.txt"</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>datasessile<span class="sc">$</span>Copper<span class="ot">&lt;-</span><span class="fu">as.factor</span>(datasessile<span class="sc">$</span>Copper)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>datasessile<span class="sc">$</span>Orientation<span class="ot">&lt;-</span><span class="fu">as.factor</span>(datasessile<span class="sc">$</span>Orientation)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datasessile)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   60 obs. of  3 variables:
 $ Copper     : Factor w/ 3 levels "High","Low","None": 3 3 3 3 3 3 3 3 3 3 ...
 $ Orientation: Factor w/ 2 levels "Horizontal","vertical": 2 2 2 2 2 2 2 2 2 2 ...
 $ Richness   : int  68 64 64 63 69 63 70 68 68 62 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for presence of missing values</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(datasessile))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Copper Orientation    Richness 
          0           0           0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There is no missing value.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration">Data exploration</h3>
<p>Before any statistical analysis, we <strong>MUST</strong> explore the data in order to prevent any error. Here is the list of explorations to perform before modelling:</p>
<ol type="1">
<li><p>Check presence of outliers in <span class="math inline">\(Y\)</span> and distribution of <span class="math inline">\(Y\)</span> values</p></li>
<li><p>If <span class="math inline">\(X\)</span> is a quantitative independent variable, check presence of outliers in X and distribution of X values</p></li>
</ol>
<p>2b. If <span class="math inline">\(X\)</span> is a qualitative independent variable, analyse the number of levels and the number of individuals per level</p>
<ol start="3" type="1">
<li><p>Analyse the potential relationships between <span class="math inline">\(Y\)</span> and the <span class="math inline">\(X_{s}\)</span></p></li>
<li><p>Check presence of interactions between <span class="math inline">\(X_{s}\)</span></p></li>
<li><p>Check presence of collinearity between <span class="math inline">\(X_{s}\)</span></p></li>
</ol>
</section>
<section id="statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>For the statistical modelling, we first analyse the full model (model containing all independent variables and interactions to test).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(Richness<span class="sc">~</span>Copper<span class="sc">+</span>Orientation<span class="sc">+</span>Copper<span class="sc">:</span>Orientation,<span class="at">data=</span>datasessile)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Comment : a simplest way to write this</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(Richness<span class="sc">~</span>Copper<span class="sc">*</span>Orientation,<span class="at">data=</span>datasessile)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Then we check for significance</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Richness ~ Copper * Orientation
                   Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;                           467.0 135.12                      
Copper:Orientation  2     570.7 1037.7 179.03  32.995 4.341e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We here have a significant interaction between COPPER and ORIENTATION, shown by the test statistic, F value and its associated p-value (Pr(&gt;F)). This means that the effect of one factor (COPPER) depends upon the other (ORIENTATION). In this example, it would mean that the effect of copper enrichment is not consistent between the vertical and horizontal habitats. This complexifies the interpretation of the main effects as a consequence. As the interaction is significant, the full model is the candidate model (i.e.&nbsp;the model containing only significant terms). To understand how factors and their interaction influence the species richness, we must analyse the coefficients of the model.</p>
<p><strong>Model’s coefficients analysis</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Candidate model formulation</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(Richness<span class="sc">~</span>Copper<span class="sc">*</span>Orientation,<span class="at">data=</span>datasessile)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Richness ~ Copper * Orientation, data = datasessile)

Residuals:
   Min     1Q Median     3Q    Max 
-5.700 -1.825  0.350  1.400 11.400 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      55.400      0.930  59.573  &lt; 2e-16 ***
CopperLow                         0.400      1.315   0.304    0.762    
CopperNone                       14.200      1.315  10.797 4.22e-15 ***
Orientationvertical             -11.700      1.315  -8.896 3.63e-12 ***
CopperLow:Orientationvertical    15.100      1.860   8.119 6.35e-11 ***
CopperNone:Orientationvertical    8.000      1.860   4.301 7.17e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.941 on 54 degrees of freedom
Multiple R-squared:  0.8986,    Adjusted R-squared:  0.8893 
F-statistic: 95.76 on 5 and 54 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This table detailed the coefficients of the model with coefficients associated with each level of the significant fixed factor. For each factor, one level is called ‘the baseline’, meaning that its coefficient is 0 (also called the reference level).</p>
<p>From this table, coefficients are : <strong>COPPER FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Copper_{High}\)</span> = 0 (the baseline of the factor COPPER)</p></li>
<li><p><span class="math inline">\(Copper_{Low}\)</span> = <span class="math inline">\(0.4^{NS}\)</span></p></li>
<li><p><span class="math inline">\(Copper_{None}\)</span> = <span class="math inline">\(14.2^{***}\)</span></p></li>
</ul>
<p><strong>ORIENTATION FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Orientation_{Horizontal}\)</span> = 0 (the baseline of the factor ORIENTATION)</p></li>
<li><p><span class="math inline">\(Orientation_{Vertical}\)</span>= <span class="math inline">\(-11.7^{***}\)</span></p></li>
</ul>
<p><strong>ORIENTATION:COPPER INTERACTION</strong></p>
<ul>
<li><p><span class="math inline">\(Copper_{Low}\)</span> : <span class="math inline">\(Orientation_{Vertical}\)</span> = <span class="math inline">\(15.1^{***}\)</span></p></li>
<li><p><span class="math inline">\(Copper_{None}\)</span> : <span class="math inline">\(Orientation_{Vertical}\)</span> = <span class="math inline">\(8^{***}\)</span></p></li>
</ul>
<p>So, the candidate model is: <span class="math display">\[ Species\:Richness = 55.4  \]</span> <span class="math display">\[+ [\:Copper_{High}=0;\:Copper_{Low}=0.4^{NS}\:,\:Copper_{None}=14.2^{***} ]  \]</span> <span class="math display">\[ +[Orientation_{Horizontal}=0.0; \:Orientation_{Vertical}=-11.7^{***}]  \]</span> <span class="math display">\[ +[Copper_{Low} : Orientation_{Vertical} = 15.1^{***};\:Copper_{None} : Orientation_{Vertical} = 8^{***}]\]</span></p>
<p>A quick way to help understand an interaction, if we get one, is to examine the interaction plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interactions graphic</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(datasessile<span class="sc">$</span>Richness<span class="sc">~</span>datasessile<span class="sc">$</span>Copper<span class="sc">*</span>datasessile<span class="sc">$</span>Orientation, <span class="at">varwidth =</span> <span class="cn">TRUE</span>, <span class="at">ylab =</span> <span class="st">"Species Richness"</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">main =</span> <span class="st">""</span>,<span class="at">cex.axis=</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Multiple comparisons</strong></p>
<p>If we’re able to detect any significant differences in the ANOVA, we are then interested in knowing exactly which levels of a given factor differ from one another, and which do not. Remember that a significant p value in the F-test we just ran would reject the null hypothesis where the means were the same across all factor levels, but not identify which were different from each other. Here, we have two factors with their own coefficients:</p>
<p><strong>ORIENTATION FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Orientation_{Horizontal}\)</span> = 0 (the baseline of the factor ORIENTATION)</p></li>
<li><p><span class="math inline">\(Orientation_{Vertical}\)</span>= <span class="math inline">\(-11.7^{***}\)</span></p></li>
</ul>
<p>Those coefficients suggest that the species richness is lowest in vertical habitats.</p>
<p><strong>COPPER FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Copper_{High}\)</span> = 0 (the baseline of the factor COPPER)</p></li>
<li><p><span class="math inline">\(Copper_{Low}\)</span> = <span class="math inline">\(0.4^{NS}\)</span><br>
</p></li>
<li><p><span class="math inline">\(Copper_{None}\)</span> = <span class="math inline">\(14.2^{***}\)</span></p></li>
</ul>
<p>Those coefficients suggest that the species richness is highest in absence of Copper enrichment (level <span class="math inline">\(None\)</span> &gt; <span class="math inline">\(High\)</span>). But as the level <span class="math inline">\(High\)</span> is the baseline, we can’t detect whether the levels <span class="math inline">\(None\)</span> and <span class="math inline">\(Low\)</span> are different or not. So, we must change the level baseline and re-analyse the coefficients of the model to detect difference or not between those two factor levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the COPPER factor baseline: put 'Low' level as the baseline</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>datasessile<span class="sc">$</span>Copper2<span class="ot">&lt;-</span><span class="fu">relevel</span>(datasessile<span class="sc">$</span>Copper,<span class="at">ref=</span><span class="st">"Low"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># New model formulation</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">lm</span>(Richness<span class="sc">~</span>Copper2<span class="sc">*</span>Orientation,<span class="at">data=</span>datasessile)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Richness ~ Copper2 * Orientation, data = datasessile)

Residuals:
   Min     1Q Median     3Q    Max 
-5.700 -1.825  0.350  1.400 11.400 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       55.800      0.930  60.003  &lt; 2e-16 ***
Copper2High                       -0.400      1.315  -0.304  0.76218    
Copper2None                       13.800      1.315  10.493 1.21e-14 ***
Orientationvertical                3.400      1.315   2.585  0.01246 *  
Copper2High:Orientationvertical  -15.100      1.860  -8.119 6.35e-11 ***
Copper2None:Orientationvertical   -7.100      1.860  -3.817  0.00035 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.941 on 54 degrees of freedom
Multiple R-squared:  0.8986,    Adjusted R-squared:  0.8893 
F-statistic: 95.76 on 5 and 54 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now, the coefficients of the COPPER factor are: <strong>COPPER FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Copper_{Low}\)</span> = 0 (the new baseline of the factor COPPER)</p></li>
<li><p><span class="math inline">\(Copper_{High}\)</span> = <span class="math inline">\(-0.4^{NS}\)</span></p></li>
<li><p><span class="math inline">\(Copper_{None}\)</span> = <span class="math inline">\(13.8^{***}\)</span></p></li>
</ul>
<p>Those coefficients suggest that the species richness is highest in absence of Copper enrichment (<span class="math inline">\(None\)</span> &gt; <span class="math inline">\(Low\)</span>). In conclusion, <span class="math inline">\(Richness_{Copper_{High}}\)</span> = <span class="math inline">\(Richness_{Copper_{Low}}\)</span>&lt; <span class="math inline">\(Richness_{Copper_{None}}\)</span></p>
<p><strong>Model explanation: R²</strong></p>
<p>Let’s determine the part of the <span class="math inline">\(Y\)</span> variation explained by the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² of the model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Richness ~ Copper * Orientation, data = datasessile)

Residuals:
   Min     1Q Median     3Q    Max 
-5.700 -1.825  0.350  1.400 11.400 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      55.400      0.930  59.573  &lt; 2e-16 ***
CopperLow                         0.400      1.315   0.304    0.762    
CopperNone                       14.200      1.315  10.797 4.22e-15 ***
Orientationvertical             -11.700      1.315  -8.896 3.63e-12 ***
CopperLow:Orientationvertical    15.100      1.860   8.119 6.35e-11 ***
CopperNone:Orientationvertical    8.000      1.860   4.301 7.17e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.941 on 54 degrees of freedom
Multiple R-squared:  0.8986,    Adjusted R-squared:  0.8893 
F-statistic: 95.76 on 5 and 54 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this output, the adjusted R² is equal to 0.8893, which means that about 89% of the variance of species richness is explained by the model.</p>
</section>
<section id="model-validation-check-the-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="model-validation-check-the-assumptions">Model validation: Check the assumptions</h3>
<p><em>See part III/.</em></p>
</section>
</section>
<section id="ancova" class="level2">
<h2 class="anchored" data-anchor-id="ancova">2) ANCOVA</h2>
<section id="introduction-2" class="level3">
<h3 class="anchored" data-anchor-id="introduction-2">INTRODUCTION</h3>
<p>ANCOVA (i.e.&nbsp;Analysis of Covariance) is a statistical technique widely used in various disciplines like the previous analysis presented, ANOVA and the linear regression . It is used to model the relationship between a quantitative dependent variable Y, called the response variable, and several independant variable X1, X2… called explanatory variables or predictors). The difference between ANOVA and ANCOVA, is that the predictors can be <strong>quantitative</strong> and <strong>qualitative</strong>. For example, we could use an ANCOVA to test whether the size (continuous), sex (categorical), reproductive status (categorical), habitat (categorical), age (continuous) of a sperm whale are good predictors of its weight (the response variable). As the ANCOVA includes quantitative and categorical independent variables, this technique represents between linear regression and ANOVA.</p>
<p>We can give an example and write the model with one continuous and one categorical independent variables, the model takes the form: <span class="math display">\[ Y_{ij} = \mu + \alpha_{i}+ \beta.X_{ij}+\gamma_{i}.X_{ij}+\epsilon_{ij}\]</span></p>
<ul>
<li><p><span class="math inline">\(\mu\)</span> is the overall mean, the intercept</p></li>
<li><p><span class="math inline">\(\alpha_{i}\)</span> is the effect of the modality i of the categorical variable)</p></li>
<li><p><span class="math inline">\(\beta\)</span> is the slope (amount of change in Y for each unit of the quantitative covariate), it is the effect of the quantitative variable<span class="math inline">\(X_{j}\)</span></p></li>
<li><p><span class="math inline">\(\gamma_{i}\)</span> is the interactive coefficient between the modality i of the factor and the quantitative covariate</p></li>
<li><p><span class="math inline">\(\epsilon_{ij}\)</span> is the error term (residuals). The inclusion of the error term <span class="math inline">\(\epsilon_{ij}\)</span>, also called the stochastic part of the model, that makes the model statistical rather than mathematical. The error term is drawn from a statistical distribution that integers the random variability in the response. In standard linear model, this is assumed to be <strong>a normal (Gaussian) distribution</strong> with parameter 0 et <span class="math inline">\(\sigma^2\)</span>, avec <span class="math inline">\(\sigma\)</span> l’écart type.</p></li>
</ul>
</section>
<section id="ancova-example" class="level3">
<h3 class="anchored" data-anchor-id="ancova-example">ANCOVA EXAMPLE</h3>
</section>
<section id="dataset-presentation-and-objectives-of-the-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="dataset-presentation-and-objectives-of-the-analysis-1">Dataset presentation and objectives of the analysis</h3>
<p>For this example, we will use data from a study performed in 1994 that concerns the fly, <em>Anatalanta aptera</em>, a wingless fly living in subantarctic islands, particularly in sea bird colonies. 320 individuals has been collected in the Crozet Island, living either on the coast or inland (i.e.&nbsp;mountain landscape). The goal of that study is to determine which variables may explain the dry weight of <em>Anatalanta aptera</em>. Dry weight represents total organic and inorganic matter in the tissue and is more accurate than measuring wet weight (using dry weight as a measure of animal growth tends to be more reliable). Then, the following life-history traits have been measured to try and explain the response variable Y= Dry weight. Those are the predictors.</p>
<ul>
<li><strong>Sex</strong> = the sex of a given individual, categorical variable<br>
</li>
<li><strong>Habitat</strong> = the habitat of a given individual(‘Coast’ or ‘Inland’), categorical variable<br>
</li>
<li><strong>Length</strong> = the length of a given individual, continuous variable<br>
</li>
<li><strong>Width</strong> = the width of a given individual, continuous variable<br>
</li>
<li><strong>WaterContent</strong> = the water content of a given individual, continuous variable<br>
</li>
<li><strong>FatContent</strong> = the fat content of a given individual, continuous variable<br>
</li>
<li><strong>DryWeight</strong> = the dry weight of a given individual, continuous variable</li>
</ul>
<p>The underlying question for this research is simple; do variables drive the dry weight in <em>Anatalanta aptera</em>? Predictors being continuous and categorical, we are gonna perform an <strong>ANCOVA</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset import</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dataFly <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"FlyWeight.txt"</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We must check whether the variables are correctly imported, i.e.&nbsp;they are of the right type. Sex and Habitat are ‘chr’, so we must transform them into factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dataFly<span class="sc">$</span>Sex<span class="ot">&lt;-</span><span class="fu">as.factor</span>(dataFly<span class="sc">$</span>Sex)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dataFly<span class="sc">$</span>Habitat<span class="ot">&lt;-</span><span class="fu">as.factor</span>(dataFly<span class="sc">$</span>Habitat)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dataFly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   320 obs. of  8 variables:
 $ FlyNumber   : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Sex         : Factor w/ 2 levels "Female","Male": 2 2 2 2 2 2 2 2 2 2 ...
 $ Habitat     : Factor w/ 2 levels "Coast","Inland": 1 1 1 1 1 1 1 1 1 1 ...
 $ Length      : num  1.4 1.55 1.52 1.44 1.77 1.69 1.79 1.65 1.58 1.62 ...
 $ Width       : num  1.24 1.39 1.26 1.18 1.46 1.41 1.46 1.41 1.32 1.4 ...
 $ WaterContent: num  5.9 7.1 6.8 5.3 8.2 7.6 8.2 7.2 6.5 8.8 ...
 $ FatContent  : num  0.3 0.2 0 0.2 0.1 0 0 0.3 0.1 0.2 ...
 $ DryWeight   : num  2.2 3 2.2 2 3.1 2.6 2.8 3.1 2.2 2.6 ...</code></pre>
</div>
</div>
</section>
<section id="data-exploration-1" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-1">Data exploration</h3>
<p><em>See part 1).</em></p>
</section>
<section id="statistical-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis-1">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>For the statistical modelling, we first analyse the full model (model containing all independent variables to test). We will test the effects of the main effects (3 continuous and 2 categorical independent variables) and their interactions (by excluding interactions between quantitative independent variables). To get the candidate model we will perform a <strong>backward selection</strong>. It consist in testing the full model first, then we drop the least significant interaction, we perform this step until all the remaining interaction effect are significant. We do the qsame approach for the main effect. By following these two steps, candidate model is found. We use the function drop (F test) to test the significant at each step and choose the lest significant effect. Keep in mind that if a variable is involved in an interaction effect you must keep it as a main effect in the model.</p>
<p><strong>Backward selection</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Full model</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(DryWeight<span class="sc">~</span> Sex <span class="sc">+</span> Habitat <span class="sc">+</span> Width <span class="sc">+</span> WaterContent <span class="sc">+</span> FatContent <span class="sc">+</span> Sex<span class="sc">:</span>Habitat <span class="sc">+</span> Sex<span class="sc">:</span>Width <span class="sc">+</span> Habitat<span class="sc">:</span>Width <span class="sc">+</span> Sex<span class="sc">:</span>WaterContent <span class="sc">+</span> Habitat<span class="sc">:</span>WaterContent <span class="sc">+</span> Sex<span class="sc">:</span>FatContent <span class="sc">+</span> Habitat<span class="sc">:</span>FatContent </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>        ,<span class="at">data=</span>dataFly)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Then we check for significance</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
DryWeight ~ Sex + Habitat + Width + WaterContent + FatContent + 
    Sex:Habitat + Sex:Width + Habitat:Width + Sex:WaterContent + 
    Habitat:WaterContent + Sex:FatContent + Habitat:FatContent
                     Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
&lt;none&gt;                            83.710 -403.11                      
Sex:Habitat           1    0.1683 83.878 -404.47  0.6172 0.4326813    
Sex:Width             1    0.0076 83.717 -405.08  0.0277 0.8678741    
Habitat:Width         1    3.0401 86.750 -393.69 11.1492 0.0009443 ***
Sex:WaterContent      1    0.0105 83.720 -405.07  0.0385 0.8445863    
Habitat:WaterContent  1    3.3319 87.042 -392.62 12.2195 0.0005426 ***
Sex:FatContent        1    0.0033 83.713 -405.10  0.0122 0.9122382    
Habitat:FatContent    1    0.9549 84.665 -401.48  3.5022 0.0622392 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From this significance output, we will exclude the interaction that is ‘the less significant’ = ‘Sex:Fat Content’</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
DryWeight ~ Sex + Habitat + Width + WaterContent + FatContent + 
    Sex:Habitat + Sex:Width + Habitat:Width + Sex:WaterContent + 
    Habitat:WaterContent + Habitat:FatContent
                     Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
&lt;none&gt;                            83.713 -405.10                      
Sex:Habitat           1    0.1673 83.880 -406.46  0.6156 0.4332877    
Sex:Width             1    0.0061 83.719 -407.07  0.0226 0.8805490    
Habitat:Width         1    3.0926 86.806 -395.49 11.3783 0.0008380 ***
Sex:WaterContent      1    0.0095 83.722 -407.06  0.0349 0.8518861    
Habitat:WaterContent  1    3.4666 87.180 -394.11 12.7546 0.0004119 ***
Habitat:FatContent    1    0.9516 84.665 -403.48  3.5013 0.0622693 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From this new significance list, we will exclude the interaction that is ‘the less significant’… and so on.</p>
<p>After the non significant interaction deletions, the model contains only 2 significant interactions = ‘Habitat:Width’ and ‘Habitat:WaterContent’. That means that the main effects ‘Habitat’, ‘Width’ and ‘WaterContent’ are maintained in the model as included in significant interactions.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
DryWeight ~ Sex + Habitat + Width + WaterContent + FatContent + 
    Habitat:Width + Habitat:WaterContent
                     Df Sum of Sq    RSS     AIC F value   Pr(&gt;F)    
&lt;none&gt;                            85.017 -408.15                     
Sex                   1    0.5309 85.547 -408.16  1.9482 0.163775    
FatContent            1    0.7347 85.751 -407.40  2.6961 0.101602    
Habitat:Width         1    2.5775 87.594 -400.59  9.4592 0.002287 ** 
Habitat:WaterContent  1    3.5343 88.551 -397.12 12.9705 0.000368 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From the previous listing, we decide to first exclude the ‘Sex’ factor.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
DryWeight ~ Habitat + Width + WaterContent + FatContent + Habitat:Width + 
    Habitat:WaterContent
                     Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
&lt;none&gt;                            85.547 -408.16                      
FatContent            1    0.6398 86.187 -407.78  2.3409 0.1270272    
Habitat:Width         1    2.6522 88.200 -400.39  9.7040 0.0020089 ** 
Habitat:WaterContent  1    4.0859 89.633 -395.23 14.9495 0.0001343 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>As the ‘FatContent’ is still non significant, we exclude this main effect and we obtain the ‘Candidate Model’. This candidate model contains three main effects (we are keeping the main effect because the variables have interaction effects) and two interactions.</p>
<p><strong>Candidate model</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(DryWeight<span class="sc">~</span> Habitat<span class="sc">+</span> Width <span class="sc">+</span> WaterContent <span class="sc">+</span> Habitat<span class="sc">:</span>Width <span class="sc">+</span> Habitat<span class="sc">:</span>WaterContent,<span class="at">data=</span>dataFly)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
DryWeight ~ Habitat + Width + WaterContent + Habitat:Width + 
    Habitat:WaterContent
                     Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
&lt;none&gt;                            86.187 -407.78                      
Habitat:Width         1    2.7963 88.983 -399.56  10.188 0.0015570 ** 
Habitat:WaterContent  1    4.2441 90.431 -394.39  15.462 0.0001036 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>To understand how main effects and interactions influence the dry weight of the flies, we will analyse the coefficients of the model.</p>
<p><strong>Model’s coefficients analysis</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DryWeight ~ Habitat + Width + WaterContent + Habitat:Width + 
    Habitat:WaterContent, data = dataFly)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.86592 -0.25639 -0.01119  0.23329  1.91099 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 0.05228    0.66459   0.079 0.937354    
HabitatInland              -2.43270    0.78331  -3.106 0.002072 ** 
Width                       0.21761    0.64964   0.335 0.737865    
WaterContent                0.31332    0.04925   6.362 7.02e-10 ***
HabitatInland:Width         2.34365    0.73427   3.192 0.001557 ** 
HabitatInland:WaterContent -0.21378    0.05437  -3.932 0.000104 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5239 on 314 degrees of freedom
Multiple R-squared:  0.6129,    Adjusted R-squared:  0.6067 
F-statistic: 99.42 on 5 and 314 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This output presents a table detailing the coefficients of the model with coefficients associated with each significant main effect and interaction. Remind that for a factor, one level is called ‘the baseline’ meaning that its coefficient is 0 (also called the reference level). From this table, coefficients are:</p>
<p><strong>HABITAT FACTOR</strong></p>
<ul>
<li><p><span class="math inline">\(Habitat_{Coast}\)</span> = 0 (the baseline of the factor Habitat)</p></li>
<li><p><span class="math inline">\(Habitat_{Inland}\)</span> = <span class="math inline">\(-2.43^{**}\)</span></p></li>
</ul>
<p><strong>WIDTH COVARIATE</strong></p>
<ul>
<li><span class="math inline">\(\beta_{Width}\)</span> = <span class="math inline">\(0.21^{NS}\)</span></li>
</ul>
<p><strong>WATER CONTENT COVARIATE</strong></p>
<ul>
<li><span class="math inline">\(\beta_{WaterContent}\)</span> = <span class="math inline">\(0.31^{***}\)</span></li>
</ul>
<p><strong>HABITAT:WIDTH INTERACTION</strong></p>
<ul>
<li><span class="math inline">\(\beta_{Width_{Inland}}\)</span> = <span class="math inline">\(2.34^{***}\)</span></li>
</ul>
<p><strong>HABITAT:WATER CONTENT INTERACTION</strong></p>
<ul>
<li><span class="math inline">\(\beta_{WaterContent_{Inland}}\)</span> = <span class="math inline">\(- 0.21^{***}\)</span></li>
</ul>
<p><strong>Model explanation: R²</strong></p>
<p>You can determine the part of the <span class="math inline">\(Y\)</span> variation explained by your model. See the output of the model summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#to get R² of the model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DryWeight ~ Habitat + Width + WaterContent + Habitat:Width + 
    Habitat:WaterContent, data = dataFly)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.86592 -0.25639 -0.01119  0.23329  1.91099 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 0.05228    0.66459   0.079 0.937354    
HabitatInland              -2.43270    0.78331  -3.106 0.002072 ** 
Width                       0.21761    0.64964   0.335 0.737865    
WaterContent                0.31332    0.04925   6.362 7.02e-10 ***
HabitatInland:Width         2.34365    0.73427   3.192 0.001557 ** 
HabitatInland:WaterContent -0.21378    0.05437  -3.932 0.000104 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5239 on 314 degrees of freedom
Multiple R-squared:  0.6129,    Adjusted R-squared:  0.6067 
F-statistic: 99.42 on 5 and 314 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this output, you get that the adjusted R² = 0.6067. That means that about 61% of the variance of the dry weight of the flies is explained by its relationship with their habitat, water content and width and the interactions between these predictors.</p>
<p><strong>Model expression</strong></p>
<p>You can write the model with the coefficient. Be careful: you have a different expression for each modality. <span class="math display">\[ Dry\:Weight = 0.05\:+\:(Habitat_{Coast} = 0 \:;\:Habitat_{Inland} = -2.43^{**}) \]</span> <span class="math display">\[ +\:0.21^{NS}. Width\:+\:0.31^{***}. Water\:Content \]</span> <span class="math display">\[ + (if\:Habitat=Inland:\:+ 2.34^{***}. Width\: -\: 0.21^{***}.Water\:Content)\]</span></p>
<p><strong>Biological interpretation</strong></p>
<p>Before drawing any conclusions from your result, you have to validate the model (part model validation). The assumptions of ANCOVA are the same as for all general linear models (i.e.&nbsp;regressions, ANOVAs), you have to check <em>independence of residuals</em>, <em>normality of residuals</em> and <em>homogeneity of variances</em>.</p>
</section>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">3) REGRESSION</h2>
<section id="introduction-3" class="level3">
<h3 class="anchored" data-anchor-id="introduction-3">INTRODUCTION</h3>
<p>You have certainly used the technique of regression many times in various exercises. It is used to model the relationship between a <strong>quantitative dependent variable</strong> <span class="math inline">\(Y\)</span> (the <strong>response</strong>, that is continuous, and one or several <strong>explanatory quantitative variable(s)</strong> (the <strong>predictors</strong>, that are independant). <span class="math inline">\(X_{1}\)</span>,<span class="math inline">\(X_{2}\)</span>…<span class="math inline">\(X_{p}\)</span>. For example, we could use a linear regression to test whether the weight of a dog (i.e.&nbsp;the explanatory variable) is a good predictor of its lifespan (the response variable).</p>
</section>
<section id="model-writing" class="level3">
<h3 class="anchored" data-anchor-id="model-writing">MODEL WRITING</h3>
<p>The general model is written: <span class="math display">\[ Y_{i} = \alpha + \beta_{j}.X{ij}+ \epsilon_{i}\]</span> <span class="math display">\[ i=1,...,n\]</span> <span class="math display">\[ j=1,...,p\]</span> The inclusion of the error term <span class="math inline">\(\epsilon\)</span>, also called the stochastic part of the model, makes the model statistical rather than mathematical. The error term is drawn from a statistical distribution that integers the random variability in the response. In standard linear regression, this is assumed to be a <strong>normal (Gaussian) distribution</strong>.</p>
<p>There are two different regression types:</p>
<p>• the <em>simple linear regression</em> includes a single <span class="math inline">\(X\)</span> in your analysis. The model takes the form: <span class="math display">\[ Y = \alpha + \beta.X + \epsilon \]</span> where <span class="math inline">\(\alpha\)</span> is the intercept (value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> = 0), <span class="math inline">\(\beta\)</span> is the regression slope (amount of change in <span class="math inline">\(Y\)</span> for each unit of <span class="math inline">\(X\)</span>), and <span class="math inline">\(\epsilon\)</span> is the error term (i.e.&nbsp;residuals).</p>
<p>• the <em>multiple linear regression</em> includes several <span class="math inline">\(X_{s}\)</span> in your analysis. The model takes the form: <span class="math display">\[ Y_{i} = \alpha + \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip}+ \epsilon_{i}\]</span></p>
</section>
<section id="regression-example" class="level3">
<h3 class="anchored" data-anchor-id="regression-example">REGRESSION EXAMPLE:</h3>
</section>
<section id="dataset-presentation-and-objectives-of-the-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="dataset-presentation-and-objectives-of-the-analysis-2">Dataset presentation and objectives of the analysis</h3>
<p>This data was published in ‘Latitudinal variation in light levels drives human visual system size’. Eiluned Pearce and Robin Dunbar. Biol. Lett. published online 27 July 2011 (<a href="http://doi:10.1098/rsbl.2011.0570" class="uri">http://doi:10.1098/rsbl.2011.0570</a>). Ambient light levels influence visual system size in birds and primates and Pearce and Dunbar (2011) argue that the same is true for humans. Using linear regression techniques, they want to test the relationship between (absolute) latitude and human orbital volume, an index of eyeball size. Pearce and Dunbar (2011) measured cranial capacity (CC), orbital volume and foramen magnum (FM) dimensions for 73 healthy adult crania from the Oxford University Museum of Natural History and Duckworth Collection, University of Cambridge.</p>
<p>List of the variables: - <strong>MeanOrbitalVolume</strong> = Index for eyeball size, continuous variable (the response)</p>
<ul>
<li><p><strong>CranialCapacity</strong> = measure of the volume of the interior of the cranium, continuous variable</p></li>
<li><p><strong>Minimum_Illuminance</strong> = log scale of the minimum of illuminance of the sample site, continuous variable</p></li>
<li><p><strong>Minimum_Temperature</strong> = Minimum temperature of the sample site, continuous variable</p></li>
<li><p><strong>AbsoluteLatitude</strong> = Absolute values of latitude of the sample, continuous variable</p></li>
<li><p><strong>Population</strong> = country/region of the sample, Categorical variable</p></li>
</ul>
<p>The response variable is mean orbital volume and the rest are assumed covariates. The Population variable is a descriptor of the samples, so not included in the modelling. Each value for orbital volume represents the mean of 3 replicate measurements from the same skull.</p>
<p>Question: <em>which covariates drive the mean orbital volume?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset import</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dataHVS <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"HumanVisualSystem.txt"</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Population<span class="ot">&lt;-</span><span class="fu">as.factor</span>(dataHVS<span class="sc">$</span>Population)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dataHVS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   55 obs. of  6 variables:
 $ Population         : Factor w/ 12 levels "Australia","CanaryIslands",..: 8 8 8 2 2 2 2 11 11 11 ...
 $ AbsoluteLatitude   : num  1.33 5.42 5.42 28.51 28.51 ...
 $ CranialCapacity    : int  1200 1300 1100 1300 1420 1400 1620 1340 1480 1280 ...
 $ Minimum_Illuminance: num  109648 104713 104713 64565 64565 ...
 $ Minimum_Temperature: num  26.7 24.4 24.4 14.4 14.4 ...
 $ MeanOrbitalVolume  : num  22.5 21 22 20.5 25 25.5 27.6 24.5 24 25.3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for presence of missing values</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(dataHVS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Population    AbsoluteLatitude     CranialCapacity Minimum_Illuminance 
                  0                   0                   0                   0 
Minimum_Temperature   MeanOrbitalVolume 
                  0                   0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#There is no missing value.</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Simplify the names of the variables</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Pop<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>Population</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Lat<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>AbsoluteLatitude</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Capacity<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>CranialCapacity</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Illumi<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>Minimum_Illuminance</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Temp<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>Minimum_Temperature</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>dataHVS<span class="sc">$</span>Response<span class="ot">&lt;-</span>dataHVS<span class="sc">$</span>MeanOrbitalVolume      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-exploration-2" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-2">Data exploration</h3>
<p><em>See part 1).</em></p>
</section>
<section id="statistical-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis-2">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>You need to first analyse the full model containing all the independent variables in order to test their significance (i.e.&nbsp;see if they are relevant in the modelling) and decide whether you keep them or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(Response<span class="sc">~</span>Lat<span class="sc">+</span>Capacity,<span class="at">data=</span>dataHVS)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Then we check for significance, here with an F-Test</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Response ~ Lat + Capacity
         Df Sum of Sq    RSS    AIC F value   Pr(&gt;F)   
&lt;none&gt;                236.18 86.150                    
Lat       1    48.830 285.01 94.486  10.751 0.001863 **
Capacity  1    28.079 264.26 90.328   6.182 0.016155 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Look at the test statistic, the F value and its associated p-value (Pr). They show that both covariates are significant. So here, no need to go further, because <strong>the full model is the candidate model</strong>. To understand how covariates influence the response (the orbital volume), we analyse coefficients of the model (i.e.&nbsp;the <span class="math inline">\(\beta_{j}\)</span>).</p>
<p><strong>Model’s coefficients analysis</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Response ~ Lat + Capacity, data = dataHVS)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3661 -1.5412  0.0534  1.6091  4.4284 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.406367   3.063999   5.028 6.24e-06 ***
Lat          0.048910   0.014917   3.279  0.00186 ** 
Capacity     0.005836   0.002347   2.486  0.01616 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.131 on 52 degrees of freedom
Multiple R-squared:  0.3701,    Adjusted R-squared:  0.3459 
F-statistic: 15.28 on 2 and 52 DF,  p-value: 6.034e-06</code></pre>
</div>
</div>
<p>This table detailed the coefficients of the model with coefficients associated with each covariate. You can deduce the candidate model: <span class="math display">\[ Orbital\:Volume = 15.4 \:+\: 0.04.Latitude\: +\: 0.005.Cranial\:Capacity  \]</span> Those coefficients suggest that the orbital volume increases with the latitude (in relation with Temperature and Illuminance) and the cranial capacity.</p>
<p><strong>Model explanation: R²</strong></p>
<p>Let’s determine the part of the <span class="math inline">\(Y\)</span> variation explained by your model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² of the model</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Response ~ Lat + Capacity, data = dataHVS)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3661 -1.5412  0.0534  1.6091  4.4284 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.406367   3.063999   5.028 6.24e-06 ***
Lat          0.048910   0.014917   3.279  0.00186 ** 
Capacity     0.005836   0.002347   2.486  0.01616 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.131 on 52 degrees of freedom
Multiple R-squared:  0.3701,    Adjusted R-squared:  0.3459 
F-statistic: 15.28 on 2 and 52 DF,  p-value: 6.034e-06</code></pre>
</div>
</div>
<p>You can read the adjusted R² = 0.345. That means that about 35% of the variance of the Orbital Volume is explained by its relationship with the Latitude (Temperature &amp; Illuminance) and the Cranial Capacity.</p>
<p><strong>Model validation</strong>: check the assumptions</p>
<p><em>See III/.</em></p>
<p>You must want to have the best visual representation of your model !</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set your variables on each axis</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dataHVS<span class="sc">$</span>Capacity</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> dataHVS<span class="sc">$</span>Lat</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> dataHVS<span class="sc">$</span>Response</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remind the candidate model with these</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(z<span class="sc">~</span>x<span class="sc">+</span>y)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a grid from the x and y values (min to max) and predict values for every point: this is the base of the regression plane</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>grid.lines <span class="ot">=</span> <span class="dv">40</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>x.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(x), <span class="fu">max</span>(x), <span class="at">length.out =</span> grid.lines)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(y), <span class="fu">max</span>(y), <span class="at">length.out =</span> grid.lines)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>( <span class="at">x =</span> x.pred, <span class="at">y =</span> y.pred)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>z.pred <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">predict</span>(mod1, <span class="at">newdata =</span> xy),<span class="at">nrow =</span> grid.lines, <span class="at">ncol =</span> grid.lines)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the fitted points for droplines to the surface</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>fitpoints <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot with regression plane, in the format that you like</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter3D</span>(x, y, z, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">1</span>,<span class="at">colvar =</span> <span class="cn">NULL</span>, <span class="at">col=</span><span class="st">"red"</span>, </span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>          <span class="at">theta =</span> <span class="dv">30</span>, <span class="at">phi =</span> <span class="dv">10</span>, <span class="at">bty=</span><span class="st">"b"</span>,</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">"Cranial Capacity"</span>, <span class="at">ylab =</span> <span class="st">"Latitude"</span>, <span class="at">zlab =</span> <span class="st">"Response"</span>,  </span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">surf =</span> <span class="fu">list</span>(<span class="at">x =</span> x.pred, <span class="at">y =</span> y.pred, <span class="at">z =</span> z.pred,  </span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>          <span class="at">facets =</span> <span class="cn">TRUE</span>, <span class="at">fit =</span> fitpoints, <span class="at">col=</span><span class="fu">ramp.col</span> (<span class="at">col =</span> <span class="fu">c</span>(<span class="st">"dodgerblue3"</span>,<span class="st">"seagreen2"</span>), <span class="at">n =</span> <span class="dv">300</span>, <span class="at">alpha=</span><span class="fl">0.9</span>),           <span class="at">border=</span><span class="st">"black"</span>), <span class="at">main =</span> <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>So ! Does it look cool to you ?</p>
</section>
</section>
</section>
<section id="ii-generalized-linear-models" class="level1">
<h1>II/ GENERALIZED LINEAR MODELS</h1>
<p>In absence of <strong>normality of residuals</strong> and <strong>homoscedasticity</strong> only, you may use Generalized Linear Models. You will need a <strong>link function</strong> to ‘force’ the linear relationship between Y and the independant variables (see examples).</p>
<section id="binomial-law" class="level2">
<h2 class="anchored" data-anchor-id="binomial-law">1) Binomial Law</h2>
<section id="introduction-4" class="level3">
<h3 class="anchored" data-anchor-id="introduction-4">INTRODUCTION</h3>
<p>X is a binary variable with two modalities: 1 (success) and 0 (failure). The probability of success is: <span class="math display">\[ P(X = 1) = \pi \]</span> Then, Y, a variable corresponding to N randoms and independent draws of X, follows a binomial law whose parameters are N and <span class="math inline">\(\pi\)</span>.</p>
<p>The density function of Y is: <span class="math display">\[ f(y;\pi)=\binom{N}{y}.\pi^{y}.(1-\pi)^{(N-y)}\]</span> The expectancy and the variance of Y are: <span class="math display">\[E(Y)=N.\pi\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:var(Y)=N.\pi.(1-\pi)\]</span></p>
<p>In the generalized model, the link function for Y is the function “logit” such that: <span class="math display">\[logit(\mu_{y})= \alpha+ \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip} = \eta \]</span> Thus, the predicted value is: <span class="math display">\[\mu_{y}= \frac {e^{\eta}}{1+e^{\eta}} \]</span></p>
</section>
<section id="binomial-law-example" class="level3">
<h3 class="anchored" data-anchor-id="binomial-law-example">BINOMIAL LAW EXAMPLE</h3>
</section>
<section id="dataset-presentation-and-objectives-of-the-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="dataset-presentation-and-objectives-of-the-analysis-3">Dataset presentation and objectives of the analysis</h3>
<p>Let’s apply this on the example of the dataset “badger.txt” from the book: Zuur et al.&nbsp;2009 “Mixed effects models and extensions in ecology with R” - Springer. This dataset comes from a survey carried out on 36 farms in South-West England over 8 consecutive seasons running from autumn 2003 to summer 2005. It contains 277 rows and the columns:</p>
<ul>
<li><p><strong>year</strong>: Calendar year</p></li>
<li><p><strong>season</strong>: spring, summer, autumn, winter</p></li>
<li><p><strong>farm_code</strong>: farm identifier</p></li>
<li><p><strong>survey</strong>: which of the 8 survey occasions (i.e.&nbsp;a time indicator)</p></li>
<li><p><strong>badger_activity</strong>: presence-absence of signs of badgers activity</p></li>
<li><p><strong>N_setts_in_fields</strong>: number of badger ‘homes’ observed</p></li>
<li><p><strong>N_buildings</strong>: number of buildings on farm</p></li>
<li><p><strong>N_cattle_in_buildings</strong>: number of cattle housed in the building yard</p></li>
<li><p><strong>accessible_feed_store_present</strong>: presence-absence of a feed’s store in farm</p></li>
<li><p><strong>accessible_cattle_house_present</strong>:presence-absence of a direct access to cattle house</p></li>
<li><p><strong>accessible_feed_present</strong>: presence-absence of accessible feed on farm</p></li>
<li><p><strong>grass_silage</strong>: presence-absence of grass_silage</p></li>
<li><p><strong>cereal_silage</strong>: presence-absence of cereal_silage</p></li>
<li><p><strong>hay_straw</strong>: presence-absence of hay_straw</p></li>
<li><p><strong>cereal_grains</strong>: presence-absence of cereal_grains</p></li>
<li><p><strong>concentrates</strong>: presence-absence of concentrates</p></li>
<li><p><strong>sugar_beet</strong>: presence-absence of sugar beet</p></li>
<li><p><strong>molasses</strong>: presence-absence of molasses</p></li>
</ul>
<p>For the example, the binary variable that will be explained is the badger activity and any other variables are taken as explanatory variables. The objective is to find a model that predict the occurrence of signs of badger activity on farms in order to find a way to reduce the rates of badgers’ visits to farms. This objective is motivated by the numerous transmissions of bovine tuberculosis from badgers to cattle.</p>
<p>Let’s import the dataset and perform a binomial generalized linear model.</p>
</section>
<section id="data-exploration-3" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-3">Data exploration</h3>
<p><em>See part I/1).</em></p>
</section>
<section id="statistical-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis-3">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>We will use a backward selection with the most complete model, considered here, for a question of simplicity, as the model with all the explanatory variables but no interactions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's define the model with the function "glm" with the family "binomial" and the link function "logit" </span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">glm</span>(Activity<span class="sc">~</span>N_setts <span class="sc">+</span> N_buildings <span class="sc">+</span> N_cattle <span class="sc">+</span> season <span class="sc">+</span> feed_store <span class="sc">+</span> cattle_house <span class="sc">+</span> feed <span class="sc">+</span> grass <span class="sc">+</span> cereal <span class="sc">+</span> straw <span class="sc">+</span> grains <span class="sc">+</span> concen <span class="sc">+</span> sugar,<span class="at">data=</span>dataBadger, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We can use then the function drop1 to check the significance</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"Chi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Activity ~ N_setts + N_buildings + N_cattle + season + feed_store + 
    cattle_house + feed + grass + cereal + straw + grains + concen + 
    sugar
             Df Deviance    AIC    LRT  Pr(&gt;Chi)    
&lt;none&gt;            180.19 212.19                     
N_setts       1   214.98 244.98 34.782 3.687e-09 ***
N_buildings   1   180.32 210.32  0.127   0.72116    
N_cattle      1   184.41 214.41  4.217   0.04003 *  
season        3   181.15 207.15  0.955   0.81222    
feed_store    1   183.73 213.73  3.532   0.06019 .  
cattle_house  1   181.23 211.23  1.033   0.30942    
feed          1   182.53 212.53  2.338   0.12629    
grass         1   180.22 210.22  0.021   0.88467    
cereal        1   180.76 210.76  0.565   0.45242    
straw         1   181.42 211.42  1.223   0.26869    
grains        1   180.33 210.33  0.132   0.71641    
concen        1   180.21 210.21  0.019   0.89129    
sugar         1   181.57 211.57  1.380   0.24011    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Some of the coefficient are not significant because their p values are under 0.05 so we will suppress them and test the new model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Activity ~ N_setts + N_cattle
         Df Deviance    AIC    LRT Pr(&gt;Chi)    
&lt;none&gt;        191.84 197.84                    
N_setts   1   240.81 244.81 48.969  2.6e-12 ***
N_cattle  1   195.62 199.62  3.779   0.0519 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This time, all of the variables are significant. Let’s check the coefficient :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Activity ~ N_setts + N_cattle, family = binomial(link = logit), 
    data = dataBadger)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.638947   0.408344  -8.911  &lt; 2e-16 ***
N_setts      0.268288   0.042921   6.251 4.09e-10 ***
N_cattle     0.003486   0.001766   1.974   0.0483 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 246.17  on 277  degrees of freedom
Residual deviance: 191.84  on 275  degrees of freedom
AIC: 197.84

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>All the coefficients are significant.</p>
<p>The candidate model is: <span class="math display">\[  logit(Presence\:of\:badger\:activity) = - 3.64 0.27*Number\:of\:Setts\: +\: 0.004* Number\:of\:Cattles \]</span></p>
<p><strong>Model explanation</strong></p>
<p>However there is no <span class="math inline">\(R^2\)</span> in Generalized Linear Models, we can still calculate a $pseudo:R^2* to estimate how far the candidate model is from the null model by determining the distance between deviance of the null model and the residual deviance of the candidate model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate of deviance explained</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>(mod2<span class="sc">$</span>null.deviance<span class="sc">-</span>mod2<span class="sc">$</span>deviance)<span class="sc">/</span>mod2<span class="sc">$</span>null.deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2207131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Some others estimates of deviance explained - package 'rcompanion' =&gt; code lines : nagelkerke(mod2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From these code lines, we deduce that the estimate of deviance explained is 22 %. We found about the same thing with the <span class="math inline">\(Pseudo\:R^2\)</span> estimate (package ‘rcompanion’).</p>
<p><strong>Model validation</strong>: check the assumptions</p>
<p><em>See III/.</em></p>
<p>Nota Bene : For this example, the validation will show a dependency that could be resolved by using a mixed model with “Farm_code” as random factor.</p>
</section>
</section>
<section id="poisson-law" class="level2">
<h2 class="anchored" data-anchor-id="poisson-law">2) POISSON LAW</h2>
<section id="introduction-5" class="level3">
<h3 class="anchored" data-anchor-id="introduction-5">INTRODUCTION</h3>
<p>Here we will focus on count data. This count data is a positive discrete variable. There are two types of distribution for this type of data. It can follow a Poisson or a Negative Binomial law. We will first focus on a <strong>Poisson law</strong>.</p>
<p>For the Poisson law, we have: <span class="math display">\[ E(y)= Var(y)=\lambda \]</span></p>
<p>We can write the distribution under a Poisson distribution as follows: <span class="math display">\[Pr(Y=y)=\frac{e^{-\lambda}.\lambda^y}{y!}\]</span> <span class="math inline">\(y\)</span> permits to count the number of occurrences and <span class="math inline">\(\lambda\)</span> is the mean and the variance of the Poisson distribution.</p>
<p>The link function of the Poisson law in the Generalized Linear model is <strong>log</strong> and can be written like that: <span class="math display">\[log(\mu_{y})= \alpha+ \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip} = \eta \]</span></p>
<p>By applying the inverse link function to <span class="math inline">\(\eta\)</span>, we obtain the predicted values of Y: <span class="math display">\[\mu_{y}= e^{\alpha+ \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip}} = e^{\eta} \]</span> Let’s take an example to illustrate the use of the Poisson law:</p>
</section>
<section id="poisson-law-example" class="level3">
<h3 class="anchored" data-anchor-id="poisson-law-example">POISSON LAW EXAMPLE</h3>
<p>###Dataset representation and objectives of the analysis</p>
<p>The study of Gotelli and Ellison in 2002 is a good example to apply the Poisson law. It is named “Biogeography at a regional scale: determinants of ants species density in New England bogs and forests”. At each of 22 sites, 25 pitfall traps were set in two 8x8m arrays, one in the center of the bog and one in adjacent upland forest 50 to 500m from the corresponding bog. Traps are treated as 50 independent replicate observations. The data are in the file BogAnts.txt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset importation </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ants<span class="ot">&lt;-</span><span class="fu">read.table</span>(<span class="st">"BogAnts.txt"</span>, <span class="at">dec =</span> <span class="st">"."</span>, <span class="at">header =</span> <span class="cn">TRUE</span>) </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>ants<span class="sc">$</span>Location<span class="ot">&lt;-</span><span class="fu">as.factor</span>(ants<span class="sc">$</span>Location)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   44 obs. of  6 variables:
 $ Site     : chr  "ARC" "ARC" "BH" "BH" ...
 $ Latitude : num  42.3 42.3 42.6 42.6 45 ...
 $ Elevation: int  95 95 274 274 133 133 210 210 362 362 ...
 $ Area     : int  1190 1190 105369 105369 38023 38023 73120 73120 38081 38081 ...
 $ Location : Factor w/ 2 levels "Bog","Forest": 2 1 2 1 2 1 2 1 2 1 ...
 $ Nsp      : int  9 8 10 8 6 5 9 4 6 2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for presence of missing values</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(ants))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Site  Latitude Elevation      Area  Location       Nsp 
        0         0         0         0         0         0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There is no missing value.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have 6 variables. The first one gives the site name. Latitude, Area (of the bog) and Elevation are covariates for each site. Location is a qualitative variable (‘Bog’ or ‘Forest’). The response variable is the last one variable (Nsp) which give the number of ant species found in the traps, in other words the ant species richness.</p>
<p>For this research we can wonder: which continuous or categorical variables drive the species richness of ants in bogs from New England ?</p>
</section>
<section id="data-exploration-4" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-4">Data exploration</h3>
<p><em>See I/1).</em></p>
<p>However, before continuing, we need to transform the variable ‘Area’, as in the exploration we can see a presence of outliers due to presence of very extensive bogs. We will therefore perform a log-transformation of this covariate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Bog Area</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Cleveland plot</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>(ants<span class="sc">$</span>Area,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">'Bog Area'</span>)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ants<span class="sc">$</span>Area,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">"Bog Area"</span>,<span class="at">main=</span><span class="st">""</span>)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile-Quantile plot</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(ants<span class="sc">$</span>Area,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(ants<span class="sc">$</span>Area,<span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-transformation for the 'Area' variable : </span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>ants<span class="sc">$</span>LogArea<span class="ot">&lt;-</span><span class="fu">log</span>(ants<span class="sc">$</span>Area)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Log Bog Area</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Cleveland plot</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>(ants<span class="sc">$</span>LogArea,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">'LogBog Area'</span>)</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ants<span class="sc">$</span>LogArea,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">"LogBog Area"</span>,<span class="at">main=</span><span class="st">""</span>)</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile-Quantile plot</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(ants<span class="sc">$</span>LogArea,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(ants<span class="sc">$</span>LogArea,<span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Now we can use the ‘Area’ variable.</p>
</section>
<section id="statistical-analysis-4" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis-4">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>As every model building, we will search for the candidate model by first analysing the full model with all the independent variables and their interactions. Then a backward selection will be used to select the best model based on term significance. Successively, the non-significant interactions are deleted, and then the non-significant main effects. However, a non-significant main effect is deleted only if it is non-significant AND not contained in a significant interaction.</p>
<p>Here we perform a Poisson generalized linear model with these code lines:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The model is : </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">glm</span>(Nsp<span class="sc">~</span> Location <span class="sc">+</span> Latitude <span class="sc">+</span> Elevation <span class="sc">+</span> LogArea <span class="sc">+</span> Location<span class="sc">:</span>Latitude <span class="sc">+</span> Location<span class="sc">:</span>Elevation<span class="sc">+</span> Location<span class="sc">:</span>LogArea, <span class="at">data=</span>ants,<span class="at">family=</span><span class="fu">poisson</span>(<span class="at">link=</span><span class="st">"log"</span>))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># To check the significance</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"Chi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Nsp ~ Location + Latitude + Elevation + LogArea + Location:Latitude + 
    Location:Elevation + Location:LogArea
                   Df Deviance    AIC     LRT Pr(&gt;Chi)
&lt;none&gt;                  39.973 216.33                 
Location:Latitude   1   39.981 214.34 0.00801   0.9287
Location:Elevation  1   40.370 214.72 0.39675   0.5288
Location:LogArea    1   40.075 214.43 0.10247   0.7489</code></pre>
</div>
</div>
<p>Here any interaction is significant. We delete the less significant interaction : Location:Latitude and do this code lines until there are only significant effects.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Nsp ~ Location + Latitude + Elevation + LogArea + Location:Elevation + 
    Location:LogArea
                   Df Deviance    AIC     LRT  Pr(&gt;Chi)    
&lt;none&gt;                  39.981 214.34                      
Latitude            1   55.094 227.45 15.1134 0.0001012 ***
Location:Elevation  1   40.426 212.78  0.4446 0.5049344    
Location:LogArea    1   40.078 212.43  0.0974 0.7550075    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The less significant interaction is Location:LogArea. So we delete this interaction and continue.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Nsp ~ Location + Latitude + Elevation + LogArea + Location:Elevation
                   Df Deviance    AIC     LRT  Pr(&gt;Chi)    
&lt;none&gt;                  40.078 212.43                      
Latitude            1   55.176 225.53 15.0976 0.0001021 ***
LogArea             1   40.273 210.63  0.1943 0.6593240    
Location:Elevation  1   40.499 210.85  0.4208 0.5165445    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The less significant interaction is Location:Elevation. So, we delete this interaction and continue.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Nsp ~ Location + Latitude + Elevation + LogArea
          Df Deviance    AIC     LRT  Pr(&gt;Chi)    
&lt;none&gt;         40.499 210.85                      
Location   1   70.185 238.54 29.6856 5.081e-08 ***
Latitude   1   55.621 223.97 15.1221 0.0001008 ***
Elevation  1   49.909 218.26  9.4100 0.0021580 ** 
LogArea    1   40.690 209.04  0.1913 0.6618646    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The less significant effect is LogArea. So, we delete this effect and continue.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Nsp ~ Location + Latitude + Elevation
          Df Deviance    AIC     LRT  Pr(&gt;Chi)    
&lt;none&gt;         40.690 209.04                      
Location   1   70.376 236.73 29.6856 5.081e-08 ***
Latitude   1   56.649 223.00 15.9590 6.473e-05 ***
Elevation  1   50.284 216.64  9.5938  0.001952 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here all the effects are significant. So we can stop the backward selection and conclude with this the selected model: Nsp~Location + Elevation + Latitude</p>
<p>It is necessary to analyse the coefficients of the model in order to understand how the main effects influence the ant species richness in bogs.</p>
<p><strong>Model’s coefficients analysis</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Nsp ~ Location + Latitude + Elevation, family = poisson(link = "log"), 
    data = ants)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    11.9368121  2.6214970   4.553 5.28e-06 ***
LocationForest  0.6354389  0.1195664   5.315 1.07e-07 ***
Latitude       -0.2357930  0.0616638  -3.824 0.000131 ***
Elevation      -0.0011411  0.0003749  -3.044 0.002337 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 102.76  on 43  degrees of freedom
Residual deviance:  40.69  on 40  degrees of freedom
AIC: 209.04

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>So we can write the model like that: <span class="math display">\[ log(Species\:Richness) = 11.93 + (Location_{Bog} = 0 ;\:Location_{Forest} = +0.63^{***})\:- 0.23^{***}.Latitude\: -0.001^{***}. Elevation  \]</span> Be careful here, for a factor, there is a level called “the baseline” which mean that its coefficient is 0. It is the reference level.</p>
<p><strong>Model explanation</strong></p>
<p>In generalized linear models, there is no R2, so we need to calculate a pseudo R2 with the distance between the null model deviance and the residual deviance of the model with this formula: <span class="math display">\[Pseudo\:R^2=100\:.\:\frac{Null\:Deviance- Residual\:Deviance}{Null\:Deviance}\]</span></p>
<p>Let’s do it with R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pseudo R2 calculation </span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>(mod1<span class="sc">$</span>null.deviance<span class="sc">-</span>mod1<span class="sc">$</span>deviance)<span class="sc">/</span>mod1<span class="sc">$</span>null.deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6040372</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can have other pseudo R2 with the package 'rcompanion'</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nagelkerke</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Models
                                                                                  
Model: "glm, Nsp ~ Location + Latitude + Elevation, poisson(link = \"log\"), ants"
Null:  "glm, Nsp ~ 1, poisson(link = \"log\"), ants"                              

$Pseudo.R.squared.for.model.vs.null
                             Pseudo.R.squared
McFadden                             0.235913
Cox and Snell (ML)                   0.756039
Nagelkerke (Cragg and Uhler)         0.757956

$Likelihood.ratio.test
 Df.diff LogLik.diff  Chisq    p.value
      -3     -31.036 62.073 2.1197e-13

$Number.of.observations
         
Model: 44
Null:  44

$Messages
[1] "Note: For models fit with REML, these statistics are based on refitting with ML"

$Warnings
[1] "None"</code></pre>
</div>
</div>
<p>So here, the model explains 60.4% of the deviance, but with the others estimate, we found the model explain about 75% of the deviance. Now, it is necessary to check the assumptions of the model to validate. See the part dedicated to this at the end.</p>
</section>
</section>
<section id="negative-binomial-law" class="level2">
<h2 class="anchored" data-anchor-id="negative-binomial-law">3) NEGATIVE BINOMIAL LAW</h2>
<section id="introduction-6" class="level3">
<h3 class="anchored" data-anchor-id="introduction-6">INTRODUCTION</h3>
<p>The Negative Binomial distribution has been configured in a number of different ways in the statistical literature. Perhaps the most common way to parameter is to see the Negative Binomial distribution arising as a distribution of the number of failures (X) before the r^th success in independent trials, with success probability p in each trial (consequently, r &gt; 0 and 0 &lt; p &gt; 1). In such a case the probability mass function can be expressed as: <span class="math display">\[Pr(X=x|r,p)=\frac {\Gamma(x+r)}{x!.\Gamma(r)}.p^r.(1-p)^x\]</span></p>
<p>and the random variable X has the expectation (theoretical mean): <span class="math display">\[\mu =\frac{r.(1 - p)}{p}\]</span></p>
<p>and variance: <span class="math display">\[\sigma^2 = \frac{r.(1 – p)}{p^2}\]</span></p>
<p>In a NB Generalized Linear model, the link function is log so that: <span class="math display">\[log(\mu_{y})= \alpha+ \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip} = \eta \]</span></p>
<p>The predicted values of Y is obtained by applying the inverse link function to <span class="math inline">\(\eta\)</span>. <span class="math display">\[\mu_{y}= e^{\alpha+ \beta_{1}.X{i1}+ \beta_{2}.X{i2}+\beta_{3}.X{i3}+...\beta_{p}.X{ip}} = e^{\eta} \]</span> The negative binomial model has a NB error structure. This error structure allows, among other things, to correctly specify the relationship between the mean and the variance. This relationship is used by the maximum likelihood approach to estimate the coefficients and standard errors of the generalized linear model parameters.</p>
<p>Let’s take an example to illustrate the use of the Negative binomial law:</p>
</section>
<section id="negative-binomial-law-example" class="level3">
<h3 class="anchored" data-anchor-id="negative-binomial-law-example">NEGATIVE BINOMIAL LAW EXAMPLE</h3>
</section>
<section id="dataset-presentation-and-objectives-of-the-analysis-4" class="level3">
<h3 class="anchored" data-anchor-id="dataset-presentation-and-objectives-of-the-analysis-4">Dataset presentation and objectives of the analysis</h3>
<p>The study of Timi and Poulin in 2003 is a good example to apply the Negative binomial law. We will use a subset of the original data. At each of 4 stations, fish sample were collected, with a total of 522 individual of anchovy. These fish were examined for parasites in order to understand the parasite community structure across the host population of anchovy. The data are in the file FishParasite.txt The response variable is “Number”, which represents the total number of parasites found in the fish. It is a count variable. There are 3 explicative variables: “Sex” (of the fish), “Length” (of the fish) and “Area”. Sex and Length are continuous, and Area is a categorical variable with 4 categories (A, B, C or D). Here we only consider the interaction between Length and Area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset import</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>para <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"FishParasites.txt"</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>para<span class="sc">$</span>Area<span class="ot">&lt;-</span><span class="fu">as.factor</span>(para<span class="sc">$</span>Area)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>para<span class="sc">$</span>Sex<span class="ot">&lt;-</span><span class="fu">as.factor</span>(para<span class="sc">$</span>Sex)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(para)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   521 obs. of  4 variables:
 $ Area  : Factor w/ 4 levels "A","B","C","D": 1 1 1 1 1 1 1 1 1 1 ...
 $ Length: int  88 93 94 94 94 94 94 94 94 96 ...
 $ Sex   : Factor w/ 2 levels "Female","Male": 1 2 1 1 1 2 2 2 2 1 ...
 $ Number: int  3 2 8 14 12 4 10 0 2 17 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing values ? </span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(para))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Area Length    Sex Number 
     0      0      0      0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There is no missing value.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s begin quickly with a <strong>Poisson model</strong> in order to see the problems and then apply a <strong>Negative Binomial model</strong>.</p>
</section>
<section id="data-exploration-5" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-5">Data exploration</h3>
<p><em>See part I/1).</em></p>
</section>
<section id="statistical-analysis-5" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis-5">Statistical analysis</h3>
<p><strong>Model building</strong></p>
<p>We perform a backward selection as explained previously, with a Poisson model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">glm</span>(Number<span class="sc">~</span> Sex <span class="sc">+</span> Area <span class="sc">+</span> Length <span class="sc">+</span> Area<span class="sc">:</span>Length ,<span class="at">data=</span>para ,<span class="at">family=</span><span class="fu">poisson</span>(<span class="at">link=</span><span class="st">"log"</span>))</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Then we check for significance</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod1,<span class="at">test=</span><span class="st">"Chi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Number ~ Sex + Area + Length + Area:Length
            Df Deviance   AIC    LRT  Pr(&gt;Chi)    
&lt;none&gt;            10030 12300                     
Sex          1    10066 12334  35.91 2.071e-09 ***
Area:Length  3    10953 13217 922.60 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Number ~ Sex + Area + Length + Area:Length, family = poisson(link = "log"), 
    data = para)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.2067538  0.1056462   1.957   0.0503 .  
SexMale      -0.1041194  0.0173649  -5.996 2.02e-09 ***
AreaB         1.2976071  0.1447951   8.962  &lt; 2e-16 ***
AreaC        -2.6680762  0.1814043 -14.708  &lt; 2e-16 ***
AreaD        -5.4800806  0.2431050 -22.542  &lt; 2e-16 ***
Length        0.0229176  0.0008601  26.645  &lt; 2e-16 ***
AreaB:Length -0.0070126  0.0011600  -6.045 1.49e-09 ***
AreaC:Length  0.0162007  0.0012135  13.350  &lt; 2e-16 ***
AreaD:Length  0.0316032  0.0015890  19.889  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 19911  on 520  degrees of freedom
Residual deviance: 10030  on 512  degrees of freedom
AIC: 12300

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Here the interaction between Length and Area is significant, so we keep both variables. And Sex is also significant. So the full model is the candidate model. To see if we can apply the Poisson model, we test the overdispersion. Sometimes, the variance of the response variable may be higher than supposed by the Poisson law. If the parameter is greater than 1.5, we can say that there is overdispersion and the standard errors of the coefficient estimates are biased.</p>
<p>Let’s check the overdispersion in the model with a DHARMa non parametric dispersion test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Overdisperion checking of the Poisson model</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale parameter calculation</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>E1 <span class="ot">&lt;-</span> <span class="fu">resid</span>(mod1, <span class="at">type =</span> <span class="st">"pearson"</span>) <span class="co"># (Y - mu) / sqrt(mu)</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>N  <span class="ot">&lt;-</span> <span class="fu">nrow</span>(para)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>p  <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(mod1))</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(E1<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (N <span class="sc">-</span> p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.72358</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use simulations for parameter estimation (package DHARMa)</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">testDispersion</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa nonparametric dispersion test via sd of residuals fitted vs.
    simulated

data:  simulationOutput
dispersion = 31.727, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>The overdispersion index is largely over 1.5, which means that there is an overdispersion in the model. So, the Poisson model can’t be apply and analyse. There are some reasons of overdispersion like for example: the presence of outliers, a dependency, a non linear relationship, the use of the wrong link function…</p>
<p>We will change and use a Negative Binomial model and recalculate the overdispersion once we have found the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulation</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>modNB<span class="ot">&lt;-</span><span class="fu">glm.nb</span>(Number<span class="sc">~</span> Sex <span class="sc">+</span> Area <span class="sc">+</span> Length <span class="sc">+</span> Area<span class="sc">:</span>Length ,<span class="at">data=</span>para)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Then we check for significance</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(modNB,<span class="at">test=</span><span class="st">"Chi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Number ~ Sex + Area + Length + Area:Length
            Df Deviance    AIC    LRT  Pr(&gt;Chi)    
&lt;none&gt;           581.89 4182.9                     
Sex          1   582.70 4181.7  0.814    0.3669    
Area:Length  3   637.58 4232.6 55.698 4.874e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We have a significant effect for the interaction between Area and Length but not for the main effect Sex. We need to keep the main factor Area and Length and delete the variable Sex, contrary to the Poisson model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Number ~ Area + Length + Area:Length
            Df Deviance    AIC    LRT  Pr(&gt;Chi)    
&lt;none&gt;           581.90 4181.7                     
Area:Length  3   636.77 4230.6 54.873 7.308e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here, the interaction is still significant, with the two main effect. So we have found the candidate model. Now we need to test the overdispersion, the same way as before.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.345759</code></pre>
</div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa nonparametric dispersion test via sd of residuals fitted vs.
    simulated

data:  simulationOutput
dispersion = 0.86643, p-value = 0.568
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>We found 1.35, which is below/under 1.5. So we succeed to delete the overdispersion. The DHARMa test validates the absence of overdispersion.</p>
<p><strong>Model explanation</strong></p>
<p>Now we can examine the coefficients of the candidate model in order to understand how the number of parasites in fish is influenced.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients of the model</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modNB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Number ~ Area + Length + Area:Length, data = para, 
    init.theta = 1.326438087, link = log)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.440440   0.459468  -0.959   0.3378    
AreaB         1.639419   0.652440   2.513   0.0120 *  
AreaC        -0.613328   0.825456  -0.743   0.4575    
AreaD        -5.421868   0.718160  -7.550 4.36e-14 ***
Length        0.028189   0.004059   6.944 3.80e-12 ***
AreaB:Length -0.010137   0.005593  -1.812   0.0699 .  
AreaC:Length  0.002096   0.005866   0.357   0.7209    
AreaD:Length  0.029865   0.005618   5.316 1.06e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.3264) family taken to be 1)

    Null deviance: 1096.8  on 520  degrees of freedom
Residual deviance:  581.9  on 513  degrees of freedom
AIC: 4183.7

Number of Fisher Scoring iterations: 1

              Theta:  1.3264 
          Std. Err.:  0.0866 

 2 x log-likelihood:  -4165.6880 </code></pre>
</div>
</div>
<p>So, the candidate model is: <span class="math display">\[ log(Number\:of\:Parasites) = -0.44 + (Area_{A} = 0 ;\:Area_{B} = +1.64;\:Area_{C} = -0.61;\:Area_{D}  = -5.42)\]</span> <span class="math display">\[ +\: 0.028.Length\:+ (if\:Area=B: - 0.010. Length;\:if\:Area=C: + 0.002. Length ;\:if\:Area=C: + 0.029.Length)  \]</span></p>
<p>Be careful here! As we saw previously, there is always a modality of the factor which is the baseline, and every modality of this factor is compared to the baseline. So if a modality of the factor is significant, it means that there is a difference between this modality and the baseline. So in order to test which modality is different from one another, we need to change the baseline.</p>
<p>As in every Generalized Linear Models, there is no R2. So we will calculate the pseudo R2 with the formula: <span class="math display">\[Pseudo\:R^2=100\:.\:\frac{Null\:Deviance-Residual\:Deviance}{Null\:Deviance}\]</span></p>
<p>Let’s perform it on R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate of deviance explained</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>(modNB<span class="sc">$</span>null.deviance<span class="sc">-</span>modNB<span class="sc">$</span>deviance)<span class="sc">/</span>modNB<span class="sc">$</span>null.deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4694521</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Some others estimates of deviance explained - package 'rcompanion'</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nagelkerke</span>(modNB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Models
                                                                             
Model: "glm.nb, Number ~ Area + Length + Area:Length, para, 1.326438087, log"
Null:  "glm.nb, Number ~ 1, para, 0.689574211, log"                          

$Pseudo.R.squared.for.model.vs.null
                             Pseudo.R.squared
McFadden                            0.0820131
Cox and Snell (ML)                  0.5104780
Nagelkerke (Cragg and Uhler)        0.5105620

$Likelihood.ratio.test
 Df.diff LogLik.diff  Chisq    p.value
      -7     -186.08 372.16 2.2094e-76

$Number.of.observations
          
Model: 521
Null:  521

$Messages
[1] "Note: For models fit with REML, these statistics are based on refitting with ML"

$Warnings
[1] "None"</code></pre>
</div>
</div>
<p><strong>Model validation</strong></p>
<p><em>See III/.</em></p>
</section>
</section>
</section>
<section id="iii-model-validation" class="level1">
<h1>III/ MODEL VALIDATION</h1>
<p>To be able to conclude with your results you have to validate your model. All <strong>general linear models</strong> (linear regression, ANOVA, ANCOVA) need to verify the 3 following criteria: <em>normality of residuals</em>, <em>homogeneity of variances</em>, and <em>independance of residuals</em>. <strong>Generalized linear model</strong>, due to the hypothetis made on Y, only need to verify the last criterion: the <em>independance of the residuals</em>.</p>
<section id="normality-of-residuals" class="level2">
<h2 class="anchored" data-anchor-id="normality-of-residuals">Normality of residuals</h2>
<p>The assumption of normality can be checked by producing an histogram and a quantile plot of the residuals. The histogram of residuals should follow a normal distribution. If the points in the quantile plot lie mostly on the red line, the residuals are normally distributed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram example 1</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mod2<span class="sc">$</span>residuals,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">"residuals"</span>,<span class="at">main=</span><span class="st">"Check Normality ex 1"</span>)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile-Quantile plot</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(mod2<span class="sc">$</span>residuals,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mod2<span class="sc">$</span>residuals,<span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram example 2</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mod1<span class="sc">$</span>residuals,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">"residuals"</span>,<span class="at">main=</span><span class="st">"Check Normality ex 2"</span>)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile-Quantile plot</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(mod1<span class="sc">$</span>residuals,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mod1<span class="sc">$</span>residuals,<span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-46-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram example 3</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(resid,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">"residuals"</span>,<span class="at">main=</span><span class="st">"Check Normality ex 3"</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile-Quantile plot</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(resid,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">xlab=</span><span class="st">''</span>)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(resid,<span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-46-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see on the first example, the residuals lie mostly on the red line so we can say the residuals are normally distributed.</p>
<p>However, if a small deviation from normality is detected as on the second example, the Fisher test is considered fairly resistant to these deviations and you can still validate the model.</p>
<p>If the residuals don’t follow the red line like on the third example, you can’t conclude residuals are normally distributed and validate the model. Transformation can be done to solve the problem but the best is to make another hypothesis on the law of Y. Linear models lie on the assumption that Y is continuous and its distribution is close to follow a Gaussian law. If Y is semi quantitative, binary, or a proportion, the residuals are probably not going to follow a normal distribution, so you have to make another hypothesis on Y law. Therefore you will need to use a GLM.</p>
</section>
<section id="homogeneity-of-variances" class="level2">
<h2 class="anchored" data-anchor-id="homogeneity-of-variances">Homogeneity of variances</h2>
<p>The assumption of homogeneity of variances states that the variation in the residuals is approximately equal across the range of the predictor variables. It can be checked by plotting the residuals against the fitted values and the residuals against the significant main effects. To conclude that the variance is homogeneous, we need to check that it is stable and does not show any patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals vs fitted</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(mod2)<span class="sc">~</span><span class="fu">fitted</span>(mod2)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>      , <span class="at">col=</span><span class="st">'blue'</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>      , <span class="at">pch=</span><span class="dv">16</span>, <span class="at">main=</span><span class="st">"Graph1"</span>)</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals against Habitat factor</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(mod1)<span class="sc">~</span> dataFly<span class="sc">$</span>Habitat, </span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">varwidth =</span> <span class="cn">TRUE</span>,</span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Habitat"</span>,</span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="st">"Graph2"</span>)</span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals vs fitted</span></span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(mod1)<span class="sc">~</span><span class="fu">fitted</span>(mod1)</span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a>      , <span class="at">col=</span><span class="st">'blue'</span></span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a>      , <span class="at">pch=</span><span class="dv">16</span>, <span class="at">main=</span><span class="st">"Graph3"</span>)</span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb95-20"><a href="#cb95-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-21"><a href="#cb95-21" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals against Castes factor</span></span>
<span id="cb95-22"><a href="#cb95-22" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(resid<span class="sc">~</span> dataBombus<span class="sc">$</span>Castes, </span>
<span id="cb95-23"><a href="#cb95-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">varwidth =</span> <span class="cn">TRUE</span>,</span>
<span id="cb95-24"><a href="#cb95-24" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb95-25"><a href="#cb95-25" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"Castes"</span>,</span>
<span id="cb95-26"><a href="#cb95-26" aria-hidden="true" tabindex="-1"></a>         <span class="at">main=</span><span class="st">"Graph4"</span>)</span>
<span id="cb95-27"><a href="#cb95-27" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb95-28"><a href="#cb95-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-29"><a href="#cb95-29" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals vs fitted</span></span>
<span id="cb95-30"><a href="#cb95-30" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(resid<span class="sc">~</span><span class="fu">fitted</span>(mod3)</span>
<span id="cb95-31"><a href="#cb95-31" aria-hidden="true" tabindex="-1"></a>      , <span class="at">col=</span><span class="st">'blue'</span></span>
<span id="cb95-32"><a href="#cb95-32" aria-hidden="true" tabindex="-1"></a>      , <span class="at">pch=</span><span class="dv">16</span>, <span class="at">main=</span><span class="st">"Graph5"</span>)</span>
<span id="cb95-33"><a href="#cb95-33" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="linear_modelling_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<ul>
<li><p>As you can see in graph 1, the variation in the residuals is approximately equal across the range of the fitted values and there is no pattern, so we can conclude that the variance is homogeneous.</p></li>
<li><p>The variance of a qualitative variable is studied with a boxplot. For the second graph, we can see that the variance is similar, so we can conclude that it is homogeneous.</p></li>
<li><p>In the third graph, we can see that the variance is not stable, as we have a funnel shape. So we can’t conclude that it is homogeneous.</p></li>
<li><p>On the fourth graph, we can see that the variance is not stable, as the boxplots do not have the same height. It is therefore not possible to conclude that they are homogeneous.</p></li>
<li><p>The fifth graph shows a linear pattern so we cannot conclude positively on the homogeneity of the variance.</p></li>
</ul>
<p>Statistical tests are rather resistant to deviations from homogeneity, and can tolerate deviations of around 16 units. If the variance exceeds this threshold, is not stable or shows a pattern, it can be transformed to solve the problem.</p>
</section>
<section id="independence-of-residuals" class="level2">
<h2 class="anchored" data-anchor-id="independence-of-residuals">Independence of residuals</h2>
<p>ANCOVA (like other General Linear Models) lies on the assumption that all replicate measures (and so, residuals) are independent of each other. This issue needs to be considered as <em>the design stage</em>. Given the present design, all flies collected are independent as randomly sampled. This assumption is checked. If data are grouped/dependent in any way, then more complex designs are needed to account for additional factors. During the exploration stage, you can detect spatial dependencies with a Moran test on the response variable or spot time dependencies by plotting the autocorrelogram. Thus, you can include the dependency in your model by using mixed models (cf chapter mixte model). If the dependency is still present in the residual of the model, you can’t use general linear model and need to implement specific time (ARIMA …) and space (Spatial Lag model …) models.</p>
<p>Unlike General Linear Models, Generalized Linear Models don’t require the conditions of homoscedasticity and normality of residuals, but it does require the <em>independence of residuals</em>. We can also check the presence of influential observations (these are the statistical units that have a too large contribution to the model).</p>
</section>
</section>
<section id="general-conclusion" class="level1">
<h1>GENERAL CONCLUSION</h1>
<p>Linear models are a kind of models where a dependent and quantitative variable Y is explained by multiple independent variables X with a linear kind of connection in the form: <span class="math display">\[ Y = B*X + E \]</span></p>
<p>Statistical analysis of linear models takes 3 main steps:</p>
<p><strong>I - Data exploration</strong></p>
<p>1 - Verifying that there is no outliers in the distribution of Y and the Xs by using boxplots and Clevelandplots. A transformation of Y and/or the Xs can be performed to settle the potential issues.</p>
<p>2 - Checking the colinearity of the Xs (corrplots, boxplot, VIF).</p>
<p>3 - Checking the relationships between Y and the Xs (plot, boxplot).</p>
<p>4 - Checking if there are potential interactions between the Xs (boxplot, plot, table).</p>
<p><strong>II - Model building</strong></p>
<p>In this chapter, We developped two types of linear models: <strong>General linear models</strong> and <strong>Generalized linear models</strong>. In <strong>general linear models</strong>, Y is a <em>continuous quantitative variable</em> whose residuals follow a <em>normal law</em>. The <em>explanatory variables</em> can be:</p>
<ul>
<li><p>Only quantitative: <em>Simple</em> (only one explanatory variable) or <em>Multiple regression models</em></p></li>
<li><p>Only qualitative: <em>ANOVA models</em></p></li>
<li><p>Qualitative and Quantitative : <em>ANCOVA models</em> The estimate method is the <strong>least square method</strong>.</p></li>
</ul>
<p>In <strong>generalized linear models</strong>, Y’s law (and so its residuals’ law) is not normal and can follow, for instance:</p>
<ul>
<li><p>A <strong>Binomial law</strong> when the variable is <em>binary</em> (link function: <em>logit</em>). <em>Example of application: mark and recapture and presence/absence of data</em>.</p></li>
<li><p>A <strong>Poisson law</strong> when the variable is a <em>counting variable</em> with a low expectancy (link function : <em>log</em>) <em>Example of application: species abundance or proportion</em>.</p></li>
<li><p>A <strong>Negative Binomial law</strong> when the variable is a <em>counting variable</em> with a higher expectancy (link function : <em>log</em>)</p></li>
</ul>
<p>This time the estimate method is based on the maximum of likelihood (minimum of deviance). The relation between Y and the Xs is not direct and the mean value <span class="math inline">\(\mu\)</span> of Y is estimated through a link function g which associate it to a predicted value <span class="math inline">\(\eta\)</span> so that : <span class="math inline">\(\eta\)</span> = g(<span class="math inline">\(\mu\)</span>). NB: You can draw hypotheses on Y distribution based on other laws such as the <strong>Gamma law</strong>, the <strong>Beta Law</strong> or the <strong>Lognormal Law</strong> (not detailed here).</p>
<p><strong>III - Model validation</strong></p>
<p>There are 3 conditions to validate a linear model:</p>
<ul>
<li><p><strong>Non-correlation of the residuals</strong></p></li>
<li><p><strong>Homoscedasticity of the variance</strong> (plot residuals vs fitted) (<em>Essential for general linear models but not for generalized linear models</em>)</p></li>
<li><p><strong>Normality of the residuals</strong> (<em>Only for general linear models</em>). You can use these models to show a significant effect on Y and also to draw predictions on its distribution (function <em>predict</em>).</p></li>
</ul>
<p>To go further: In general and generalized linear models, all the explanatory variables have fixed effects and are independent. However, in ecology, it is not always the case. Other models can allow to take into account a dependency between explanatory variables by considering a random effect (<em>see chapter on mixed models</em>) or considering spatial or temporal dependency with spatial and time models. In order to model more complex ecological issues that do not fit classical statistical models, or to estimate ecological parameters, you will need to use another approach: Bayesian statistics (<em>see Chapter “Bayesian Statistics</em>.)</p>
<p>Examples from Yannick Outreman’s course</p>
<p>Written by Clément Berthelot, Sarah Derrien, Fanny Kuttler, Léa Morel and Lucia Oliveira-cruz</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>