---
title: "Modèle matrice et applications en écologie"
bibliography: "Quentin, Alexie, Jeanne et Laurane"
execute: 
  freeze: auto
output: 
  html_document:
   toc: true
   toc_float: true
---
Plan projet : 

Plan projet : 

Modélisation matricielle en écologie
A quoi servent les matrices en écologie ?
Transformer une population en matrice
Modifier une matrice de population (addition de population,soustraction)

II. Les grands exemples de matrices en écologie  
Classes d’âge et reproduction : Matrice de Leslie
Impact prédateur
Compétition ?

III. Matrice en épidémiologie 

IV. Chaînes de Markov 



Chapitre purment technique ? ou bien les modèles matriciels et on prend des exemples d'écologie et on explique en même temps ?
parler de la dynamique de populations

partir de la population de suricats et on complexifie au fur et à mesure en introduisant les notions 




I. Modélisation matricielle en écologie
	A quoi servent les matrices en écologie

Les matrices sont des outils mathématiques permettant de modéliser des situations. Utilisées dans de très nombreux domaines, l’écologie n’échappe pas à la règle. Les matrices permettent notamment de représenter des populations et de les faire évoluer selon différentes règles ou évènements. Les premières utilisations de ces modèles remontent à 1941 par Harro Bernardelli étudiant les oscillations de la structure d’une population. D’autres utilisent à leur tour les matrices pour représenter les populations, notamment Leslie en 1945 dont les travaux marquèrent un tournant dans l’utilisation de ces matrices en écologie. Par la suite, différents modèles de représentation matricielles des populations durent publiés et utilisés en dynamique des populations.

L’objectif d’une matrice de population est, comme nous l’avons déjà dit, de représenter l’évolution d’une population dans le temps et son état à un temps t particulier par exemple. Elle se base donc sur les comportements de croissance des populations. Reprenons les bases pour mieux comprendre comment les matrices de population ont été créées :

En 1798, Malthus publie son modèle de croissance des populations. Si nous considérons n(t) comme la taille de la population au temps t, et λ le taux de croissance de cette population, nous pouvons écrire que : 
n(t+1) = λn(t)

Si nous voulons écrire cette équation pour la population dans un futur lointain, nous pouvons trouver par récurrence que :

n(t) = λ^nn(0)   avec n(0) la population au début de notre étude.

En fonction du signe de λ, notre population va donc augmenter ou diminuer dans le temps.
Seulement, ce modèle est largement simplifié. Pourquoi ? Il considère que tous les individus sont identiques, que ce soit par leur capacité de reproduction ou leur capacité de survie. Cela signifie que dans ce modèle, un individu âgé peut tout aussi bien se reproduire et survivre qu’un jeune individu vigoureux et ayant tout juste atteint la maturité sexuelle. Mais alors, comment régler ce problème ? Dans la nature, chaque individu est différent, mais nous pouvons prédire ses qualités selon la moyenne de son espèce et sa position dans la population : par position, nous entendons sa place dans différentes catégories exprimées selon diverses critères tels que l’âge (jeune, adulte, âgé), le sexe (mâle, femelle), ou encore beaucoup d’autres. Ces catégories sont communément appelées « classes ». Plusieurs individus d’une même classe auront les mêmes particularités du point de vue du critère utilisé pour cette classe, et donc les mêmes impacts sur la dynamique de leur population. Ils auront par exemple le même taux de fertilité ou de survie. Ainsi, nous pouvons déterminer la contribution de chaque classe à une autre classe et donc finalement à la population, et cela en fonction de l’effectif de la première classe. L’effectif d’une classe i peut ainsi s’écrire :

n_i (t+1)= ∑_j▒〖a_ij n_j (t)〗  

où a est la contribution et a_ij la contribution d’une classe j à la classe i à l’instant t+1.
Nous pouvons alors créer un système considérant l’ensemble des classes, qui pourra être traduit en matrice :

n(t+1) = An(t)
Soit n(t) = A^tn(0)

Où A est ce que nous appelons matrice de projection de la population, représentant donc notre population sous forme matricielle, selon ses différentes caractéristiques (classes, paramètres des classes…). n(t) est un vecteur dépendant du nombre d’individu présents dans notre population, et n(0) est notre vecteur population initiale, duquel nous allons pouvoir partir pour faire évoluer cette population dans le temps.

La dynamique de population est un concept parfois difficile à étudier car dépendant de nombreux paramètres. Une population va varier en taille et en type d’individus selon quatre processus principaux : la naissance de nouveaux individus, dépendant de la fertilité de ceux déjà présent et de leur nombre ; la mortalité, pouvant dépendre du taux de prédation, de maladies ou de vieillesse ; l’immigration, dont les taux vont dépendre des autres populations, de leurs distances avec celle étudiée et de la capacité de dispersion des individus ; et enfin de l’émigration, qui va dépendre du mode de vie de l’espèce observée et de sa tendance à quitter sa population d’origine. Une matrice va permettre de représenter la variation de population selon ces quatre processus.

Ces représentations peuvent être très complètes, incluant le différences d’âge, de sexe, d’origine génétique et autres des individus. En effet, tous les individus ne vont pas avoir le même impact au même sur la dynamique de leur population. Les individus trop jeunes ou trop vieux ne participent pas à la reproduction et donc à l’augmentation future de leur groupe. Les nombre de mâles ne va pas avoir le même impact sur le nombre de descendants que les femelles. Enfin, les individus de différents âges ne vont pas avoir les mêmes taux de mortalité. Les matrices sont ainsi beaucoup utilisées en épidémiologie, où elles vont permettre de modéliser la dispersion de la maladie dans une population selon la virulence et l’infectiosité de celle-ci. Elles peuvent aussi se concentrer sur la réponse de la population à la maladie, selon le taux de mortalité des individus et leur capacité de résilience.

Il est important de savoir que les matrices de modélisation ont des limites. Elles reposent notamment sur des hypothèses qui vont permettre leur bonne analyse et la validité de leurs résultats. Ainsi, les interactions entre individus ne sont pas pris en compte, et n’influent pas sur la dynamique de leur population. Ensuite, les particularités des individus d’une même classe sont identiques, qu’importe l’individu, et constantes au cours du temps. Des particularités différentes se retrouvent uniquement dans des classes différentes.

En permettant de modéliser le plus correctement possible l’évolution d’une population dans le temps, selon le maximum de paramètres qui peuvent l’impacter positivement ou négativement, nous pouvons obtenir de nombreux résultats très intéressants. Ainsi, les matrices de population peuvent nous permettre d’améliorer la conservation des espèces et leur gestion. En fonction de la dynamique de sa population, nous pouvons savoir si l’espèce est menacée dans le futur et/ou impactée par des évènements (exemple : impact du feu sur des espèces végétales). Nous pouvons avoir une vision plus globale et réelle de la manière dont les populations évoluent dans leur environnement. Cependant, il n’est pas forcément utile d’avoir recours à des modèles matriciels. Comme pour chaque étude, il est nécessaire de se poser les bonnes questions, de réfléchir à l’intérêt de ce mode d’analyse comparé à d’autres et de sa pertinence pour la question/population étudiée.

