---
title: "A simple chapter using R"
bibliography: references.bib
execute: 
  freeze: auto
output: 
  html_document:
   toc: true
   toc_float: true
---

## 3 - Saptial modeling

Once the structure of the spatial correlation has be estimated, it can then be included in the model.

Depending on the structure of the autocorrelation and especially if the process is or is not stationary,and of the structure of the residuals, the analysis required will be different and more or less difficult.

For the analysis under R, it will be important to import the package **spatialreg** as well as **gwrr**

```{r}
library(spatialreg)
library(gwrr)
```

### 3.1.Stationary process

For the models described here, it is required for the processes to be stationary, meaning that the process is constant across regions. Another assumption is that the spatial autocorrelation is isotropic. This means that the cause of the autocorrelation act the same way in every direction. Anisotropy may be caused for example by environmental factors like the wind or water currents.

All the models showed here will be based on the genralized linear model modified to take the spatial autocorrelation into account :

**Y = X**$\beta$ + $\epsilon$

#### 3.1.1. Spatially lagged X model

This analysis best perform on local analysis. If the scale is to big, it may be wiser to use another analysis as this one will lack precision.

The idea behind this analysis is that the state of a neighbor region will affect our region.

This model estimate how well the response variable at one site reflect the response values at its surrounding sites.

An extra parameter : $\rho$A, called the autocovariate is added to the generalized linear model's formula. It is a distance-weighted function of the neighboring response value.

**Y = X**$\beta$ + $\rho$A + $\epsilon$

A can be calculated as either the weighted sum :

$$(A_{i}) = \displaystyle \sum_{j\in k_{i}}w_{ij}y{j]} $$

or as the weighted average:

$$(A_{i}) = \displaystyle \frac{\sum_{j\in k_{i}}w_{ij}y{j]}}{\sum_{j\in k_{i}}w_{ij}} $$

( $y_{i}$= the value of y at the site j among site i's set of $k_{i}$ neighbors.

$w_{ij}$ = the weight given to the site j's influence over site i)

This function is usually related to the distance between data points or to the environmental distance.

In R

#### 3.1.2. - Simultaneous autoregressive models (SAR)

To be able to study an autocorrelation at a larger scale, other models must be used.

The SAR model is an autoregressive model.These models take spatial autocorrelation into account by using a neighborhood matrix specifying the relationship between the residuals at each location.

The SAR model allows to study directional processes, which, in ecology, are quite common ( ex : wind dispersal or stream flows).

The autoregressif process can be found in either the residuals of the data or in the response value. Depending on where this process is thought to be,three models are availble :

-   The **Error model**
-   The **Lag model**
-   The **Mix model**

A specific diagnostic can be made to chose between either one.

##### 3.1.2.1. Lagrange Multiplier diagnostic

##### 3.1.2.2. Lag models

In this model, we assume that the autoregressif process is in the response variable. 
As this model is general, this means that anything affecting our Y, will also affect its neighbor in some way, affecting us in return. This creates a feedback effect.

It would for exemple be liked a stone thrown in a lake. This creates waves that propagate to the whole lake.

The lag model is used to take into account a autoregressif process only occuring in the response variable. Therefore, the responsable variable argument in the model will include a term for the spatial autocorrelation : **ρW**

The model will take the form of :

**Y =**$\rho$**WY +X**$\beta$ + $\epsilon$

**ρ** is the autoregression parameter
**W** is the spatial weights matrix



##### 3.1.2.3. Error models

When using the error model, we assume that the autoregressif process is only in the residuals.

When dealing with such model, an interpretation may be that some spatially correlated variable are missing in the dataset.

this model takes the form of :

**Y = X**$\beta$ + $\lambda$**W**$\gamma$ + $\epsilon$

The term $\lambda$W represent the spatial structure with $\lambda$ being the spatial autoregression coefiscient. 
$\mu$ is the spatially dependant error term.

##### 3.1.2.4. Mixed models

**Y =** $\rho$**WY +X**$\beta$ + $\lambda$**W**$\gamma$ + $\epsilon$

### 3.2. - Non stationary process

**Graphically weighted models (GWM)**

Few methods exist to deal with non stationary processes

Bibliography :

F. Dormann, Carsten, Jana M. McPherson, Miguel B. Araújo, Roger Bivand, Janine Bolliger, Gudrun Carl, Richard G. Davies, et al. « Methods to Account for Spatial Autocorrelation in the Analysis of Species Distributional Data: A Review ». Ecography 30, nᵒ 5 (2007): 609‑28. https://doi.org/10.1111/j.2007.0906-7590.05171.x.

Smith, P. A. (1994). Autocorrelation in Logistic Regression Modelling of Species' Distributions. Global Ecology and Biogeography Letters, 4(2), 47--. doi:10.2307/2997753

Getis, Arthur. «Spatial Autocorrelation». In Handbook of Applied Spatial Analysis: Software Tools, Methods and Applications, édité par Manfred M. Fischer et Arthur Getis, 255‑78. Berlin, Heidelberg: Springer, 2010. https://doi.org/10.1007/978-3-642-03647-7_14.
