<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The Companion book a M1 MODE student should have! - Resampling methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">The Companion book a M1 MODE student should have!</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MarieEtienne/MODE_reproduciblescience" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./prior_course.html" rel="" target="">
 <span class="menu-text">Before the class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./instructions.html" rel="" target="">
 <span class="menu-text">Instructions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses-materials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Courses Materials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-courses-materials">    
        <li>
    <a class="dropdown-item" href="https://marieetienne.github.io/reproductibilite/_presentation/english_version.html" rel="" target="">
 <span class="dropdown-text">Git Intro</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-m1-mode-survival-book-by-the-m2-students" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">M1 MODE Survival book by the M2 students</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-m1-mode-survival-book-by-the-m2-students">    
        <li>
    <a class="dropdown-item" href="./AMV_chapter.html" rel="" target="">
 <span class="dropdown-text">Multivariate Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./linear_modelling.html" rel="" target="">
 <span class="dropdown-text">Linear modelling in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Mixed_models.html" rel="" target="">
 <span class="dropdown-text">Mixed models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./chapter_dependance.html" rel="" target="">
 <span class="dropdown-text">Dependent data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Matrix.html" rel="" target="">
 <span class="dropdown-text">Matrix models and applications in ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Chap_ODE.html" rel="" target="">
 <span class="dropdown-text">Ordinary Differential Equations in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./r_chapter_boostrapping_resampling.html" rel="" target="">
 <span class="dropdown-text">Resampling methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bayesian_modeles.html" rel="" target="">
 <span class="dropdown-text">Bayesian models in Ecology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./simple_chapter.html" rel="" target="">
 <span class="dropdown-text">A simple chapter with no code</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#general-introduction" id="toc-general-introduction" class="nav-link active" data-scroll-target="#general-introduction">General introduction</a></li>
  <li><a href="#confidence-interval-estimation-jackknife-and-bootstrap-methods" id="toc-confidence-interval-estimation-jackknife-and-bootstrap-methods" class="nav-link" data-scroll-target="#confidence-interval-estimation-jackknife-and-bootstrap-methods">Confidence interval estimation: Jackknife and Bootstrap methods</a>
  <ul class="collapse">
  <li><a href="#normally-distributed-sample" id="toc-normally-distributed-sample" class="nav-link" data-scroll-target="#normally-distributed-sample">Normally distributed sample</a></li>
  <li><a href="#non-normally-distributed-sample" id="toc-non-normally-distributed-sample" class="nav-link" data-scroll-target="#non-normally-distributed-sample">Non-normally distributed sample</a></li>
  <li><a href="#the-jackknife-resampling-method" id="toc-the-jackknife-resampling-method" class="nav-link" data-scroll-target="#the-jackknife-resampling-method">The Jackknife resampling method</a>
  <ul class="collapse">
  <li><a href="#principle-of-the-leave-one-out-jackknife-sinharay_jackknife_2010-petit_techniques_2022" id="toc-principle-of-the-leave-one-out-jackknife-sinharay_jackknife_2010-petit_techniques_2022" class="nav-link" data-scroll-target="#principle-of-the-leave-one-out-jackknife-sinharay_jackknife_2010-petit_techniques_2022">Principle of the leave-one-out Jackknife <span class="citation" data-cites="sinharay_jackknife_2010 petit_techniques_2022">(Sinharay 2010 ; Petit 2022)</span></a></li>
  <li><a href="#calculation-of-pseudo-values" id="toc-calculation-of-pseudo-values" class="nav-link" data-scroll-target="#calculation-of-pseudo-values">Calculation of pseudo-values</a></li>
  <li><a href="#statistical-test" id="toc-statistical-test" class="nav-link" data-scroll-target="#statistical-test">Statistical test</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval">Confidence interval</a></li>
  <li><a href="#r-package" id="toc-r-package" class="nav-link" data-scroll-target="#r-package">R package</a></li>
  <li><a href="#strengths-of-the-method" id="toc-strengths-of-the-method" class="nav-link" data-scroll-target="#strengths-of-the-method">Strengths of the method</a></li>
  <li><a href="#weaknesses-of-the-method" id="toc-weaknesses-of-the-method" class="nav-link" data-scroll-target="#weaknesses-of-the-method">Weaknesses of the method</a></li>
  </ul></li>
  <li><a href="#the-bootstrap-re-sampling-method" id="toc-the-bootstrap-re-sampling-method" class="nav-link" data-scroll-target="#the-bootstrap-re-sampling-method">The bootstrap re-sampling method</a>
  <ul class="collapse">
  <li><a href="#introduction-and-principle" id="toc-introduction-and-principle" class="nav-link" data-scroll-target="#introduction-and-principle">Introduction and Principle</a></li>
  <li><a href="#practice-and-application" id="toc-practice-and-application" class="nav-link" data-scroll-target="#practice-and-application">Practice and Application</a></li>
  <li><a href="#strengths-and-weaknesses" id="toc-strengths-and-weaknesses" class="nav-link" data-scroll-target="#strengths-and-weaknesses">Strengths and Weaknesses</a></li>
  <li><a href="#to-go-further" id="toc-to-go-further" class="nav-link" data-scroll-target="#to-go-further">To go further</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#permutation-tests" id="toc-permutation-tests" class="nav-link" data-scroll-target="#permutation-tests">Permutation Tests</a>
  <ul class="collapse">
  <li><a href="#foundations-of-permutation-tests" id="toc-foundations-of-permutation-tests" class="nav-link" data-scroll-target="#foundations-of-permutation-tests">Foundations of Permutation Tests</a>
  <ul class="collapse">
  <li><a href="#fundamental-principle" id="toc-fundamental-principle" class="nav-link" data-scroll-target="#fundamental-principle">Fundamental Principle</a></li>
  <li><a href="#parametric-tests-test-statistic-null-distribution-and-p-value" id="toc-parametric-tests-test-statistic-null-distribution-and-p-value" class="nav-link" data-scroll-target="#parametric-tests-test-statistic-null-distribution-and-p-value"><strong>Parametric tests</strong> : test statistic, null distribution and p-value</a></li>
  <li><a href="#permutation-test-test-statistic-null-distribution-and-p-value" id="toc-permutation-test-test-statistic-null-distribution-and-p-value" class="nav-link" data-scroll-target="#permutation-test-test-statistic-null-distribution-and-p-value">Permutation test : test Statistic, null distribution and p-value</a></li>
  </ul></li>
  <li><a href="#implementation-of-permutation-tests" id="toc-implementation-of-permutation-tests" class="nav-link" data-scroll-target="#implementation-of-permutation-tests">Implementation of Permutation Tests</a>
  <ul class="collapse">
  <li><a href="#test-steps" id="toc-test-steps" class="nav-link" data-scroll-target="#test-steps">Test Steps</a></li>
  <li><a href="#practical-examples" id="toc-practical-examples" class="nav-link" data-scroll-target="#practical-examples">Practical examples</a></li>
  </ul></li>
  <li><a href="#mantel-tests" id="toc-mantel-tests" class="nav-link" data-scroll-target="#mantel-tests">Mantel tests</a>
  <ul class="collapse">
  <li><a href="#uses" id="toc-uses" class="nav-link" data-scroll-target="#uses">Uses</a></li>
  <li><a href="#correspondence-distances-matrices" id="toc-correspondence-distances-matrices" class="nav-link" data-scroll-target="#correspondence-distances-matrices">Correspondence (distances) matrices</a></li>
  <li><a href="#mantels-test-application" id="toc-mantels-test-application" class="nav-link" data-scroll-target="#mantels-test-application">Mantel’s test application</a></li>
  </ul></li>
  <li><a href="#permutation-test-on-bootstrapped-data" id="toc-permutation-test-on-bootstrapped-data" class="nav-link" data-scroll-target="#permutation-test-on-bootstrapped-data">Permutation test on bootstrapped data</a></li>
  <li><a href="#conclusion-on-permutation-tests" id="toc-conclusion-on-permutation-tests" class="nav-link" data-scroll-target="#conclusion-on-permutation-tests">Conclusion on permutation tests</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Resampling methods</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Authors:</strong> Lucien Ricome, Youna Douchet, Pierre-Alexandre Quittet, Bastien Clémot</p>
<section id="general-introduction" class="level1">
<h1>General introduction</h1>
<p>While studying random variables, it is useful to know which statistical distribution they are following. Such knowledge allows to make inferences about the statistical population when only sub-samples are available. For instance, it is needed in order to calculate confidence intervals around an estimated statistic or to calculate p-values to test hypothesis. In other words, recognizing a statistical distribution of the sampled data is essential to estimate the reliability of estimations.<br>
Many well-studied statistical distributions can be useful in this situation, some of the most famous being the Normal distribution, the Poisson distribution or the Binomial distribution. Despite the diversity of studied distribution, sampled data distribution often differ, whether because they do not follow any studied statistical distribution or because too few data are available making it difficult to recognize any distribution.<br>
In this situation, resampling procedures become interesting. It is a non-parametric statistic which has many usages, such as calculating confidence intervals or estimating p-values. The principle of resampling is to “draw samples from the observed data to draw certain conclusions about the population of interest” <span class="citation" data-cites="sinharay_jackknife_2010">(<a href="#ref-sinharay_jackknife_2010" role="doc-biblioref">Sinharay 2010</a>)</span>. This chapter will discuss three resampling techniques: the jackknife, the bootstrap and the permutation (with a focus on the mantel test).</p>
<p>Before diving into the subject, let’s load some packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bootstrap)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(latex2exp)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ade4)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br>
</p>
</section>
<section id="confidence-interval-estimation-jackknife-and-bootstrap-methods" class="level1">
<h1>Confidence interval estimation: Jackknife and Bootstrap methods</h1>
<p>To illustrate the following methods, we’ll use the Iris RBase dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Original dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> iris</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
<p>Suppose we’re interested in determining the average width of the sepals in a wild population of Iris flowers. However, it’s practically impossible to measure the sepals of every single flower in the population. Instead, we’ve sampled and measured a specific number of individuals in the field. To simplify, let’s consider our Iris dataset as a representation of the complete wild population (which, in reality, is inaccessible) and select only a small number of individuals to mimic our field sampling.</p>
<section id="normally-distributed-sample" class="level3">
<h3 class="anchored" data-anchor-id="normally-distributed-sample">Normally distributed sample</h3>
<p>Let’s first imagine that we only sampled 100 individuals within our population.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our real population</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>irisPopulation <span class="ot">&lt;-</span> iris<span class="sc">$</span>Sepal.Width</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly sample 100 individuals</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>data_sample <span class="ot">&lt;-</span> irisPopulation[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">150</span>,<span class="dv">100</span>)]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> data_sample),<span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">8</span>)<span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Sepal width"</span>)<span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sepal width distribution (n=100)"</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-plot</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="fu">aes</span>(<span class="at">sample=</span>data_sample))<span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="fu">aes</span>(<span class="at">sample=</span>data_sample), <span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Normal theoretical quantiles"</span>)<span class="sc">+</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Sub-sample quantiles"</span>)<span class="sc">+</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Sepal width QQ-plot (n=100)"</span>) <span class="sc">+</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Print</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot1,plot2,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The sample being normally distributed, we can compute its mean (<span class="math inline">\(\mu\)</span>), as well as its confidence interval as below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sample mean</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"mu = "</span>,<span class="fu">mean</span>(data_sample),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mu =  3.08 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute confidence interval</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>low <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_sample)<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(data_sample)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(data_sample))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>high <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_sample)<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(data_sample)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(data_sample))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Lower bound : "</span>,<span class="fu">round</span>(low,<span class="dv">2</span>), <span class="st">"    Upper bound = "</span>,<span class="fu">round</span>(high,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lower bound :  2.99     Upper bound =  3.17</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Note: the 1.96 value comes from the normal distribution table to obtain a 95% confidence interval.</p>
</blockquote>
<p>Then, we can easily compare this result with the actual mean of our wild population, that theoretically we do not know:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute population mean</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"mean = "</span>,<span class="fu">mean</span>(irisPopulation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean =  3.057333</code></pre>
</div>
</div>
<p>The mean of our population falls within our confidence interval!</p>
</section>
<section id="non-normally-distributed-sample" class="level3">
<h3 class="anchored" data-anchor-id="non-normally-distributed-sample">Non-normally distributed sample</h3>
<p>Now, let’s consider that we were only able to sample 15 individuals within our wild population.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly sample 15 individuals</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>data_sample <span class="ot">&lt;-</span> irisPopulation[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">150</span>,<span class="dv">15</span>)]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> data_sample),<span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">8</span>)<span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Sepal width"</span>)<span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Sepal width distribution (n=15)"</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-plot</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="fu">aes</span>(<span class="at">sample=</span>data_sample))<span class="sc">+</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="fu">aes</span>(<span class="at">sample=</span>data_sample), <span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Normal theoretical quantiles"</span>)<span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Sub-sample quantiles"</span>)<span class="sc">+</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Sepal width QQ-plot (n=15)"</span>) <span class="sc">+</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Print</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot1,plot2,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This time, our sample size is too small, and its distribution is no longer normal. In this very common scenario, what options do we have to estimate a confidence interval around any of our parameters of interest, like the mean? This is where resampling methods get interesting.</p>
</section>
<section id="the-jackknife-resampling-method" class="level2">
<h2 class="anchored" data-anchor-id="the-jackknife-resampling-method">The Jackknife resampling method</h2>
<p>This method was first proposed by <span class="citation" data-cites="quenouille_approximate_1949">Quenouille (<a href="#ref-quenouille_approximate_1949" role="doc-biblioref">1949</a>)</span>. The name “Jackknife” comes from the fact that it is often referenced as a “quick and dirty” tool of statistics <span class="citation" data-cites="abdi_jackknife_2010">(<a href="#ref-abdi_jackknife_2010" role="doc-biblioref">Abdi and Williams 2010</a>)</span>. It means that it is usable in many situations but it is often not the best tool. The technique allows us to estimate a confidence interval for some statistics when the dataset is too small and/or when it does not follow a known distribution.</p>
<section id="principle-of-the-leave-one-out-jackknife-sinharay_jackknife_2010-petit_techniques_2022" class="level3">
<h3 class="anchored" data-anchor-id="principle-of-the-leave-one-out-jackknife-sinharay_jackknife_2010-petit_techniques_2022">Principle of the leave-one-out Jackknife <span class="citation" data-cites="sinharay_jackknife_2010 petit_techniques_2022">(<a href="#ref-sinharay_jackknife_2010" role="doc-biblioref">Sinharay 2010</a> ; <a href="#ref-petit_techniques_2022" role="doc-biblioref">Petit 2022</a>)</span></h3>
<p>The main goal of the jackknife method is to calculate a confidence interval around a statistic when classical statistics can not apply to the data.The principle is to create subsamples of the initial sample by successively removing some of the observations. Then, on each subsample, a pseudo-value will be calculated. With all the pseudo-values, it is possible to calculate an estimator of the statistic and to estimate its confidence interval.</p>
<p>The most famous jackknife is the the leave-one-out jackknife (or order 1 jackknife) for which all the subsamples contain all the observations except one. Concretely, for a sample of <span class="math inline">\(n\)</span> observations, there will be <span class="math inline">\(n\)</span> subsamples of size <span class="math inline">\((n-1)\)</span>. The <span class="math inline">\(i^{th}\)</span> subsample will be composed of observations from <span class="math inline">\(1\)</span> to <span class="math inline">\(n\)</span> minus the <span class="math inline">\(i^{th}\)</span> observation.</p>
<p>To illustrate, here is our sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data_sample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.7 2.9 2.8 3.0 2.8 3.0 3.0 3.8 3.3 3.2 2.8 3.0 3.6 3.8 2.5</code></pre>
</div>
</div>
<p>And we can represent some subsamples:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"1st subsample : </span><span class="sc">\n</span><span class="st">"</span>,data_sample[<span class="sc">-</span><span class="dv">1</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1st subsample : 
 2.9 2.8 3 2.8 3 3 3.8 3.3 3.2 2.8 3 3.6 3.8 2.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"4th subsample : </span><span class="sc">\n</span><span class="st">"</span>,data_sample[<span class="sc">-</span><span class="dv">4</span>], <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4th subsample : 
 3.7 2.9 2.8 2.8 3 3 3.8 3.3 3.2 2.8 3 3.6 3.8 2.5 </code></pre>
</div>
</div>
</section>
<section id="calculation-of-pseudo-values" class="level3">
<h3 class="anchored" data-anchor-id="calculation-of-pseudo-values">Calculation of pseudo-values</h3>
<p>After creating the subsamples, the next step is to calculate pseudo-values for each of the new subsamples. The formula for pseudo-values depend on the statistic of interest. In our case we want to estimate the mean, the formula will then be:</p>
<p><span class="math display">\[
v_{i} = n\overline{X} - (n-1)\overline{X}_{-i}
\]</span></p>
<p>with the following variables:</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(v_{i}\)</span></td>
<td>Pseudo value of the <span class="math inline">\(i^{th}\)</span> subsample</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
<td>Total number of observations</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\overline{X}\)</span></td>
<td>Mean of the initial sample</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\overline{X}_{-i}\)</span></td>
<td>Mean of the <span class="math inline">\(i^{th}\)</span> subsample, corresponding to all observations except the <span class="math inline">\(i{th}\)</span></td>
</tr>
</tbody>
</table>
<p>Let’s write a function which create the subsamples and calculate their pseudo values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function for pseudo-values</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pseudo_val <span class="ot">&lt;-</span> <span class="cf">function</span>(data, theta){</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># entry : data = the vector of data to which we want to apply the Jackknife</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># entry : theta = function for the statistic of interest</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># output : a vector of pseudo values for each subsample</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(data)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  mean_init <span class="ot">&lt;-</span> <span class="fu">theta</span>(data)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  pv <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,n) <span class="co">#to keep in memory each pseudo value</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    pv[i] <span class="ot">&lt;-</span> n<span class="sc">*</span>mean_init <span class="sc">-</span> (n<span class="dv">-1</span>)<span class="sc">*</span><span class="fu">theta</span>(data[<span class="sc">-</span>i])</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pv)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To try the function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function test</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>pv <span class="ot">&lt;-</span> <span class="fu">pseudo_val</span>(<span class="at">data =</span>  data_sample,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">theta =</span> mean)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.7 2.9 2.8 3.0 2.8 3.0 3.0 3.8 3.3 3.2 2.8 3.0 3.6 3.8 2.5</code></pre>
</div>
</div>
</section>
<section id="statistical-test" class="level3">
<h3 class="anchored" data-anchor-id="statistical-test">Statistical test</h3>
<p>The jackknife estimator <span class="math inline">\(\theta\)</span> of the mean will then be calculated as follow:</p>
<p><span class="math display">\[
\begin{align}
\hat{\theta} &amp; = \frac{\sum_{i=1}^{n}v_{i}}{n} \\
\hat{\theta} &amp; = \overline{v}
\end{align}
\]</span></p>
<p>It corresponds to the mean of the pseudo values <span class="math inline">\(v_i\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute mean of the pseudo-values</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mean_pv <span class="ot">&lt;-</span> <span class="fu">mean</span>(pv)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>mean_pv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.146667</code></pre>
</div>
</div>
<p>The Jackknife estimator <span class="math inline">\(\theta\)</span> obtained is 3.15. This technique supposes that the Jackknife estimator is normally distributed and its standard error is calculated as follow:</p>
<p><span class="math display">\[
\begin{align}
SE_\hat{X} &amp; = \sqrt{\frac{\sum_{i=1}^{n}(v_{i}-\overline{v})}{n(n-1)}} \\
SE_\hat{X} &amp; = \sqrt{\frac{\sigma_{v}^{2}}{n}}
\end{align}
\]</span></p>
<p>With <span class="math inline">\(\overline{v}\)</span> being the mean of the pseudo values (and the jackknife estimator).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute standard error</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(pv)<span class="sc">/</span><span class="fu">length</span>(pv))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>SE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1050472</code></pre>
</div>
</div>
</section>
<section id="confidence-interval" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval">Confidence interval</h3>
<p>From these we can calculate a confidence interval:</p>
<p><span class="math display">\[
[\, \overline{v} - 1.96 \, SE_\hat{X} ; \overline{v} + 1.96 \, SE_\hat{X} \,]
\]</span></p>
<blockquote class="blockquote">
<p>Note: the 1.96 value comes from the normal distribution table to obtain a 95% confidence interval.</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Lower bound :  2.94 
 Higher bound :  3.35</code></pre>
</div>
</div>
<p>The estimated Jackknife mean is <span class="math inline">\(3.15\)</span> with the following confidence interval : <span class="math inline">\([2.94\:;\:3.35]\)</span>. The real value <span class="math inline">\(\mu = 3.05\)</span> is captured within the bounds of the confidence interval which indicate the robustness of the estimation process.</p>
</section>
<section id="r-package" class="level3">
<h3 class="anchored" data-anchor-id="r-package">R package</h3>
<p>On r, functions already exist to automatically execute the Jackknife. For instance, in the package <code>bootstrap</code> <span class="citation" data-cites="tibshirani_bootstrap_2019">(<a href="#ref-tibshirani_bootstrap_2019" role="doc-biblioref">Tibshirani 2019</a>)</span>, there is a function jackknife. The function take as entry a vector containing the data (x) and a function indicating which statistic needs to be estimated (theta).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Package function</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>bootstrap <span class="sc">::</span> <span class="fu">jackknife</span>(<span class="at">x=</span> data_sample,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">theta =</span> <span class="cf">function</span>(x) <span class="fu">mean</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$jack.se
[1] 0.1050472

$jack.bias
[1] 0

$jack.values
 [1] 3.107143 3.164286 3.171429 3.157143 3.171429 3.157143 3.157143 3.100000
 [9] 3.135714 3.142857 3.171429 3.157143 3.114286 3.100000 3.192857

$call
bootstrap::jackknife(x = data_sample, theta = function(x) mean(x))</code></pre>
</div>
</div>
<p>The output of the function include the standard error (<code>$jack.se</code>) as describe above. It also include the bias (<code>$jack.bias</code>) which is the difference between the initial sample statistic and the jackknife estimated statistic. It is important to note that the output <code>$jack.values</code> does not correspond to the pseudo values but to the statistic of interest calculated on every subsample. In our example, it correspond to the mean of each subsample.</p>
</section>
<section id="strengths-of-the-method" class="level3">
<h3 class="anchored" data-anchor-id="strengths-of-the-method">Strengths of the method</h3>
<p>As seen precedently, the Jackknife allows to calculate a confidence intervall when data are not following a normal distribution and to estimate the bias induced when only a sample of the statistical population is observed. These two characteristic does not only apply to univariate estimators such as the mean. It can be used on correlation coefficients and regression parameters for instance <span class="citation" data-cites="sinharay_jackknife_2010">(<a href="#ref-sinharay_jackknife_2010" role="doc-biblioref">Sinharay 2010</a>)</span>. In that case, each subsample leave one observations out with all its associated variables. The jackknife method is peticularly interesting when it comes to make inferences about variance ratio. It can perform as good as the Fisher test if variables are normally distributed and better if they are not <span class="citation" data-cites="miller_jackknife">(<a href="#ref-miller_jackknife" role="doc-biblioref"><strong>miller_jackknife?</strong></a>–review_1974)</span>.<br>
The Jackknife method was a good tool in the last century as it was easy to apply manually but it is nowaday surpassed by other methods which emerged thanks to the evolution of computers.</p>
</section>
<section id="weaknesses-of-the-method" class="level3">
<h3 class="anchored" data-anchor-id="weaknesses-of-the-method">Weaknesses of the method</h3>
<p>This method is not always efficient, it is not recomanded for time series analysis where some time period are successively removed to create the subsample. Moreover it has little succes when it comes to the estimation of single order statistics (specific values in an ordered set of observations or data points) such as the median or the maximum <span class="citation" data-cites="miller_jackknife">(<a href="#ref-miller_jackknife" role="doc-biblioref"><strong>miller_jackknife?</strong></a>–review_1974)</span>. But for this last point, other jackknife can be used such as the deleted-d jackknife which perform better for the median. In this method, subsamples are of size <span class="math inline">\((n-d)\)</span> and there are <span class="math inline">\(\binom{n}{d}\)</span> subsamples.</p>
<p>For more informations about applications of the Jackknife you can read the paper: Jackknife a Review by Rupert G. Miller <span class="citation" data-cites="miller_jackknife">(<a href="#ref-miller_jackknife" role="doc-biblioref"><strong>miller_jackknife?</strong></a>)</span>–review_1974.</p>
<p><br>
</p>
</section>
</section>
<section id="the-bootstrap-re-sampling-method" class="level2">
<h2 class="anchored" data-anchor-id="the-bootstrap-re-sampling-method">The bootstrap re-sampling method</h2>
<section id="introduction-and-principle" class="level3">
<h3 class="anchored" data-anchor-id="introduction-and-principle">Introduction and Principle</h3>
<p>Now that we’ve thoroughly explored jackknife resampling in the previous section, let’s delve into another resampling technique: the bootstrap method.</p>
<p>Similar to jackknife, bootstrap aims to estimate descriptive parameters of a sample and assess the accuracy of these estimates for making inferences about the actual population. It is yet another statistical inference method that involves generating multiple datasets through resampling from the original dataset. Essentially, the concept revolves around using resampling techniques to create a probability distribution for a chosen parameter. This distribution, known as the empirical distribution function, serves as an estimation of the true probability distribution of our parameter in the population. In practice, similar to the earlier section, our objective here is to compute parameters of interest from our sample (such as mean, median, or even the <span class="math inline">\(R^2\)</span> of a regression, among others) and establish confidence intervals around these estimates.</p>
<p>The fundamental difference between jackknife and bootstrap lies in their resampling methodologies. In each of its <span class="math inline">\(i\)</span> iterations, bootstrap randomly resamples <span class="math inline">\(n\)</span> elements from an initial sample of <span class="math inline">\(n\)</span> data points with replacement. This leads to two crucial distinctions from the resampling method employed in jackknife: i) The new samples generated through bootstrap maintain the same size <span class="math inline">\(n\)</span> as the original dataset. ii) Given the sampling with replacement approach, a particular element can occur multiple times in a new sample or might not appear at all during the resampling process.</p>
<p>After generating these <span class="math inline">\(i\)</span> bootstrap samples, the intended statistical parameters are computed for each of these samples. As a result, we obtain a distribution of <span class="math inline">\(i\)</span> data points derived from these samples, forming what is known as our empirical distribution function. Subsequently, the analysis of this distribution allows us to estimate precision, particularly in establishing the confidence interval for our statistical parameters.</p>
</section>
<section id="practice-and-application" class="level3">
<h3 class="anchored" data-anchor-id="practice-and-application">Practice and Application</h3>
<p>If the previous introduction seemed a bit perplexing, don’t worry—we’ll use an example to illustrate this concept.</p>
<p>For this demonstration, we’ll once again consider our non-normally distributed sampling of 15 individuals. Let’s proceed with the calculation of the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Field sampling mean</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.146667</code></pre>
</div>
</div>
<p>So, we’ve obtained a mean value of 3.15, which is great. However, this mean value can’t be reliably generalized to the entire population because we lack information about the variability induced by the specific individuals we chose to sample. As highlighted in our previous code, we only sampled <span class="math inline">\(n=15\)</span> individuals in the field. Clearly, this limited sampling isn’t sufficient to confidently assert that our estimated mean is truly representative of the entire population. Hence, it becomes essential to gain insights into the variability of the mean we’ve just calculated. This is precisely where the bootstrap method comes into play.</p>
<p>We’ll now systematically apply our algorithm to resample the initial dataset obtained from our field sampling. This resampling process will be utilized to construct the probability distribution of our mean.</p>
<ol type="1">
<li><strong>bootstrap resampling iterations</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix our number of bootstrap iterations</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">1000</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an empty list to stock our resamplings</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>bootstrapSamples <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>,B)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap resampling algorithm</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Randomly sample n elements with replacement</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  bootstrapSamples[[i]] <span class="ot">&lt;-</span> <span class="fu">sample</span>(data_sample, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For pedagogical purposes, let’s examine a few resamples while comparing them to our initial field sampling dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our original field sampling</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(data_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.5 2.8 2.8 2.8 2.9 3.0 3.0 3.0 3.0 3.2 3.3 3.6 3.7 3.8 3.8</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A few resampling</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(bootstrapSamples[[<span class="dv">5</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.8 2.8 2.8 3.0 3.0 3.0 3.0 3.2 3.3 3.3 3.6 3.6 3.6 3.8 3.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(bootstrapSamples[[<span class="dv">777</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.8 2.8 2.8 2.8 2.8 2.9 3.0 3.0 3.0 3.0 3.2 3.2 3.3 3.8 3.8</code></pre>
</div>
</div>
<p>Observe how certain values are repeated more frequently than in our initial dataset. Additionally, note that some values aren’t sampled at all. For instance, the value 2.5 appeared only once in our initial set and consequently was seldom or perhaps never resampled. Conversely, the value 2.8 was more prevalent in our initial dataset and consequently was sampled more frequently</p>
<ol start="2" type="1">
<li><strong>Compute mean for every resampled datasets</strong></li>
</ol>
<p>Now, we’ll compute the parameter of interest for each of our resampled datasets. This process will yield our set of <span class="math inline">\(i=1000\)</span> mean values, which we’ll utilize to construct our empirical distribution in the subsequent step.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute mean for each bootstrap samples</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>iterationMeans <span class="ot">&lt;-</span> <span class="fu">sapply</span>(bootstrapSamples, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li><strong>Plot the probability distribution</strong></li>
</ol>
<p>The computation of the distribution for our parameter of interest is complete. We can now proceed to plot it, providing us with an understanding of the variability surrounding our estimated mean value.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability distribution plot</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(iterationMeans), <span class="fu">aes</span>(<span class="at">x =</span> iterationMeans)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="fl">0.05</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density))</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">fill =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">mean</span>(data_sample),</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">1.5</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Empirical probability distribution of mean values"</span>,</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean"</span>,</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>Hence, this probability distribution provides us with insights into the variability around the mean value estimated from our field sampling. As anticipated, and as indicated by the red dashed line, this distribution is centered around the estimated mean value.</p>
<ol start="4" type="1">
<li><strong>Compute Confidence Interval around our mean estimate</strong></li>
</ol>
<p>Recall the primary objective of the bootstrap method: to assess the precision of our parameter estimation to make inferences about the broader population. To accomplish this, we’ll utilize the bootstrap percentiles. For instance, suppose we aim to calculate the 95% Confidence Interval. In this case, we’ll allocate 5% of the error evenly on both sides of our distribution, corresponding to the values at the 2.5th and 97.5th percentiles in our empirical distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get percentile 2.5%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(iterationMeans, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5%    97.5% 
2.966667 3.333500 </code></pre>
</div>
</div>
<p>And thus, we’ve successfully obtained our confidence interval for the mean estimation: <span class="math inline">\(2.97 \leq \overline{x} \leq 3.33\)</span>.</p>
<p>For educational purposes, let’s proceed to plot these percentiles in green.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability distribution plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(iterationMeans), <span class="fu">aes</span>(<span class="at">x =</span> iterationMeans)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="fl">0.05</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density))</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">fill =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">mean</span>(data_sample),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">quantile</span>(iterationMeans, <span class="at">probs =</span> <span class="fl">0.025</span>),</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"darkolivegreen4"</span>,</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">1.5</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">quantile</span>(iterationMeans, <span class="at">probs =</span> <span class="fl">0.975</span>),</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"darkolivegreen4"</span>,</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">1.5</span></span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Empirical probability distribution of mean values"</span>,</span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean"</span>,</span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb41-32"><a href="#cb41-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li><strong>Compare with population mean value</strong></li>
</ol>
<p>The bootstrap resampling method has facilitated the construction of a confidence interval around our mean estimate with a 5% margin of error. Now, let’s compare this interval with the actual value of our Iris population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(irisPopulation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.057333</code></pre>
</div>
</div>
<p>The actual sepal width mean of our population falls within the bounds of our confidence interval, which is highly encouraging! Comparing it to the interval estimated using the jackknife method, we notice that this interval is narrower and more precise. Consequently, we’ve effectively inferred information about the population mean in a scenario where we had limited data, made no normality assumptions, and where the standard computation of confidence intervals might not have been sufficiently robust and a</p>
</section>
<section id="strengths-and-weaknesses" class="level3">
<h3 class="anchored" data-anchor-id="strengths-and-weaknesses">Strengths and Weaknesses</h3>
<p>As we’ve seen, bootstrap is a powerful resampling technique used in statistics for estimating the precision of parameters. One of its primary advantages lies in its versatility across a wide spectrum of statistical estimations. Indeed, this resampling technique is applicable to various parameters, such as mean, variance, regression coefficients, and more. Furthermore, this method is particularly robust in handling complex data structure without strict distributional assumptions, meaning that it can easily works with non-normally distributed datasets with little observations, which is really relevant in real-word scenarios. In those cases, bootstrap ends up being more accurate than the standard intervals obtained under normality assumption.</p>
<p>However, one significant concern is its computational intensity, especially noticeable with larger datasets or complex models. Generating numerous bootstrap samples can demand, in certain cases, substantial computing resources. Additionally, bootstrap might display biased estimation of the accuracy of estimates, depending on whether or not the sampling dataset is representative of the actual population.</p>
<p>Overall, bootstrap’s major advantages lie in its broader applicability across various statistical estimations, but which comes with higher computational demands. In contrast, Jackknife might be less versatile, but tends to offer a better computational efficiency and less biased parameters, making it a favorable choice under certain conditions.</p>
</section>
<section id="to-go-further" class="level3">
<h3 class="anchored" data-anchor-id="to-go-further">To go further</h3>
<p>This section on the bootstrap method offers a fundamental understanding, providing explicit R scripts for pedagogical purposes. If you find yourself needing to utilize bootstrap, we highly recommend exploring the capabilities of the precedently presented <code>bootstrap</code> R package, which streamlines bootstrap implementation. Moreover, the bootstrap method extends beyond basic parameter estimation, offering various derivatives and applications catering to diverse needs:</p>
<ul>
<li><strong>Parametric bootstrap:</strong> Assumes a specific parametric distribution, generating bootstrap samples from this fitted distribution and allowing inference within a particular statistical model.</li>
<li><strong>Smooth bootstrap:</strong> Incorporates smoothing techniques to reduce variability in resampling, ideal for noisy or irregular data.</li>
<li><strong>Bayesian bootstrap:</strong> Generates bootstrap samples from posterior distributions, useful for uncertainty estimation in Bayesian analysis (see more in Bayesian chapter of this book).</li>
</ul>
<p>Lastly, bootstrap resampling isn’t limited to parameter estimation. It can also be employed to assess statistical tests, a topic we’ll delve into in our upcoming section.</p>
<p><br>
</p>
</section>
</section>
</section>
<section id="permutation-tests" class="level1">
<h1>Permutation Tests</h1>
<p>Permutation tests are a robust statistical tool for comparing groups and assessing the impact of one variable on another. In contrast to bootstrap methods that generate confidence intervals, their aim is to calculate a p-value, providing a basis for making statistical conclusions. What sets permutation tests apart is that, unlike some other tests, they don’t depend on specific assumptions about the data distribution. This makes them particularly sturdy, especially in situations where the number of data points is limited. Permutation tests are straightforward to understand, easy to put into action, and their resilience makes them highly practical for real-world applications.</p>
<section id="foundations-of-permutation-tests" class="level2">
<h2 class="anchored" data-anchor-id="foundations-of-permutation-tests">Foundations of Permutation Tests</h2>
<section id="fundamental-principle" class="level3">
<h3 class="anchored" data-anchor-id="fundamental-principle">Fundamental Principle</h3>
<p>Permutation tests differ from classical statistical tests such as Student’s t-test or the <span class="math inline">\(\chi\)</span> -square test in that they do not rely on specific assumptions about the distribution of data. Unlike traditional tests that assume a theoretical distribution of the test statistic under the null hypothesis, often based on well-known laws like the Gaussian distribution, permutation tests empirically generate this theoretical distribution directly from the data. This categorizes them as exact tests and non-parametric tests.</p>
<p>According to the central limit theorem, repeating a large number of observations of a random variable (in this case, the test statistic) leads to a Gaussian distribution. This distribution allows us to position the observed test statistic (calculated on our sample) and determine the significance of the effect of our explanatory variables. In other words, we generate a large number of permutations of the observations, calculate the test statistic for each permutation, and then compare the observed statistic to this null distribution. We’ll get into some reminder on what is the statistic of a test, a null distribution and a how p-values are generated to dive into the world of permutation test.</p>
</section>
<section id="parametric-tests-test-statistic-null-distribution-and-p-value" class="level3">
<h3 class="anchored" data-anchor-id="parametric-tests-test-statistic-null-distribution-and-p-value"><strong>Parametric tests</strong> : test statistic, null distribution and p-value</h3>
<p>The test statistic is a numerical measure used to evaluate whether observed differences between groups in a study are statistically significant. It quantifies the gap between observed and randomly attributable observations. In a very simplistic way, we could say they allow to determine the extent to which the effect we observe with our experimental design could be attributable to chance. Here are some familiar test statistics you’ve likely encountered in your fruitful scientific career:</p>
<p><span class="math display">\[
\begin{align*}
F [\text{ANOVA}] &amp;: \quad F = \frac{MS_{\text{between}}}{MS_{\text{within}}} \quad \sim \mathcal{F}(df_{\text{between}}, df_{\text{within}}) \\
\\
t [\text{Student's t-test}] &amp;: \quad t = \frac{\bar{X}_1 - \bar{X}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}} \quad \sim t(df) \\
\\
\chi^2 [\text{$\chi^2$ Test}] &amp;: \quad \chi^2 = \sum \frac{(O_i - E_i)^2}{E_i} \quad \sim \chi^2(df) \\
\end{align*}
\]</span></p>
<p>With <span class="math inline">\(MS\)</span> as the mean square error, <span class="math inline">\(df\)</span> as the degrees of freedom, <span class="math inline">\(\bar{X}_i\)</span> as the mean of group <span class="math inline">\(i\)</span>, <span class="math inline">\(s^2_i\)</span> as the variance of group <span class="math inline">\(i\)</span>, <span class="math inline">\(n_i\)</span> as the number of replicates in group <span class="math inline">\(i\)</span>, <span class="math inline">\(O_i\)</span> as the observed <span class="math inline">\(\chi^2\)</span> distance, and <span class="math inline">\(E_i\)</span> as the expected <span class="math inline">\(\chi^2\)</span> distance.</p>
<p>You may recall that these statistics typically follow well-established distributional laws. But what does “known distributional laws” mean? It means we know the probability of a given value of a statistical test (referred to as its probability distribution) based on certain parameter values (e.g., the degree of freedom for Student distribution). Hence, the term parametric tests! The probability distribution of a statistic under a specific parameter, such as the degrees of freedom [ddl] for a Student’s t-distribution, forms the basis of the null hypothesis in statistical testing. The null hypothesis represents the idea that any observed differences or effects are purely due to chance variation within this established distribution. By comparing our calculated statistic (the one coming from our data) to the expected distribution under the null hypothesis, we can assess whether the observed result is consistent with what we would anticipate if there were no real effect. In essence, this comparison allows us to make informed decisions about the significance of our findings in the context of the null hypothesis. Then, the p-value merely represent the probability of observe your observed statistic under this null distribution / hypothesis.</p>
<p>In simpler terms, when we talk about “known distributional laws,” it means we know how likely certain test results are under specific conditions. In the testing process, the null hypothesis proposes that any observed differences are merely random occurrences within the expected pattern. By comparing our actual result to what we would expect by chance, the p-value indicates the probability of our result occurring in this random scenario. If the likelihood of this chance scenario is highly improbable (typically below the 5% threshold), we reject the assumption that differences are random (reject the null hypothesis!). Conversely, if the chance scenario is ‘too probable’ (more than 5%), we conclude that it’s not safe to assert our effect is not due to chance and refrain from rejecting the null hypothesis.</p>
<p>Enough talking, let’s illustrate with a graphical example. Let’s imagine we want to compare the sepal length between the species <em>I. virginica</em> and <em>I. versicolor</em> using a Student test. First, we plot the data:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p><em>I. virginica</em> seems to have slightly bigger sepal length than <em>I. versicolor</em>. Assuming all conditions are met, we perform a Student test to determine the significance of the difference observed:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"virginica"</span>],</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>],</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> F,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> T,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  iris$Sepal.Length[iris$Species == "virginica"] and iris$Sepal.Length[iris$Species == "versicolor"]
t = 5.6292, df = 98, p-value = 1.725e-07
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.4221484 0.8818516
sample estimates:
mean of x mean of y 
    6.588     5.936 </code></pre>
</div>
</div>
<p>Here we observe a significance difference between the species <em>I. virginica</em> and <em>I. versicolor</em> with <em>I. virigina</em> having bigger sepal length than <em>I. versicolor</em>.</p>
<p>Let’s get more precise on how do we get the p-value associated with this comparison and make the connection with what we saw earlier in this endless introduction paragraph. The Student distribution under null hypothesis (<span class="math inline">\(H0\)</span>) is defined according the parameter ‘degree of freedom’, here equal to <span class="math inline">\(df = 98\)</span>. Let’s plot this <span class="math inline">\(H0\)</span> probability distribution of the test we just performed:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Density distribution of the t statistic</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dt</span>(<span class="at">x =</span> x, <span class="at">df =</span> <span class="dv">98</span>),</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>),</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Density"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"t"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.axis =</span> <span class="fl">1.5</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>This distribution shows the probability associated with each value of the <span class="math inline">\(t\)</span> statistic for a similar degree of freedom (<span class="math inline">\(98\)</span>) with our data. It contains all the probabilities of the statistical tests assuming that ‘sepal length means do not differ between both species.’ Now, our task is to position the <span class="math inline">\(t_{obs}\)</span> representing the observed test statistic we calculated from our data, which is <span class="math inline">\(t_{obs} = 5.6\)</span>, in this null distribution. The goal is to figure out how probable is the value 5.6 in the probability distribution of the Student’s t-distribution with <span class="math inline">\(df=98\)</span>.</p>
<p>Since we conducted a two-sided test, meaning no a priori assumption about the direction of the effect, we split the 5% of the <span class="math inline">\(\alpha\)</span> threshold between both sides of the distribution. We will visually identify the values of <span class="math inline">\(t\)</span> for which less than <span class="math inline">\(2.5%\)</span> and more than <span class="math inline">\(97.5%\)</span> of values are respectively below and above these thresholds. If our <span class="math inline">\(t_{observed}\)</span> falls below the <span class="math inline">\(2.5%\)</span> or above the <span class="math inline">\(97.5%\)</span> threshold, we consider the observed difference statistically significant.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Density distribution of the t statistic</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dt</span>(<span class="at">x =</span> x, <span class="at">df =</span> <span class="dv">98</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Density"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"t"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="fl">1.5</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.axis =</span> <span class="fl">1.5</span>,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantile function : values of t associated of a two sided test</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">df =</span> <span class="dv">98</span>)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(threshold[<span class="dv">1</span>], threshold[<span class="dv">2</span>]), <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Color the area of significance</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="at">length.out =</span> <span class="dv">100000</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">98</span>)</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(x[x<span class="sc">&lt;=</span>threshold[<span class="dv">1</span>]], threshold[<span class="dv">1</span>]), <span class="fu">c</span>(y[x<span class="sc">&lt;=</span>threshold[<span class="dv">1</span>]], y[x <span class="sc">==</span> <span class="fu">max</span>(x)]), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(x[x<span class="sc">&gt;=</span>threshold[<span class="dv">2</span>]], threshold[<span class="dv">2</span>]), <span class="fu">c</span>(y[x<span class="sc">&gt;=</span>threshold[<span class="dv">2</span>]], y[x <span class="sc">==</span> <span class="fu">max</span>(x)]), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">3.7</span>, <span class="at">y =</span> <span class="fl">0.3</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$quantile(1 - </span><span class="sc">\\</span><span class="st">frac{alpha}{2})$"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> .<span class="dv">9</span>)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="sc">-</span><span class="fl">3.5</span>, <span class="at">y =</span> <span class="fl">0.3</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$quantile(</span><span class="sc">\\</span><span class="st">frac{alpha}{2})$"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> .<span class="dv">9</span>)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Placing the t_obs value</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">5.6</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fl">0.1</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$t_{obs}$"</span>), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>With <span class="math inline">\(\alpha\)</span> the type-I error (here 5%). Hence <span class="math inline">\(t_{obs}\)</span> is in the significance area (in red) meaning the difference is significant. Now we have all the reminders we need to master the conception of permutation test.</p>
</section>
<section id="permutation-test-test-statistic-null-distribution-and-p-value" class="level3">
<h3 class="anchored" data-anchor-id="permutation-test-test-statistic-null-distribution-and-p-value">Permutation test : test Statistic, null distribution and p-value</h3>
<p>The method for inference in permutation test is very similar in conception in the sense they are based on a statistic test, a null hypothesis and the generation of a p-value. In permutation test, the statistic test <span class="math inline">\(P_{obs}\)</span> have to be defined. It can basically be anything that link the different conditions of our experimental design. For example, if we want to compare an effect on a response variable dispatch into two conditions (e.g.&nbsp;levels of a preditive categorical variable), the statistic test could be the difference of the sums, the variances, means… of the values of both groups. For example, let’s consider a difference in means as statistic test:</p>
<p><span class="math display">\[
P = \bar{X}_1 - \bar{X}_2
\]</span></p>
<p>where (<span class="math inline">\(\bar{X}_1\)</span>) and (<span class="math inline">\(\bar{X}_2\)</span>) are the means of the two groups compared. In the absence of a predefined theoretical distribution, like the Student distribution mentioned earlier, we need to determine where to place the observed test statistic <span class="math inline">\(P_{obs}\)</span>. To do this, we construct a null distribution. This involves randomly shuffling each value between the two groups and calculating the test statistic <span class="math inline">\(P_{H0}\)</span> for this newly arranged dataset. Essentially, each data point is randomly assigned to either group 1 or group 2, reflecting the idea that belonging to one group or the other has no effect on the response variable since the data has been randomly shuffled.</p>
<p>We repeat this process many times, extracting the <span class="math inline">\(P_{H0}\)</span> each time to build a distribution of the test statistic under the null hypothesis (<span class="math inline">\(H_0\)</span>). According to the central limit theorem, which suggests that the distribution of random variables repeated a large number of times tends to follow a bell curve, regardless of the original distribution shape of those variables. Once we have this null distribution, we follow a similar procedure as described earlier for parametric tests. We compare our <span class="math inline">\(P_{obs}\)</span> to this null distribution and determine its probability. Just like in parametric tests, in permutation tests, the p-value corresponds to the number of iterations where <span class="math inline">\(P_{H0}\)</span> is above or below (depending on the direction of our hypothesis) the <span class="math inline">\(P_{obs}\)</span> value.</p>
<p><br>
</p>
</section>
</section>
<section id="implementation-of-permutation-tests" class="level2">
<h2 class="anchored" data-anchor-id="implementation-of-permutation-tests">Implementation of Permutation Tests</h2>
<section id="test-steps" class="level3">
<h3 class="anchored" data-anchor-id="test-steps">Test Steps</h3>
<p>Typical steps to implement a permutation test include:</p>
<ol type="1">
<li><p>Formulate null and alternative hypothesis</p></li>
<li><p>Determine and calculate the test statistic from the observed data</p></li>
<li><p>Generate a large amount of permutations on independent unit of the data and calculate the test statistic for each permutation</p></li>
<li><p>Compare the observed statistic to the null distribution of test statistics</p></li>
<li><p>Conclude on accepting or rejecting the null hypothesis</p></li>
</ol>
</section>
<section id="practical-examples" class="level3">
<h3 class="anchored" data-anchor-id="practical-examples">Practical examples</h3>
<p>Here we’ll present an example of permutation test on independent data and paired data.</p>
<section id="independent-data-e.g.-comparison-of-means" class="level4">
<h4 class="anchored" data-anchor-id="independent-data-e.g.-comparison-of-means">Independent data (e.g.&nbsp;comparison of means)</h4>
<p>Let’s take an example to test if the difference in means between two groups is statistically significant. We’ll use the mean statistic as described earlier and pose the same question asked in the Student test example: “Is the sepal length of the genera <em>I. virginica</em> and <em>I. versicolor</em> different?” However, in this case, we’ll only use 20 randomly chosen observations to illustrate how these tests can maintain high statistical power even with a low number of replicates compared to parametric tests and how we can reach to the same conclusion as before with the whole data set with minimal sample size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># SELECT THE VARIABLES OF INTEREST</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>filter_data <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"virginica"</span> <span class="sc">|</span> Species <span class="sc">==</span> <span class="st">"versicolor"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co"># TAKE A SUBSET</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>sub_data <span class="ot">&lt;-</span> filter_data[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(filter_data), <span class="at">size =</span> <span class="dv">20</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot the sub-dataset.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>In this example, the data doesn’t follow a Gaussian distribution, as one might expect with such a small data set. It’s important to note that we employed a Student test here for illustration and comparison with the previous tests using the full data set.</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T </span><span class="al">TEST</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sub_data<span class="sc">$</span>Sepal.Length[sub_data<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"virginica"</span>],</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> sub_data<span class="sc">$</span>Sepal.Length[sub_data<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>],</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> F,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> T,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  sub_data$Sepal.Length[sub_data$Species == "virginica"] and sub_data$Sepal.Length[sub_data$Species == "versicolor"]
t = 0.95304, df = 18, p-value = 0.3532
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.3011112  0.8011112
sample estimates:
mean of x mean of y 
     6.36      6.11 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MANN-WHITNEY </span><span class="al">TEST</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(sub_data<span class="sc">$</span>Sepal.Length[sub_data<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"virginica"</span>],</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  sub_data<span class="sc">$</span>Sepal.Length[sub_data<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>],</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE 
FALSE   Wilcoxon rank sum test with continuity correction
FALSE 
FALSE data:  sub_data$Sepal.Length[sub_data$Species == "virginica"] and sub_data$Sepal.Length[sub_data$Species == "versicolor"]
FALSE W = 66, p-value = 0.239
FALSE alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Hence, neither of the tests for comparing means indicates a significant difference in sepal length between the two species whether we use a Student test, which assumes normality (although not met in this case), or the Mann-Whitney non-parametric test. This is where permutation test becomes interesting. They have a great power even when the number of replicates is low. Let’s see how we proceed.</p>
<p>Permuted data can be created, among various methods, by randomly assigning levels of the variable ‘species’ to sepal length values using the sample function. Subsequently, the difference of means is calculated to determine p_h0, representing the statistic for the permuted data (<span class="math inline">\(P_{H0}\)</span>—the difference of means of sepal length in the permuted data). This process is repeated for a specified number of iterations (<span class="math inline">\(i\)</span>), generating <span class="math inline">\(i\)</span> values of <span class="math inline">\(P_{H0}\)</span> and resulting in the null_distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># INITIAL PARAMETERS</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>iteration <span class="ot">&lt;-</span> <span class="dv">10000</span>  <span class="co"># number of iteration</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="ot">&lt;-</span> <span class="fu">c</span>()  <span class="co"># storage of the statistic for permuted data</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ALGORITHM</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iteration)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Randomly assign a specie level to each observation </span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  permuted_species <span class="ot">&lt;-</span> <span class="fu">with</span>(sub_data, <span class="fu">sample</span>(Species, <span class="at">replace =</span> F))</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Difference of means of both species under h0</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>  p_h0 <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> sub_data<span class="sc">$</span>Sepal.Length, <span class="at">INDEX =</span> permuted_species, <span class="at">FUN =</span> mean)[<span class="st">"virginica"</span>] <span class="sc">-</span> </span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tapply</span>(<span class="at">X =</span> sub_data<span class="sc">$</span>Sepal.Length, <span class="at">INDEX =</span> permuted_species, <span class="at">FUN =</span> mean)[<span class="st">"versicolor"</span>]</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Add to null distribution</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  null_distribution[i] <span class="ot">&lt;-</span> p_h0</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a><span class="co"># CALCULATION OF THE OBSERVED STATISTIC</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>p_obs <span class="ot">&lt;-</span> <span class="fu">with</span>(iris, <span class="fu">mean</span>(Sepal.Length[Species <span class="sc">==</span> <span class="st">"virginica"</span>]) <span class="sc">-</span> <span class="fu">mean</span>(Sepal.Length[Species <span class="sc">==</span> <span class="st">"versicolor"</span>]))</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"P_obs = "</span>, p_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P_obs = 0.652"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Note : here we use <code>replace = F</code> in the <code>sample</code> function to keep the same number of replicates in each levels of species.</p>
</blockquote>
<p>So here we have a <span class="math inline">\(P_{obs}\)</span> value of 0.652. We can now plot the null distribution we generated with the permuted data and compare our observed statistic <span class="math inline">\(P_{obs}\)</span> with the null distribution. Let’s plot it to have a visual support on how permutation test works.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CALCULATE SIGNIFICANCE THRESHOLD</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>bornes <span class="ot">&lt;-</span> <span class="fu">quantile</span>(null_distribution,<span class="fu">c</span>(.<span class="dv">025</span>,.<span class="dv">975</span>))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># VISUALISATION</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(null_distribution,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(null_distribution) <span class="sc">-</span> <span class="fl">0.15</span>, <span class="dv">1</span>),</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">TeX</span>(<span class="st">"$P_{H0}$"</span>),</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="fl">1.5</span>,</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># POSITION THRESHOLD </span></span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="at">v =</span> bornes, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">text</span>(<span class="at">x =</span> <span class="fl">0.3</span>, <span class="at">y =</span> <span class="dv">1350</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$quantile(1 - </span><span class="sc">\\</span><span class="st">frac{alpha}{2})$"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">text</span>(<span class="at">x =</span> <span class="sc">-</span><span class="fl">0.65</span>, <span class="at">y =</span> <span class="dv">1350</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$quantile(</span><span class="sc">\\</span><span class="st">frac{alpha}{2})$"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># POSITION P_OBS</span></span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="at">v =</span> p_obs, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"darkolivegreen4"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">text</span>(<span class="at">x =</span> .<span class="dv">75</span>, <span class="at">y =</span> <span class="dv">1400</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$P_{obs}$"</span>), <span class="at">col =</span> <span class="st">"darkolivegreen4"</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As anticipated by the central limit theorem, the distribution of the statistic we use, repeated 10,000 times, follows a normal distribution. It’s evident that our observed statistic calculated on the data (<span class="math inline">\(P_{obs}\)</span>) stands out from the null distribution. Since we didn’t assume any specific direction for the difference (i.e.&nbsp;two sided test), we can determine the p-value as the number of absolut permuted observations (<span class="math inline">\(|P_{H0}|\)</span>) greater than the absolute value of <span class="math inline">\(P_{obs}\)</span>, divided by the number of iterations:</p>
<p><span class="math display">\[
\text{p-value} = \frac{\text{Number of } \big|P_{H0}\big| &gt; \big|P_{obs}\big|}{\text{Number of iterations}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(null_distribution) <span class="sc">&gt;</span> <span class="fu">abs</span>(p_obs)) <span class="sc">/</span> iteration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0037</code></pre>
</div>
</div>
<p>Here, the p-value of the test is 0.0037, meaning the test statistic observed <span class="math inline">\(P_{obs}\)</span> falls into the non-significant area only 3.7% of the time. Thus, we conclude the difference between both means is significant at a threshold <span class="math inline">\(5\%%\)</span> and that <em>I. virginica</em> has bigger sepal length than <em>I. versicolor</em>.</p>
<p><br>
</p>
</section>
<section id="paired-data-e.g.-comparison-of-correlation" class="level4">
<h4 class="anchored" data-anchor-id="paired-data-e.g.-comparison-of-correlation">Paired data (e.g.&nbsp;comparison of correlation)</h4>
<p>In this section, we’ll demonstrate how to conduct a permutation test on paired data using the iris data set. For this purpose, we’ll imagine a scenario where a fertilizer has been applied to each individual plant. The question will still focus on sepal length, exploring whether the fertilizer induces sepal length growth in a before-and-after experimental paradigm. Consequently, the data are paired by individuals. To ensure the independence of each unit of permutation, we must constrain how values are permuted <strong>within</strong> individuals. Unlike previous permutation procedures where all data were shuffled together, here we need to permute the data within each individual to account for the non-independence of the measures within each individual.</p>
<p>To simplify the procedure, we will only consider the species <em>I. versicolor</em>. Let’s create the sub-data and generate the new variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># FILTERING DATASET FOR VERSICOLOR</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>data_versicolor <span class="ot">&lt;-</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"versicolor"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># GENERATION OF THE NEW VARIABLE </span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Generation of the new variable Sepal.Length.T2 drawn drom normal distribution</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>Sepal.Length.T2 <span class="ot">&lt;-</span> <span class="fu">round</span>(</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">runif</span>(<span class="fu">nrow</span>(data_versicolor), <span class="at">min =</span> .<span class="dv">8</span>, <span class="at">max =</span> <span class="fl">1.2</span>) <span class="sc">*</span> data_versicolor<span class="sc">$</span>Sepal.Length,</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">1</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Adding the new variable to the dataset</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>data_versicolor <span class="ot">&lt;-</span> </span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>  data_versicolor <span class="sc">%&gt;%</span> </span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sepal.Length.T1 =</span> Sepal.Length,</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">Sepal.Length.T2 =</span> Sepal.Length.T2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot this relation:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  data_versicolor<span class="sc">$</span>Sepal.Length.T1,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  data_versicolor<span class="sc">$</span>Sepal.Length.T2,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"orange"</span>),</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Sepal Length"</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">""</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"T1"</span>, <span class="st">"T2"</span>),</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">9</span>),</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.axis =</span> <span class="fl">1.5</span>,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>According to the visualization, the effect of the fertilizer does not seem to have a clear effect on the sepal length.</p>
<p>Let’s follow step by step the permutation procedure :</p>
<ol type="1">
<li><p><strong>Formulate null and alternative hypotheses</strong></p>
<ul>
<li><p><strong>H1</strong> : the fertilizer has a positive effect on the sepal length, sepal measure at T2 is expected to be greater than T1</p></li>
<li><p><strong>H0</strong> : the fertilizer has no effect, no differences between T1 and T2</p></li>
</ul></li>
<li><p><strong>Determine and calculate the test statistic from the observed data</strong></p>
<p>To illustrate another example of statistic, we’ll use the difference in <strong>sum</strong> of each column to assess significance :</p>
<p><span class="math display">\[
P = \sum_{i}^n \text{Sepal length T1}_i - \sum_{i}^n \text{Sepal length T2}_i
\]</span></p>
<p>As long as the statistic enable comparing both conditions, it will work ! That is part of the magic of permutation test. We calculate the test statistic for <span class="math inline">\(P_{obs}\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>p_obs <span class="ot">&lt;-</span> <span class="fu">sum</span>(data_versicolor<span class="sc">$</span>Sepal.Length.T1) <span class="sc">-</span> <span class="fu">sum</span>(data_versicolor<span class="sc">$</span>Sepal.Length.T2) </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>p_obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.6</code></pre>
</div>
</div></li>
<li><p><strong>Generate a large amount of permutations on independent unit of the data and calculate the test statistic for each permutation</strong></p>
<p>Given the paired nature of the data, we will randomly shuffle the values of the variable Sepal Length <strong>within</strong> each individual to construct the null hypothesis. Instead of permuting data in the entire column, as done before in the case of independent data, we will permute by row to ensure that the permutation is constrained by individual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># INITIAL PARAMETERS</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>iteration <span class="ot">&lt;-</span> <span class="dv">10000</span>  <span class="co"># number of iteration</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="ot">&lt;-</span> <span class="fu">c</span>()  <span class="co"># storage of the statistic for permuted data</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ALGORITHM</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iteration)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Randomly assign age data witihin individual modality</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  permuted_data <span class="ot">&lt;-</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t</span>(<span class="fu">apply</span>(</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">X =</span> data_versicolor[<span class="fu">c</span>(<span class="st">"Sepal.Length.T1"</span>, <span class="st">"Sepal.Length.T2"</span>)],</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">MARGIN =</span> <span class="dv">1</span>,</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">FUN =</span> sample,  <span class="co"># randomly shuffle the two values of each rows</span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">simplify =</span> T   <span class="co"># to have a matrix output (and not a list)</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Difference of means of both species under h0</span></span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a>  p_h0 <span class="ot">&lt;-</span> <span class="fu">sum</span>(permuted_data[,<span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">sum</span>(permuted_data[,<span class="dv">2</span>])</span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Add to null distribution</span></span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  null_distribution <span class="ot">&lt;-</span> <span class="fu">c</span>(null_distribution, p_h0)</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Compare the observed statistic to the null distribution of test statistics</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CALCULATE SIGNIFICANCE THRESHOLD</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>bornes <span class="ot">&lt;-</span> <span class="fu">quantile</span>(null_distribution,<span class="fu">c</span>(.<span class="dv">95</span>))</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># VISUALISATION</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(null_distribution,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span>,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">TeX</span>(<span class="st">"$P_{H0}$"</span>),</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="fl">1.5</span>,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="co"># POSITION THRESHOLD </span></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> bornes, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">12</span>, <span class="at">y =</span> <span class="dv">750</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$quantile(1 - </span><span class="sc">\\</span><span class="st">alpha)$"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> .<span class="dv">8</span>)</span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a><span class="co"># POSITION P_OBS</span></span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> p_obs, <span class="at">lwd =</span> <span class="fl">2.5</span>, <span class="at">col =</span> <span class="st">"darkolivegreen4"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="sc">-</span><span class="dv">5</span>, <span class="at">y =</span> <span class="dv">750</span>, <span class="at">labels =</span> <span class="fu">TeX</span>(<span class="st">"$P_{obs}$"</span>), <span class="at">col =</span> <span class="st">"darkolivegreen4"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this section, we hypothesized a direction of the effect by stating that the sepal length would be greater after the use of the fertilizer. Hence, we’ll calculate the p-value as the number of null observations greater than the observed test statistic (not in absolute value!):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(null_distribution <span class="sc">&gt;</span> p_obs) <span class="sc">/</span> iteration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7029</code></pre>
</div>
</div></li>
<li><p><strong>Conclude on accepting or rejecting the null hypothesis</strong></p>
<p>As <span class="math inline">\(p &gt; 0.05\)</span>, we don’t reject the null hypothesis, suggesting that a difference is not observed before and after fertilizer usage.</p></li>
</ol>
<p>In the next part, we delve into the Mantel test, a statistical method used to assess the correlation between two distance matrices. This test is particularly valuable in fields such as ecology and genetics, where understanding the spatial or temporal relationships between entities is crucial.<br>
</p>
</section>
</section>
</section>
<section id="mantel-tests" class="level2">
<h2 class="anchored" data-anchor-id="mantel-tests">Mantel tests</h2>
<section id="uses" class="level3">
<h3 class="anchored" data-anchor-id="uses">Uses</h3>
<p>The Mantel test <span class="citation" data-cites="mantel_detection_1967">(<a href="#ref-mantel_detection_1967" role="doc-biblioref">Mantel 1967</a>)</span> is used to evaluate the relationship between two matrices of correspondences measured on the same individuals. The two correspondence (distances) matrices are denoted by <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Here, the null hypothesis describes the independence of the mechanisms governing the distances between individuals. The Mantel test is mainly used for testing correlations between genetics or geographical distances. The H0 distribution is obtained by permuting the individuals between them. We will use the data set “ozone” from the website UCLA (https://stats.idre.ucla.edu/stat/r/faq/ozone.csv). In this case, Mantel’s test is used to know more about correlations between ozone differences and geographical distances between stations. In other terms: Is the ozone variability independent of the geographical variability?</p>
</section>
<section id="correspondence-distances-matrices" class="level3">
<h3 class="anchored" data-anchor-id="correspondence-distances-matrices">Correspondence (distances) matrices</h3>
<p>The first step is to extract the distances matrix of geographical distances and ozone distances between each station. Here, we select the five first individuals of the distances matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Download a dataset </span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>ozone <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://stats.idre.ucla.edu/stat/r/faq/ozone.csv"</span>, <span class="at">sep=</span><span class="st">","</span>, <span class="at">header=</span>T)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co"># We create a sub sample of the data set</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>ozone <span class="ot">&lt;-</span> ozone[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ozone), <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>),]</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create distance matrices of geographical and ozone distances</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>station.dists <span class="ot">&lt;-</span> <span class="fu">dist</span>(<span class="fu">cbind</span>(ozone<span class="sc">$</span>Lon, ozone<span class="sc">$</span>Lat))</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>ozone.dists <span class="ot">&lt;-</span> <span class="fu">dist</span>(ozone<span class="sc">$</span>Av8top)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">4</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">5</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">6</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">7</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">8</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">9</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">1</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">4.35</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center;">3.09</td>
<td style="text-align: center;">3.79</td>
<td style="text-align: center;">3.69</td>
<td style="text-align: center;">0.44</td>
<td style="text-align: center;">1.63</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">2</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">4.06</td>
<td style="text-align: center;">0.64</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">2.80</td>
<td style="text-align: center;">3.50</td>
<td style="text-align: center;">3.40</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">1.34</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">3</td>
<td style="text-align: center;">4.35</td>
<td style="text-align: center;">4.06</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">4.69</td>
<td style="text-align: center;">4.74</td>
<td style="text-align: center;">1.25</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">3.90</td>
<td style="text-align: center;">2.72</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">4</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.64</td>
<td style="text-align: center;">4.69</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">3.44</td>
<td style="text-align: center;">4.14</td>
<td style="text-align: center;">4.03</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">1.98</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">5</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">4.74</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">3.49</td>
<td style="text-align: center;">4.19</td>
<td style="text-align: center;">4.08</td>
<td style="text-align: center;">0.84</td>
<td style="text-align: center;">2.02</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">6</td>
<td style="text-align: center;">3.09</td>
<td style="text-align: center;">2.80</td>
<td style="text-align: center;">1.25</td>
<td style="text-align: center;">3.44</td>
<td style="text-align: center;">3.49</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.70</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">2.65</td>
<td style="text-align: center;">1.46</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">7</td>
<td style="text-align: center;">3.79</td>
<td style="text-align: center;">3.50</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">4.14</td>
<td style="text-align: center;">4.19</td>
<td style="text-align: center;">0.70</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">3.35</td>
<td style="text-align: center;">2.17</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">8</td>
<td style="text-align: center;">3.69</td>
<td style="text-align: center;">3.40</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">4.03</td>
<td style="text-align: center;">4.08</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">3.24</td>
<td style="text-align: center;">2.06</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">9</td>
<td style="text-align: center;">0.44</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">3.90</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">0.84</td>
<td style="text-align: center;">2.65</td>
<td style="text-align: center;">3.35</td>
<td style="text-align: center;">3.24</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">10</td>
<td style="text-align: center;">1.63</td>
<td style="text-align: center;">1.34</td>
<td style="text-align: center;">2.72</td>
<td style="text-align: center;">1.98</td>
<td style="text-align: center;">2.02</td>
<td style="text-align: center;">1.46</td>
<td style="text-align: center;">2.17</td>
<td style="text-align: center;">2.06</td>
<td style="text-align: center;">1.19</td>
<td style="text-align: center;">0.00</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The distances matrix must be a squared matrix. Now we can apply the Mantel test our to matrix.</p>
<p><br>
</p>
</section>
<section id="mantels-test-application" class="level3">
<h3 class="anchored" data-anchor-id="mantels-test-application">Mantel’s test application</h3>
<p>There are some packages available to perform the Mantel test. For example, the <code>ade4</code> package with the <code>mantel. rtest()</code> function as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">123</span>) </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>mod_ade <span class="ot">&lt;-</span> ade4<span class="sc">::</span><span class="fu">mantel.rtest</span>(<span class="fu">as.dist</span>(station.dists), <span class="fu">as.dist</span>(ozone.dists), <span class="at">nrepet =</span> <span class="dv">1000</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>mod_ade</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte-Carlo test
Call: ade4::mantel.rtest(m1 = as.dist(station.dists), m2 = as.dist(ozone.dists), 
    nrepet = 1000)

Observation: 0.2169789 

Based on 1000 replicates
Simulated p-value: 0.08691309 
Alternative hypothesis: greater 

     Std.Obs  Expectation     Variance 
 1.587656484 -0.001886359  0.019003800 </code></pre>
</div>
</div>
<p>The coefficient of correlation observed is -0.2 and the p-value is 0.9. If we put the threshold of significance at 0.05 the correlation is not significant here!</p>
<p>Another example of package is the <code>vegan</code> package which allows to use of different correlation statistics. In our case, we chose the Pearson correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the vegan package, pearson correlation</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mantel</span>(<span class="at">xdis =</span> station.dists, <span class="at">ydis =</span> ozone.dists, <span class="at">permutations =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mantel statistic based on Pearson's product-moment correlation 

Call:
mantel(xdis = station.dists, ydis = ozone.dists, permutations = 1000) 

Mantel statistic r: 0.217 
      Significance: 0.082917 

Upper quantiles of permutations (null model):
  90%   95% 97.5%   99% 
0.188 0.279 0.366 0.468 
Permutation: free
Number of permutations: 1000</code></pre>
</div>
</div>
<p>Using this package, the results are similar. well! The p-value is indicated after the term “Significance:” and the correlation coefficient follows the term “Mantel statistic r”.</p>
<p><br>
</p>
<p>The mantel test evaluates the significance of the regression line between the two distance matrix. We saw that the mantel test is not significant. We detected no correlations between distances. Let’s plot the results:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="permutation-test-on-bootstrapped-data" class="level2">
<h2 class="anchored" data-anchor-id="permutation-test-on-bootstrapped-data">Permutation test on bootstrapped data</h2>
<p>Exploring the precision of our calculated statistic becomes particularly insightful. To achieve a robust assessment, we could opt for a combined approach, integrating both bootstrap and permutation methodologies. In this process, we would initiate a permutation test on each pseudo-data set generated through bootstrapping. The objective is to collect the statistic for each iteration, resulting in a distribution that effectively communicates the variance of estimation linked to the difference in means. This combined technique not only provides a confidence interval around our statistic but also enhances the overall reliability of our findings by accounting for the complexities and uncertainties inherent in the data. Note that combining both re-sampling techniques can be computationally intensive.</p>
<p><br>
</p>
<p>To illustrate, we will consider construct the following model :</p>
<p><span class="math display">\[
\text{Sepal length} = \beta + \alpha(\text{Sepal Width}) + \epsilon \sim \mathcal{N}(0, \sigma^2)
\]</span></p>
<p>With <span class="math inline">\(\beta\)</span> representing the intercept, <span class="math inline">\(\alpha\)</span> as the regression coefficient, and <span class="math inline">\(\epsilon\)</span> denoting the error. The objective is to ascertain (i) the confidence interval of the regression estimate <span class="math inline">\(\alpha\)</span> and (ii) the associated p-value. To achieve this, we will utilize a subset of the iris dataset comprising 25 randomly selected samples of the <em>I. versicolor</em> species:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># SUBSET OF IRIS (n=25)</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>sub_data <span class="ot">&lt;-</span> iris[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>,] </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>sub_data <span class="ot">&lt;-</span> sub_data[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(sub_data), <span class="at">size =</span> <span class="dv">25</span>, <span class="at">replace =</span> F),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, the plan is to conduct <span class="math inline">\(j\)</span> bootstrap datasets to evaluate the confidence intervals for both estimates <span class="math inline">\(\alpha_{obs}\)</span> and <span class="math inline">\(\beta_{obs}\)</span>. For each of these <span class="math inline">\(j\)</span> bootstrapped datasets, we will execute <span class="math inline">\(i\)</span> permutation tests and calculate the mean value of the estimates from these <span class="math inline">\(i\)</span> permutation tests to construct our null distribution. Subsequently, we will determine the confidence interval of the bootstrapped distribution of <span class="math inline">\(\alpha\)</span> and assess its significance by comparing it to the null distribution. Let’s proceed. First, we calculate the observed <span class="math inline">\(\alpha\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OBSERVED ALPHA</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>alpha_observed <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Sepal.Width, <span class="at">data =</span> sub_data)<span class="sc">$</span>coefficients[[<span class="dv">2</span>]], <span class="dv">2</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>alpha_observed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.98</code></pre>
</div>
</div>
<p>Our observed <span class="math inline">\(\alpha = 0.98\)</span>. We’ll keep it for later. Now, we’ll perform the combined bootstrapped / permutation procedure :</p>
<div class="cell" data-hash="r_chapter_boostrapping_resampling_cache/html/unnamed-chunk-48_0189e23cbb63b1868df55d78d41cf07e">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co"># NUMBER OF ITERATION</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>bootstrap_iteration <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>permu_iteration <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="co"># STORAGE</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Null distribution</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>null_distribution <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> bootstrap_iteration, <span class="at">ncol =</span> <span class="dv">1</span>)</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(null_distribution) <span class="ot">&lt;-</span> <span class="st">"alpha"</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Storage of mean of permuted values</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>permu_a <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Storage of the bootstrap value of a</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>boot_a <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ALGORITHM</span></span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="co"># BOOTSTRAP</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>bootstrap_iteration){</span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Random sampling with replacement of rows tp generate bootstrap data </span></span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>  row_alea <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(sub_data), <span class="at">replace =</span> T)</span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>  boot_data <span class="ot">&lt;-</span> sub_data[row_alea,]</span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Model with bootstraped data</span></span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Sepal.Width,</span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> boot_data  <span class="co"># bootstraped data</span></span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Store the boostrapped estimates</span></span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a>  boot_a[j] <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[[<span class="dv">2</span>]]</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-36"><a href="#cb74-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># PERMUTATION OF boostrapped DATA</span></span>
<span id="cb74-37"><a href="#cb74-37" aria-hidden="true" tabindex="-1"></a>   <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>permu_iteration){</span>
<span id="cb74-38"><a href="#cb74-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-39"><a href="#cb74-39" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb74-40"><a href="#cb74-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- random sampling WITHOUT replacement</span></span>
<span id="cb74-41"><a href="#cb74-41" aria-hidden="true" tabindex="-1"></a>  y_permuted <span class="ot">&lt;-</span> <span class="fu">sample</span>(boot_data<span class="sc">$</span>Sepal.Length, <span class="at">replace =</span> F)</span>
<span id="cb74-42"><a href="#cb74-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-43"><a href="#cb74-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Model with permuted data</span></span>
<span id="cb74-44"><a href="#cb74-44" aria-hidden="true" tabindex="-1"></a>  mod_permu <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_permuted <span class="sc">~</span> Sepal.Width,</span>
<span id="cb74-45"><a href="#cb74-45" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> boot_data)</span>
<span id="cb74-46"><a href="#cb74-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-47"><a href="#cb74-47" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Store of the estimates of permuted data</span></span>
<span id="cb74-48"><a href="#cb74-48" aria-hidden="true" tabindex="-1"></a>  permu_a[i] <span class="ot">&lt;-</span> mod_permu<span class="sc">$</span>coefficients[[<span class="dv">2</span>]]</span>
<span id="cb74-49"><a href="#cb74-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-50"><a href="#cb74-50" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb74-51"><a href="#cb74-51" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-52"><a href="#cb74-52" aria-hidden="true" tabindex="-1"></a> <span class="co"># --- Mean values of the i permuted values of estimates for the j bootstrap iteration</span></span>
<span id="cb74-53"><a href="#cb74-53" aria-hidden="true" tabindex="-1"></a> null_distribution[j] <span class="ot">&lt;-</span> <span class="fu">mean</span>(permu_a)</span>
<span id="cb74-54"><a href="#cb74-54" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb74-55"><a href="#cb74-55" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot our two distributions :</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="r_chapter_boostrapping_resampling_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We observe a notable distinction between the bootstrapped distribution and the null distribution. To formalize this, we calculate the p-value, defined as the overlap between both distributions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(null_distribution <span class="sc">&gt;</span> boot_a) <span class="sc">/</span> bootstrap_iteration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0012</code></pre>
</div>
</div>
<p>We obtain a p-value of <span class="math inline">\(p = 0.0012\)</span>, indicating that the coefficient is significantly greater than chance! Now, let’s leverage our combined techniques to calculate the confidence interval of this newly established significant <span class="math inline">\(\alpha\)</span> along with the associated p-value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">quantile</span>(boot_a, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 97.5% 
 0.40  1.84 </code></pre>
</div>
</div>
<p>We have an estimate of <span class="math inline">\(\alpha = 0.98 \ [0.40, 1.84]\)</span> with a <span class="math inline">\(95%\)</span> confidence interval. To further demonstrate the reliability of permutation tests, let’s compare these results with the <span class="math inline">\(\alpha\)</span> estimate of the entire dataset. Remember that we only used half of the original dataset !</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>original_data_alpha <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Sepal.Width, <span class="at">data =</span> iris[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>,])<span class="sc">$</span>coefficients[[<span class="dv">2</span>]], <span class="dv">2</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>original_data_alpha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.87</code></pre>
</div>
</div>
<p>So <span class="math inline">\(0.87 \in [0.40, 1.84]\)</span> ! With only half the original sample size, we achieved the exact same conclusion with a bootstrap and permutation procedure. Although it takes a bit more computation time and resources, this procedure is really efficient even with low sample size !</p>
<p><br>
</p>
</section>
<section id="conclusion-on-permutation-tests" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-on-permutation-tests">Conclusion on permutation tests</h2>
<p>In conclusion, permutation tests offer a powerful and flexible approach to statistical inference, especially when traditional parametric assumptions cannot be met. By iteratively permuting the observed data, these tests generate a null distribution under the assumption of no effect, enabling the assessment of the observed statistic’s significance. This makes permutation tests applicable in various scenarios, including comparisons of means, medians, correlations, or any other measure of interest.</p>
<p>While permutation tests can be computationally intensive (especially when combined with bootstrap procedures), their key advantage lies in providing reliable results with small sample sizes and non-normally distributed data. Unlike parametric tests, permutation tests do not rely on assumptions about the underlying distribution of the data, making them robust and applicable in a wide range of situations.</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abdi_jackknife_2010" class="csl-entry" role="listitem">
Abdi, Herve, and Lynne Williams. 2010. <span>“Jackknife.”</span> <em>Encyclopedia of Research Design</em>, January.
</div>
<div id="ref-mantel_detection_1967" class="csl-entry" role="listitem">
Mantel, N. 1967. <span>“<a href="https://www.ncbi.nlm.nih.gov/pubmed/6018555">The Detection of Disease Clustering and a Generalized Regression Approach</a>.”</span> <em>Cancer Research</em> 27 (2): 209–20.
</div>
<div id="ref-petit_techniques_2022" class="csl-entry" role="listitem">
Petit, Eric. 2022. <span>“Techniques de Rééchantillonnage.”</span> Rennes.
</div>
<div id="ref-quenouille_approximate_1949" class="csl-entry" role="listitem">
Quenouille, M. H. 1949. <span>“Approximate Tests of Correlation in Time‐series.”</span> <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 11 (1): 68–84. <a href="https://doi.org/10.1111/j.2517-6161.1949.tb00023.x">https://doi.org/10.1111/j.2517-6161.1949.tb00023.x</a>.
</div>
<div id="ref-sinharay_jackknife_2010" class="csl-entry" role="listitem">
Sinharay, S. 2010. <span>“Jackknife Methods.”</span> In <em>International Encyclopedia of Education</em>, 229–31. Elsevier. <a href="https://doi.org/10.1016/B978-0-08-044894-7.01338-5">https://doi.org/10.1016/B978-0-08-044894-7.01338-5</a>.
</div>
<div id="ref-tibshirani_bootstrap_2019" class="csl-entry" role="listitem">
Tibshirani, Rob. 2019. <span>“Bootstrap: Functions for the Book "an Introduction to the Bootstrap".”</span> <a href="https://cran.r-project.org/web/packages/bootstrap/index.html">https://cran.r-project.org/web/packages/bootstrap/index.html</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>